project_id = "dgznlsckoamseqcpzfqm"

[functions.pattern-detector]
verify_jwt = false

[functions.send-pattern-alert]
verify_jwt = false

[functions.pattern-scheduler]
verify_jwt = false

[functions.admin-change-membership]
verify_jwt = true

[functions.upgrade-subscription]
verify_jwt = true

[functions.subscription-webhook]
verify_jwt = false

[functions.manage-translations]
verify_jwt = false

[functions.site-string-extractor]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.generate-market-report]
verify_jwt = false

[functions.send-market-report]
verify_jwt = false

[functions.save-market-report-subscription]
verify_jwt = true

[functions.send-scheduled-market-reports]
verify_jwt = false

[functions.send-starter-scripts]
verify_jwt = false

[functions.unsubscribe-market-report]
verify_jwt = false

[functions.send-sample-market-report]
verify_jwt = false

[functions.fetch-economic-calendar]
verify_jwt = false
verify_jwt = true

[functions.send-economic-alert]
verify_jwt = false