export const QUIZ_QUESTIONS = [
  // Visual Recognition Questions
  {
    question_code: "v1",
    category: "pattern_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What pattern is shown in this candlestick chart?",
    pattern_name: "Head and Shoulders",
    pattern_key: "head-shoulders",
    options: JSON.stringify(["Head and Shoulders", "Double Top", "Triple Top"]),
    correct_answer: 0,
    explanation: "Head and Shoulders has 93% accuracy rate according to Thomas Bulkowski's Encyclopedia of Chart Patterns, with average decline of 17%. This pattern is one of the most reliable reversal indicators, consisting of three peaks where the middle peak (head) is highest. Why this matters: Professional traders at top Wall Street firms use this pattern specifically because of its high success rate - when identified correctly, it provides clear entry/exit points with predictable risk/reward ratios. The 93% success rate is based on analysis of over 10,000 historical patterns across multiple decades and market conditions.",
    tags: ["reversal", "bearish", "pattern-recognition"],
  },
  {
    question_code: "v2",
    category: "pattern_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "Identify this reversal pattern in the candlestick chart:",
    pattern_name: "Double Bottom",
    pattern_key: "double-bottom",
    options: JSON.stringify(["Cup and Handle", "Double Bottom", "Inverse Head and Shoulders"]),
    correct_answer: 1,
    explanation: "Double Bottom is a bullish reversal pattern with 79% success rate and 35% average rise according to Bulkowski's research of over 10,000 historical patterns. Why this pattern works: After a downtrend, the pattern shows two distinct attempts by sellers to push price lower, both times finding support at approximately the same level (within 3-5%). The failure of the second decline signals that selling pressure is exhausted - sellers can't push price any lower despite trying. When price breaks above the middle peak (neckline) with strong volume, it confirms that buyers have taken control.",
    tags: ["reversal", "bullish", "pattern-recognition"],
  },
  {
    question_code: "v3",
    category: "pattern_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What continuation pattern is displayed in this candlestick chart?",
    pattern_name: "Ascending Triangle",
    pattern_key: "ascending-triangle",
    options: JSON.stringify(["Ascending Triangle", "Descending Triangle", "Symmetrical Triangle"]),
    correct_answer: 0,
    explanation: "Ascending Triangle is a bullish continuation pattern that breaks upward 73% of the time with 38% average rise, according to Bulkowski's Encyclopedia. This pattern is a favorite among professional traders because it offers clear structure and reliable outcomes. How to identify it: The pattern has a flat horizontal resistance line on top (where sellers repeatedly appear at the same price level) and a rising support line on the bottom (where buyers become increasingly aggressive, bidding higher prices).",
    tags: ["continuation", "bullish", "triangle"],
  },
  {
    question_code: "v4",
    category: "pattern_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "This consolidation pattern in the candlestick chart is called:",
    pattern_name: "Bull Flag",
    pattern_key: "bull-flag",
    options: JSON.stringify(["Pennant", "Bull Flag", "Wedge"]),
    correct_answer: 1,
    explanation: "Bull Flag is one of the most reliable continuation patterns with 88% success rate and typically forms over 8 days according to Bulkowski's research. What it is: A bull flag represents a brief pause in a strong uptrend - like a 'flag' on a pole. Structure: The 'pole' is a sharp, near-vertical price advance on strong volume. The 'flag' is a rectangular consolidation that slopes slightly downward or sideways, formed on decreasing volume.",
    tags: ["continuation", "bullish", "flag"],
  },
  {
    question_code: "v5",
    category: "pattern_recognition" as const,
    difficulty: "advanced" as const,
    question_text: "What bullish pattern is shown in this candlestick chart?",
    pattern_name: "Cup with Handle",
    pattern_key: "cup-handle",
    options: JSON.stringify(["Rounding Bottom", "Cup with Handle", "Inverse Head and Shoulders"]),
    correct_answer: 1,
    explanation: "Cup and Handle is one of the most powerful and reliable bullish continuation patterns, with 86% success rate and 45% average gain according to Bulkowski's research. This pattern was popularized by William O'Neil (founder of Investor's Business Daily) who identified it in his study of the biggest stock market winners.",
    tags: ["continuation", "bullish", "cup-handle"],
  },
  {
    question_code: "v6",
    category: "pattern_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "This bearish pattern in the candlestick chart is:",
    pattern_name: "Descending Triangle",
    pattern_key: "descending-triangle",
    options: JSON.stringify(["Descending Triangle", "Falling Wedge", "Rectangle"]),
    correct_answer: 0,
    explanation: "Descending Triangle is a bearish continuation pattern that breaks downward 64% of the time with 21% average decline according to Bulkowski's Encyclopedia. What it is: This pattern shows sellers in control as buyers become progressively weaker. Structure: The pattern has a flat horizontal support line on the bottom and a descending resistance line on top.",
    tags: ["continuation", "bearish", "triangle"],
  },
  {
    question_code: "v7",
    category: "pattern_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What neutral pattern is shown in this candlestick chart?",
    pattern_name: "Symmetrical Triangle",
    pattern_key: "symmetrical-triangle",
    options: JSON.stringify(["Pennant", "Symmetrical Triangle", "Diamond"]),
    correct_answer: 1,
    explanation: "Symmetrical Triangle is a neutral continuation pattern that breaks upward 54% of the time (slight upward bias) with no directional preference, according to Bulkowski's research. What it is: This pattern represents equilibrium between buyers and sellers, with both sides becoming less aggressive as the pattern develops.",
    tags: ["continuation", "neutral", "triangle"],
  },
  {
    question_code: "v8",
    category: "pattern_recognition" as const,
    difficulty: "advanced" as const,
    question_text: "This bearish reversal pattern in the candlestick chart is:",
    pattern_name: "Rising Wedge",
    pattern_key: "rising-wedge",
    options: JSON.stringify(["Rising Wedge", "Ascending Triangle", "Bull Flag"]),
    correct_answer: 0,
    explanation: "Rising Wedge is a bearish reversal pattern that breaks downward 68% of the time with 19% average decline according to Bulkowski's Encyclopedia. What it is: Despite rising price action, this pattern signals weakening momentum and impending reversal.",
    tags: ["reversal", "bearish", "wedge"],
  },
  {
    question_code: "v9",
    category: "pattern_recognition" as const,
    difficulty: "advanced" as const,
    question_text: "This bullish reversal pattern in the candlestick chart is:",
    pattern_name: "Falling Wedge",
    pattern_key: "falling-wedge",
    options: JSON.stringify(["Descending Triangle", "Falling Wedge", "Bear Flag"]),
    correct_answer: 1,
    explanation: "Falling Wedge is a bullish reversal pattern that breaks upward 68% of the time with 35% average rise according to Bulkowski's research. What it is: Despite declining price action, this pattern signals diminishing selling pressure and impending reversal to the upside.",
    tags: ["reversal", "bullish", "wedge"],
  },
  {
    question_code: "v10",
    category: "pattern_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What reversal pattern is displayed in this candlestick chart?",
    pattern_name: "Double Top",
    pattern_key: "double-top",
    options: JSON.stringify(["Double Top", "Head and Shoulders", "Triple Top"]),
    correct_answer: 0,
    explanation: "Double Top is a bearish reversal pattern with 79% success rate and 20% average decline according to Bulkowski's Encyclopedia of Chart Patterns. What it is: This pattern signals the end of an uptrend as price fails twice to break through a resistance level.",
    tags: ["reversal", "bearish", "pattern-recognition"],
  },
  // Risk Management Questions
  {
    question_code: "r1",
    category: "risk_management" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the recommended maximum risk per trade for pattern trading?",
    options: JSON.stringify(["1-2%", "5%", "10%"]),
    correct_answer: 0,
    explanation: "Professional pattern traders risk 1-2% of capital per trade maximum. This conservative approach ensures you can survive losing streaks. Even with a 50% win rate, risking 2% per trade means you can lose 50 trades in a row and still have 63% of capital remaining. Risk more than 2%, and consecutive losses compound quickly into devastating drawdowns.",
    tags: ["risk-management", "position-sizing", "trading-rules"],
  },
  {
    question_code: "r2",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "What is the minimum risk-reward ratio professionals use for pattern trades?",
    options: JSON.stringify(["1:1", "1:2", "1:3"]),
    correct_answer: 1,
    explanation: "Professional pattern traders require minimum 1:2 risk-reward ratio. This means if you risk $100, you target at least $200 profit. With this ratio, you only need a 33% win rate to break even (not including commissions). Many institutional traders actually target 1:3 or higher, which drops the required win rate to just 25% for profitability.",
    tags: ["risk-reward", "trading-rules", "professional-standards"],
  },
  {
    question_code: "r3",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "What percentage of winning trades do professional pattern traders typically achieve?",
    options: JSON.stringify(["45-50%", "55-65%", "75-85%"]),
    correct_answer: 1,
    explanation: "Professional pattern traders typically achieve 55-65% win rates when trading high-probability setups with proper confirmation. This is significantly better than random (50%), but not the 80-90% many beginners expect. The key insight: you don't need a high win rate if your winners are much larger than your losers (good risk-reward ratio).",
    tags: ["win-rate", "statistics", "professional-trading"],
  },
  {
    question_code: "r4",
    category: "risk_management" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the recommended stop loss placement for pattern breakout trades?",
    options: JSON.stringify(["Below pattern low", "At entry price", "10% below entry"]),
    correct_answer: 0,
    explanation: "Professional traders place stops below the pattern low for long positions (or above pattern high for shorts). This placement respects the pattern's structure - if price returns into the pattern after a breakout, the pattern has failed and the trade thesis is invalidated. Stops placed randomly (like 10% below entry) don't respect market structure and often get hit before the pattern plays out.",
    tags: ["stop-loss", "pattern-trading", "risk-management"],
  },
  {
    question_code: "r5",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "What volume confirmation do institutional traders require for valid breakouts?",
    options: JSON.stringify(["25% above average", "50% above average", "100% above average"]),
    correct_answer: 1,
    explanation: "Institutional traders require volume at least 50% above average (1.5x average) for valid breakouts. This is based on decades of research showing that breakouts on light volume frequently fail, while breakouts on heavy volume tend to continue. The 50% threshold filters out most false breakouts while capturing real institutional participation.",
    tags: ["volume", "breakouts", "institutional-trading"],
  },
  // Add remaining 85+ quiz questions with similar structure...
];
