export const QUIZ_QUESTIONS = [
  // Visual Recognition Questions (15 questions from PatternQuiz.tsx)
  {
    question_code: "v1",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What pattern is shown in this candlestick chart?",
    pattern_name: "Head and Shoulders",
    pattern_key: "head-shoulders",
    options: ["Head and Shoulders", "Double Top", "Triple Top"],
    correct_answer: 0,
    explanation: "Head and Shoulders has 93% accuracy rate according to Thomas Bulkowski's Encyclopedia of Chart Patterns, with average decline of 17%. Professional traders at top Wall Street firms use this pattern specifically because of its high success rate.",
    tags: ["reversal", "bearish", "pattern-recognition"],
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "v2",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "Identify this reversal pattern in the candlestick chart:",
    pattern_name: "Double Bottom",
    pattern_key: "double-bottom",
    options: ["Cup and Handle", "Double Bottom", "Inverse Head and Shoulders"],
    correct_answer: 1,
    explanation: "Double Bottom is a bullish reversal pattern with 79% success rate and 35% average rise according to Bulkowski's research. After a downtrend, the pattern shows two distinct attempts by sellers to push price lower, both finding support at approximately the same level.",
    tags: ["reversal", "bullish", "pattern-recognition"],
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "v3",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What continuation pattern is displayed in this candlestick chart?",
    pattern_name: "Ascending Triangle",
    pattern_key: "ascending-triangle",
    options: ["Ascending Triangle", "Descending Triangle", "Symmetrical Triangle"],
    correct_answer: 0,
    explanation: "Ascending Triangle is a bullish continuation pattern that breaks upward 73% of the time with 38% average rise. The pattern has a flat horizontal resistance line on top and a rising support line on the bottom.",
    tags: ["continuation", "bullish", "triangle"],
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "v4",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "This consolidation pattern in the candlestick chart is called:",
    pattern_name: "Bull Flag",
    pattern_key: "bull-flag",
    options: ["Pennant", "Bull Flag", "Wedge"],
    correct_answer: 1,
    explanation: "Bull Flag is one of the most reliable continuation patterns with 88% success rate and typically forms over 8 days. The pole is a sharp price advance on strong volume, followed by a rectangular consolidation on decreasing volume.",
    tags: ["continuation", "bullish", "flag"],
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "v5",
    category: "visual_recognition" as const,
    difficulty: "advanced" as const,
    question_text: "What bullish pattern is shown in this candlestick chart?",
    pattern_name: "Cup with Handle",
    pattern_key: "cup-handle",
    options: ["Rounding Bottom", "Cup with Handle", "Inverse Head and Shoulders"],
    correct_answer: 1,
    explanation: "Cup and Handle has 86% success rate and 45% average gain. This pattern was popularized by William O'Neil who identified it in his study of the biggest stock market winners.",
    tags: ["continuation", "bullish", "cup-handle"],
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "v6",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "This bearish pattern in the candlestick chart is:",
    pattern_name: "Descending Triangle",
    pattern_key: "descending-triangle",
    options: ["Descending Triangle", "Falling Wedge", "Rectangle"],
    correct_answer: 0,
    explanation: "Descending Triangle breaks downward 64% of the time with 21% average decline. The pattern has a flat horizontal support line on the bottom and a descending resistance line on top.",
    tags: ["continuation", "bearish", "triangle"],
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "v7",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What neutral pattern is shown in this candlestick chart?",
    pattern_name: "Symmetrical Triangle",
    pattern_key: "symmetrical-triangle",
    options: ["Pennant", "Symmetrical Triangle", "Diamond"],
    correct_answer: 1,
    explanation: "Symmetrical Triangle breaks upward 54% of the time (slight upward bias). This pattern represents equilibrium between buyers and sellers.",
    tags: ["continuation", "neutral", "triangle"],
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "v8",
    category: "visual_recognition" as const,
    difficulty: "advanced" as const,
    question_text: "This bearish reversal pattern in the candlestick chart is:",
    pattern_name: "Rising Wedge",
    pattern_key: "rising-wedge",
    options: ["Rising Wedge", "Ascending Triangle", "Bull Flag"],
    correct_answer: 0,
    explanation: "Rising Wedge breaks downward 68% of the time with 19% average decline. Despite rising price action, this pattern signals weakening momentum and impending reversal.",
    tags: ["reversal", "bearish", "wedge"],
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "v9",
    category: "visual_recognition" as const,
    difficulty: "advanced" as const,
    question_text: "This bullish reversal pattern in the candlestick chart is:",
    pattern_name: "Falling Wedge",
    pattern_key: "falling-wedge",
    options: ["Descending Triangle", "Falling Wedge", "Bear Flag"],
    correct_answer: 1,
    explanation: "Falling Wedge breaks upward 68% of the time with 35% average rise. Despite declining price action, this pattern signals diminishing selling pressure and impending reversal.",
    tags: ["reversal", "bullish", "wedge"],
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "v10",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What reversal pattern is displayed in this candlestick chart?",
    pattern_name: "Double Top",
    pattern_key: "double-top",
    options: ["Double Top", "Head and Shoulders", "Triple Top"],
    correct_answer: 0,
    explanation: "Double Top has 79% success rate and 20% average decline. This pattern signals the end of an uptrend as price fails twice to break through a resistance level.",
    tags: ["reversal", "bearish", "pattern-recognition"],
    image_url: null,
    image_metadata: null,
  },
  // Risk Management Questions (5 questions)
  {
    question_code: "r1",
    category: "risk_management" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the recommended maximum risk per trade for pattern trading?",
    options: ["1-2%", "5%", "10%"],
    correct_answer: 0,
    explanation: "Professional pattern traders risk 1-2% of capital per trade maximum. This ensures you can survive losing streaks without catastrophic losses.",
    tags: ["risk-management", "position-sizing", "trading-rules"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "r2",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "What is the minimum risk-reward ratio professionals use for pattern trades?",
    options: ["1:1", "1:2", "1:3"],
    correct_answer: 1,
    explanation: "Professional pattern traders require minimum 1:2 risk-reward ratio. With this ratio, you only need a 33% win rate to break even.",
    tags: ["risk-reward", "trading-rules", "professional-standards"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "r3",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "What percentage of winning trades do professional pattern traders typically achieve?",
    options: ["45-50%", "55-65%", "75-85%"],
    correct_answer: 1,
    explanation: "Professional pattern traders typically achieve 55-65% win rates when trading high-probability setups with proper confirmation.",
    tags: ["win-rate", "statistics", "professional-trading"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "r4",
    category: "risk_management" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the recommended stop loss placement for pattern breakout trades?",
    options: ["Below pattern low", "At entry price", "10% below entry"],
    correct_answer: 0,
    explanation: "Professional traders place stops below the pattern low for long positions. If price returns into the pattern after a breakout, the pattern has failed.",
    tags: ["stop-loss", "pattern-trading", "risk-management"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "r5",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "What volume confirmation do institutional traders require for valid breakouts?",
    options: ["25% above average", "50% above average", "100% above average"],
    correct_answer: 1,
    explanation: "Institutional traders require volume at least 50% above average for valid breakouts. The 50% threshold filters out most false breakouts.",
    tags: ["volume", "breakouts", "institutional-trading"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  // Pattern Characteristics Questions (10 questions from PatternQuiz)
  {
    question_code: "c1",
    category: "characteristics" as const,
    difficulty: "advanced" as const,
    question_text: "According to Bulkowski, Head and Shoulders patterns fail what percentage of the time?",
    options: ["7%", "15%", "25%"],
    correct_answer: 0,
    explanation: "Head and Shoulders patterns have a 93% success rate, meaning only 7% failure rate. This makes it one of the most reliable patterns in technical analysis.",
    tags: ["head-shoulders", "statistics", "bulkowski"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "c2",
    category: "characteristics" as const,
    difficulty: "advanced" as const,
    question_text: "Double tops have what average decline according to Encyclopedia of Chart Patterns?",
    options: ["18%", "25%", "32%"],
    correct_answer: 0,
    explanation: "Bulkowski's research found double tops average 18% decline with 79% success rate, based on analysis of thousands of patterns.",
    tags: ["double-top", "statistics", "bulkowski"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "c3",
    category: "characteristics" as const,
    difficulty: "advanced" as const,
    question_text: "Cup and Handle patterns require the handle to retrace no more than what percentage?",
    options: ["25%", "38%", "50%"],
    correct_answer: 1,
    explanation: "The handle should retrace no more than 38% of the cup's advance. This is based on Fibonacci levels and ensures the pattern maintains bullish structure.",
    tags: ["cup-handle", "fibonacci", "pattern-rules"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "c4",
    category: "characteristics" as const,
    difficulty: "advanced" as const,
    question_text: "Ascending triangles have what breakout direction frequency per Bulkowski?",
    options: ["63% upward", "73% upward", "83% upward"],
    correct_answer: 1,
    explanation: "Ascending triangles break upward 73% of the time with 38% average rise. This strong upward bias makes them reliable bullish continuation patterns.",
    tags: ["ascending-triangle", "statistics", "continuation"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "c5",
    category: "characteristics" as const,
    difficulty: "intermediate" as const,
    question_text: "According to professional standards, minimum pattern duration should be:",
    options: ["7 days", "15 days", "21 days"],
    correct_answer: 1,
    explanation: "Professional standards require minimum 15-day duration for reliable pattern formation. This ensures the pattern represents genuine market psychology shifts.",
    tags: ["pattern-duration", "professional-standards"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
];
