export const QUIZ_QUESTIONS = [
  // Visual Recognition Questions (15 questions from PatternQuiz.tsx)
  {
    question_code: "v1",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What pattern is shown in this candlestick chart?",
    pattern_name: "Head and Shoulders",
    pattern_key: "head-shoulders",
    options: ["Head and Shoulders", "Double Top", "Triple Top"],
    correct_answer: 0,
    explanation: "Head and Shoulders has 93% accuracy rate according to Thomas Bulkowski's Encyclopedia of Chart Patterns, with average decline of 17%. Professional traders at top Wall Street firms use this pattern specifically because of its high success rate.",
    tags: ["reversal", "bearish", "pattern-recognition"],
    image_url: "/patterns/head-shoulders.png",
    image_metadata: { alt: "Head and Shoulders chart pattern showing left shoulder, higher head peak, and right shoulder with downward neckline break" },
  },
  {
    question_code: "v2",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "Identify this reversal pattern in the candlestick chart:",
    pattern_name: "Double Bottom",
    pattern_key: "double-bottom",
    options: ["Cup and Handle", "Double Bottom", "Inverse Head and Shoulders"],
    correct_answer: 1,
    explanation: "Double Bottom is a bullish reversal pattern with 79% success rate and 35% average rise according to Bulkowski's research. After a downtrend, the pattern shows two distinct attempts by sellers to push price lower, both finding support at approximately the same level.",
    tags: ["reversal", "bullish", "pattern-recognition"],
    image_url: "/patterns/double-bottom.png",
    image_metadata: { alt: "Double Bottom chart pattern showing two valley lows at same price level with upward breakout" },
  },
  {
    question_code: "v3",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What continuation pattern is displayed in this candlestick chart?",
    pattern_name: "Ascending Triangle",
    pattern_key: "ascending-triangle",
    options: ["Ascending Triangle", "Descending Triangle", "Symmetrical Triangle"],
    correct_answer: 0,
    explanation: "Ascending Triangle is a bullish continuation pattern that breaks upward 73% of the time with 38% average rise. The pattern has a flat horizontal resistance line on top and a rising support line on the bottom.",
    tags: ["continuation", "bullish", "triangle"],
    image_url: "/patterns/ascending-triangle.png",
    image_metadata: { alt: "Ascending Triangle chart pattern with flat horizontal resistance and rising support trendline" },
  },
  {
    question_code: "v4",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "This consolidation pattern in the candlestick chart is called:",
    pattern_name: "Bull Flag",
    pattern_key: "bull-flag",
    options: ["Pennant", "Bull Flag", "Wedge"],
    correct_answer: 1,
    explanation: "Bull Flag is one of the most reliable continuation patterns with 88% success rate and typically forms over 8 days. The pole is a sharp price advance on strong volume, followed by a rectangular consolidation on decreasing volume.",
    tags: ["continuation", "bullish", "flag"],
    image_url: "/patterns/bull-flag.png",
    image_metadata: { alt: "Bull Flag chart pattern with steep upward pole and rectangular consolidation flag" },
  },
  {
    question_code: "v5",
    category: "visual_recognition" as const,
    difficulty: "advanced" as const,
    question_text: "What bullish pattern is shown in this candlestick chart?",
    pattern_name: "Cup with Handle",
    pattern_key: "cup-handle",
    options: ["Rounding Bottom", "Cup with Handle", "Inverse Head and Shoulders"],
    correct_answer: 1,
    explanation: "Cup and Handle has 86% success rate and 45% average gain. This pattern was popularized by William O'Neil who identified it in his study of the biggest stock market winners.",
    tags: ["continuation", "bullish", "cup-handle"],
    image_url: "/patterns/cup-handle.png",
    image_metadata: { alt: "Cup with Handle chart pattern showing U-shaped cup formation with small downward handle" },
  },
  {
    question_code: "v6",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "This bearish pattern in the candlestick chart is:",
    pattern_name: "Descending Triangle",
    pattern_key: "descending-triangle",
    options: ["Descending Triangle", "Falling Wedge", "Rectangle"],
    correct_answer: 0,
    explanation: "Descending Triangle breaks downward 64% of the time with 21% average decline. The pattern has a flat horizontal support line on the bottom and a descending resistance line on top.",
    tags: ["continuation", "bearish", "triangle"],
    image_url: "/patterns/descending-triangle.png",
    image_metadata: { alt: "Descending Triangle chart pattern with flat horizontal support and descending resistance trendline" },
  },
  {
    question_code: "v7",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What neutral pattern is shown in this candlestick chart?",
    pattern_name: "Symmetrical Triangle",
    pattern_key: "symmetrical-triangle",
    options: ["Pennant", "Symmetrical Triangle", "Diamond"],
    correct_answer: 1,
    explanation: "Symmetrical Triangle breaks upward 54% of the time (slight upward bias). This pattern represents equilibrium between buyers and sellers.",
    tags: ["continuation", "neutral", "triangle"],
    image_url: "/patterns/symmetrical-triangle.png",
    image_metadata: { alt: "Symmetrical Triangle chart pattern with converging trendlines forming triangle shape" },
  },
  {
    question_code: "v8",
    category: "visual_recognition" as const,
    difficulty: "advanced" as const,
    question_text: "This bearish reversal pattern in the candlestick chart is:",
    pattern_name: "Rising Wedge",
    pattern_key: "rising-wedge",
    options: ["Rising Wedge", "Ascending Triangle", "Bull Flag"],
    correct_answer: 0,
    explanation: "Rising Wedge breaks downward 68% of the time with 19% average decline. Despite rising price action, this pattern signals weakening momentum and impending reversal.",
    tags: ["reversal", "bearish", "wedge"],
    image_url: "/patterns/rising-wedge.png",
    image_metadata: { alt: "Rising Wedge chart pattern with both trendlines sloping upward and converging" },
  },
  {
    question_code: "v9",
    category: "visual_recognition" as const,
    difficulty: "advanced" as const,
    question_text: "This bullish reversal pattern in the candlestick chart is:",
    pattern_name: "Falling Wedge",
    pattern_key: "falling-wedge",
    options: ["Descending Triangle", "Falling Wedge", "Bear Flag"],
    correct_answer: 1,
    explanation: "Falling Wedge breaks upward 68% of the time with 35% average rise. Despite declining price action, this pattern signals diminishing selling pressure and impending reversal.",
    tags: ["reversal", "bullish", "wedge"],
    image_url: "/patterns/falling-wedge.png",
    image_metadata: { alt: "Falling Wedge chart pattern with both trendlines sloping downward and converging" },
  },
  {
    question_code: "v10",
    category: "visual_recognition" as const,
    difficulty: "intermediate" as const,
    question_text: "What reversal pattern is displayed in this candlestick chart?",
    pattern_name: "Double Top",
    pattern_key: "double-top",
    options: ["Double Top", "Head and Shoulders", "Triple Top"],
    correct_answer: 0,
    explanation: "Double Top has 79% success rate and 20% average decline. This pattern signals the end of an uptrend as price fails twice to break through a resistance level.",
    tags: ["reversal", "bearish", "pattern-recognition"],
    image_url: "/patterns/double-top.png",
    image_metadata: { alt: "Double Top chart pattern showing two peak highs at same price level with M-shape formation" },
  },
  // Risk Management Questions (5 questions)
  {
    question_code: "r1",
    category: "risk_management" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the recommended maximum risk per trade for pattern trading?",
    options: ["1-2%", "5%", "10%"],
    correct_answer: 0,
    explanation: "Professional pattern traders risk 1-2% of capital per trade maximum. This ensures you can survive losing streaks without catastrophic losses.",
    tags: ["risk-management", "position-sizing", "trading-rules"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "r2",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "What is the minimum risk-reward ratio professionals use for pattern trades?",
    options: ["1:1", "1:2", "1:3"],
    correct_answer: 1,
    explanation: "Professional pattern traders require minimum 1:2 risk-reward ratio. With this ratio, you only need a 33% win rate to break even.",
    tags: ["risk-reward", "trading-rules", "professional-standards"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "r3",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "What percentage of winning trades do professional pattern traders typically achieve?",
    options: ["45-50%", "55-65%", "75-85%"],
    correct_answer: 1,
    explanation: "Professional pattern traders typically achieve 55-65% win rates when trading high-probability setups with proper confirmation.",
    tags: ["win-rate", "statistics", "professional-trading"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "r4",
    category: "risk_management" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the recommended stop loss placement for pattern breakout trades?",
    options: ["Below pattern low", "At entry price", "10% below entry"],
    correct_answer: 0,
    explanation: "Professional traders place stops below the pattern low for long positions. If price returns into the pattern after a breakout, the pattern has failed.",
    tags: ["stop-loss", "pattern-trading", "risk-management"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "r5",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "What volume confirmation do institutional traders require for valid breakouts?",
    options: ["25% above average", "50% above average", "100% above average"],
    correct_answer: 1,
    explanation: "Institutional traders require volume at least 50% above average for valid breakouts. The 50% threshold filters out most false breakouts.",
    tags: ["volume", "breakouts", "institutional-trading"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  // Pattern Characteristics Questions (10 questions from PatternQuiz)
  {
    question_code: "c1",
    category: "characteristics" as const,
    difficulty: "advanced" as const,
    question_text: "According to Bulkowski, Head and Shoulders patterns fail what percentage of the time?",
    options: ["7%", "15%", "25%"],
    correct_answer: 0,
    explanation: "Head and Shoulders patterns have a 93% success rate, meaning only 7% failure rate. This makes it one of the most reliable patterns in technical analysis.",
    tags: ["head-shoulders", "statistics", "bulkowski"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "c2",
    category: "characteristics" as const,
    difficulty: "advanced" as const,
    question_text: "Double tops have what average decline according to Encyclopedia of Chart Patterns?",
    options: ["18%", "25%", "32%"],
    correct_answer: 0,
    explanation: "Bulkowski's research found double tops average 18% decline with 79% success rate, based on analysis of thousands of patterns.",
    tags: ["double-top", "statistics", "bulkowski"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "c3",
    category: "characteristics" as const,
    difficulty: "advanced" as const,
    question_text: "Cup and Handle patterns require the handle to retrace no more than what percentage?",
    options: ["25%", "38%", "50%"],
    correct_answer: 1,
    explanation: "The handle should retrace no more than 38% of the cup's advance. This is based on Fibonacci levels and ensures the pattern maintains bullish structure.",
    tags: ["cup-handle", "fibonacci", "pattern-rules"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "c4",
    category: "characteristics" as const,
    difficulty: "advanced" as const,
    question_text: "Ascending triangles have what breakout direction frequency per Bulkowski?",
    options: ["63% upward", "73% upward", "83% upward"],
    correct_answer: 1,
    explanation: "Ascending triangles break upward 73% of the time with 38% average rise. This strong upward bias makes them reliable bullish continuation patterns.",
    tags: ["ascending-triangle", "statistics", "continuation"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "c5",
    category: "characteristics" as const,
    difficulty: "intermediate" as const,
    question_text: "According to professional standards, minimum pattern duration should be:",
    options: ["7 days", "15 days", "21 days"],
    correct_answer: 1,
    explanation: "Professional standards require minimum 15-day duration for reliable pattern formation. This ensures the pattern represents genuine market psychology shifts.",
    tags: ["pattern-duration", "professional-standards"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  
  // Economic Calendar & Fundamentals (10 questions)
  {
    question_code: "ec1",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "Which economic event typically has the highest impact on currency markets?",
    options: ["Non-Farm Payrolls (NFP)", "Consumer Sentiment", "Manufacturing PMI"],
    correct_answer: 0,
    explanation: "Non-Farm Payrolls is one of the most influential economic indicators, often causing 100+ pip moves in major currency pairs. Released first Friday of each month, it measures employment changes excluding farm workers, government employees, and non-profit organization employees.",
    tags: ["economic-calendar", "fundamentals", "forex"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ec2",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What does a central bank interest rate increase typically do to a currency?",
    options: ["Strengthens it", "Weakens it", "No effect"],
    correct_answer: 0,
    explanation: "Higher interest rates typically strengthen a currency as they attract foreign capital seeking better returns. This is a fundamental principle in forex trading taught by central bank policy analysts worldwide.",
    tags: ["interest-rates", "central-banks", "fundamentals"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ec3",
    category: "professional_practices" as const,
    difficulty: "advanced" as const,
    question_text: "When is the FOMC (Federal Open Market Committee) meeting typically scheduled?",
    options: ["Every 2 weeks", "Every 6 weeks", "Monthly"],
    correct_answer: 1,
    explanation: "The FOMC meets approximately every 6 weeks (8 times per year) to set monetary policy. These meetings are critical for USD-based pairs and global markets, with the policy statement and press conference often moving markets significantly.",
    tags: ["fed", "monetary-policy", "economic-calendar"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ec4",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What GDP growth rate is generally considered healthy for developed economies?",
    options: ["1-2%", "2-3%", "4-5%"],
    correct_answer: 1,
    explanation: "Most developed economies target 2-3% annual GDP growth. This rate is considered optimal for sustainable growth without triggering excessive inflation, according to major central banks like the Fed and ECB.",
    tags: ["gdp", "economic-indicators", "fundamentals"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ec5",
    category: "professional_practices" as const,
    difficulty: "advanced" as const,
    question_text: "What is a 'hawkish' central bank stance?",
    options: ["Favoring lower interest rates", "Favoring higher interest rates", "Neutral policy"],
    correct_answer: 1,
    explanation: "A hawkish stance means the central bank favors raising interest rates to combat inflation. Traders monitor central bank communications for hawkish or dovish signals to anticipate policy changes. This terminology is standard across all major financial institutions.",
    tags: ["monetary-policy", "central-banks", "terminology"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ec6",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What CPI (Consumer Price Index) level do most central banks target for inflation?",
    options: ["1%", "2%", "3%"],
    correct_answer: 1,
    explanation: "Most major central banks (Fed, ECB, BOE, BOJ) target 2% annual inflation as measured by CPI or similar indices. This target balances price stability with economic growth objectives.",
    tags: ["inflation", "cpi", "central-banks"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ec7",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "When should you avoid entering new trades based on the economic calendar?",
    options: ["During major news releases", "During Asian session", "During weekends"],
    correct_answer: 0,
    explanation: "Professional traders avoid entering new positions 15-30 minutes before and during major news releases due to high volatility and widened spreads. This risk management practice is standard across institutional trading desks.",
    tags: ["news-trading", "risk-management", "timing"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ec8",
    category: "statistics" as const,
    difficulty: "advanced" as const,
    question_text: "What is a leading economic indicator?",
    options: ["Predicts future activity", "Reports past activity", "Shows current activity"],
    correct_answer: 0,
    explanation: "Leading indicators predict future economic activity. Examples include stock market performance, manufacturing orders, and building permits. Institutional analysts use leading indicators to anticipate economic cycles ahead of lagging indicators like unemployment.",
    tags: ["economic-indicators", "analysis", "fundamentals"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ec9",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What does PMI (Purchasing Managers' Index) measure?",
    options: ["Business activity", "Consumer spending", "Employment levels"],
    correct_answer: 0,
    explanation: "PMI measures business activity in manufacturing and services sectors. A reading above 50 indicates expansion, below 50 indicates contraction. PMI is released monthly and is considered a leading indicator of economic health.",
    tags: ["pmi", "economic-indicators", "business-cycle"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ec10",
    category: "professional_practices" as const,
    difficulty: "advanced" as const,
    question_text: "What typically happens to stock markets when the Fed raises interest rates?",
    options: ["Usually decline", "Usually rally", "No correlation"],
    correct_answer: 0,
    explanation: "Rising interest rates typically pressure stock markets lower because: 1) Higher borrowing costs reduce corporate profits, 2) Bonds become more attractive alternatives, 3) Economic growth may slow. However, initial rate hikes in a cycle may be viewed positively if they signal economic strength.",
    tags: ["interest-rates", "stocks", "correlations"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },

  // Pip Calculations & Position Sizing (8 questions)
  {
    question_code: "pc1",
    category: "risk_management" as const,
    difficulty: "beginner" as const,
    question_text: "What is a 'pip' in forex trading?",
    options: ["The smallest price increment", "A trading strategy", "A type of order"],
    correct_answer: 0,
    explanation: "A pip (percentage in point) is the smallest price move in most currency pairs, typically the 4th decimal place (0.0001). For JPY pairs, it's the 2nd decimal place (0.01). This standardization is used globally across all forex platforms.",
    tags: ["pips", "forex-basics", "terminology"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "pc2",
    category: "risk_management" as const,
    difficulty: "intermediate" as const,
    question_text: "If EUR/USD moves from 1.1000 to 1.1050, how many pips did it move?",
    options: ["5 pips", "50 pips", "500 pips"],
    correct_answer: 1,
    explanation: "The move from 1.1000 to 1.1050 is 0.0050, which equals 50 pips. Each 0.0001 movement represents 1 pip in major currency pairs. Accurate pip calculation is essential for risk management.",
    tags: ["pip-calculation", "forex", "math"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "pc3",
    category: "risk_management" as const,
    difficulty: "intermediate" as const,
    question_text: "With a $10,000 account risking 1% per trade, what is your maximum loss per trade?",
    options: ["$10", "$100", "$1,000"],
    correct_answer: 1,
    explanation: "$10,000 × 1% = $100 maximum risk per trade. This 1% rule is the gold standard in professional risk management, recommended by risk managers at top trading firms worldwide.",
    tags: ["position-sizing", "risk-management", "math"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "pc4",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "You have a $10,000 account, risk 1%, and your stop loss is 50 pips on EUR/USD. What lot size should you trade? (Assume $10/pip for 1 standard lot)",
    options: ["0.2 lots", "0.5 lots", "1.0 lot"],
    correct_answer: 0,
    explanation: "Risk = $100 (1% of $10,000). With 50 pip stop, you need: $100 ÷ 50 pips = $2 per pip. Since 1 standard lot = $10/pip, you need: $2 ÷ $10 = 0.2 lots. This calculation methodology is standard across institutional trading desks.",
    tags: ["position-sizing", "lot-calculation", "risk-management"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "pc5",
    category: "risk_management" as const,
    difficulty: "intermediate" as const,
    question_text: "What is a standard lot in forex trading?",
    options: ["10,000 units", "100,000 units", "1,000,000 units"],
    correct_answer: 1,
    explanation: "A standard lot is 100,000 units of the base currency. A mini lot is 10,000 units, and a micro lot is 1,000 units. Understanding lot sizes is crucial for proper position sizing and risk management.",
    tags: ["lot-sizes", "forex-basics", "position-sizing"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "pc6",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "If you risk $100 on a trade with 1:3 risk-reward ratio, what is your potential profit?",
    options: ["$100", "$200", "$300"],
    correct_answer: 2,
    explanation: "With 1:3 risk-reward ratio, for every $1 risked, you target $3 profit. Risk of $100 × 3 = $300 potential profit. Professional traders typically target minimum 1:2 or 1:3 ratios to maintain positive expectancy.",
    tags: ["risk-reward", "trade-planning", "math"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "pc7",
    category: "risk_management" as const,
    difficulty: "advanced" as const,
    question_text: "What is the Kelly Criterion used for in trading?",
    options: ["Optimal position sizing", "Entry timing", "Stop loss placement"],
    correct_answer: 0,
    explanation: "The Kelly Criterion calculates optimal position size based on win rate and risk-reward ratio. Formula: (Win% × Avg Win - Loss% × Avg Loss) ÷ Avg Win. However, most traders use 'Half Kelly' or fixed percentage for safety. This mathematical framework was developed by John Kelly and is used by quantitative trading firms.",
    tags: ["position-sizing", "kelly-criterion", "advanced-concepts"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "pc8",
    category: "risk_management" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the recommended maximum portfolio heat (total risk across all open positions)?",
    options: ["2-3%", "5-6%", "10-12%"],
    correct_answer: 1,
    explanation: "Professional traders limit total portfolio risk (all open positions combined) to 5-6% maximum. Even if each trade risks 1-2%, having too many correlated positions increases overall portfolio risk. This diversification principle is emphasized in CFA curriculum.",
    tags: ["portfolio-risk", "risk-management", "professional-standards"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },

  // Market Sessions & Timing (6 questions)
  {
    question_code: "mt1",
    category: "professional_practices" as const,
    difficulty: "beginner" as const,
    question_text: "Which forex trading session has the highest volume?",
    options: ["Asian", "London", "New York"],
    correct_answer: 1,
    explanation: "The London session accounts for approximately 35% of forex volume, making it the most liquid session. This concentration occurs because London is the world's largest forex trading center.",
    tags: ["market-sessions", "volume", "forex"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "mt2",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the most volatile period in forex trading?",
    options: ["Asian session", "London-NY overlap", "After NY close"],
    correct_answer: 1,
    explanation: "The London-New York overlap (8 AM - 12 PM EST) sees highest volatility and volume as both major markets are open. This 4-hour window accounts for over 50% of daily forex movements.",
    tags: ["market-sessions", "volatility", "timing"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "mt3",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "When does the forex market open each week?",
    options: ["Sunday 5 PM EST", "Monday 9 AM EST", "Monday 12 AM GMT"],
    correct_answer: 0,
    explanation: "The forex market opens Sunday at 5 PM EST (when Wellington, New Zealand opens Monday morning local time) and closes Friday at 5 PM EST. This 24-hour, 5-day-a-week schedule is standard globally.",
    tags: ["market-hours", "forex-basics", "timing"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "mt4",
    category: "professional_practices" as const,
    difficulty: "beginner" as const,
    question_text: "When is the best time to trade range-bound strategies in forex?",
    options: ["Asian session", "London session", "NY session"],
    correct_answer: 0,
    explanation: "The Asian session (quietest session) typically sees range-bound price action, making it suitable for range trading strategies. Lower volatility means price respects support/resistance levels better.",
    tags: ["market-sessions", "strategy-timing", "ranging"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "mt5",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What typically happens to spreads during major news releases?",
    options: ["Decrease", "Widen significantly", "Stay the same"],
    correct_answer: 1,
    explanation: "Spreads widen during high-impact news due to increased volatility and reduced liquidity as market makers protect themselves. Spreads can double or triple, significantly affecting trade costs. This is why professional traders adjust position sizes or avoid trading during news.",
    tags: ["spreads", "news-trading", "costs"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "mt6",
    category: "professional_practices" as const,
    difficulty: "advanced" as const,
    question_text: "What is 'trading the fix' in forex markets?",
    options: ["Trading at 4 PM London time", "Fixing broken trades", "Day trading strategy"],
    correct_answer: 0,
    explanation: "The 'London Fix' or 'WMR Fix' occurs at 4 PM London time when benchmark FX rates are set for the day. Large institutional orders can cause volatility spikes. Understanding these structural market events helps professional traders avoid adverse price action.",
    tags: ["market-structure", "institutional-trading", "timing"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },

  // Trade Execution & Order Types (7 questions)
  {
    question_code: "te1",
    category: "professional_practices" as const,
    difficulty: "beginner" as const,
    question_text: "What is a 'market order'?",
    options: ["Executed immediately at current price", "Executed at specific price", "Pending order"],
    correct_answer: 0,
    explanation: "A market order executes immediately at the best available price. While guaranteed fill, there's no price guarantee - you may experience slippage in fast markets. This is the most basic order type taught in all trading courses.",
    tags: ["order-types", "execution", "basics"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "te2",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What is a 'limit order'?",
    options: ["Buy below market or sell above", "Buy above market or sell below", "Same as market order"],
    correct_answer: 0,
    explanation: "A limit order to buy is placed below current market price (buy when price drops). A limit order to sell is placed above current price (sell when price rises). You get price guarantee but no fill guarantee. Professional traders use limit orders to achieve better entry prices.",
    tags: ["order-types", "limit-orders", "execution"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "te3",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What is a 'stop-loss order'?",
    options: ["Limits losses by closing at preset level", "Takes profit automatically", "Prevents slippage"],
    correct_answer: 0,
    explanation: "A stop-loss automatically closes your position when price reaches a predetermined level, limiting your loss. This is a risk management essential - every professional trade should have a stop-loss before entry. Institutional risk management requires documented stop-losses on all positions.",
    tags: ["stop-loss", "risk-management", "order-types"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "te4",
    category: "professional_practices" as const,
    difficulty: "advanced" as const,
    question_text: "What is a 'trailing stop'?",
    options: ["Fixed stop level", "Stop that follows price in your favor", "Stop before support"],
    correct_answer: 1,
    explanation: "A trailing stop automatically adjusts upward (for long positions) as price moves in your favor, locking in profits while allowing the trade room to run. For example, a 50-pip trailing stop stays 50 pips below the highest price reached. This technique is used by trend-following traders to maximize gains.",
    tags: ["trailing-stop", "trade-management", "advanced"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "te5",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What does 'slippage' mean in trading?",
    options: ["Difference between expected and actual fill price", "Profit reduction", "Stop loss movement"],
    correct_answer: 0,
    explanation: "Slippage occurs when your order executes at a different price than expected, typically during fast markets or low liquidity. Can be positive or negative. Professional traders account for average slippage when calculating real costs of trading.",
    tags: ["slippage", "execution", "costs"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "te6",
    category: "professional_practices" as const,
    difficulty: "advanced" as const,
    question_text: "What is an 'OCO' (One-Cancels-Other) order?",
    options: ["Two linked orders where filling one cancels other", "Order that cancels at end of day", "Cancellation fee"],
    correct_answer: 0,
    explanation: "OCO orders link two orders together - when one executes, the other automatically cancels. Commonly used to set both take-profit and stop-loss simultaneously, or to trade breakouts in either direction. This advanced order type is standard on professional trading platforms.",
    tags: ["oco-orders", "advanced-orders", "execution"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "te7",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "When scaling out of a position, what is best practice?",
    options: ["Close all at once", "Take partial profits at targets", "Hold until stop"],
    correct_answer: 1,
    explanation: "Professional traders often scale out by taking partial profits at predetermined targets (e.g., 50% at 1:1, 25% at 1:2, 25% at 1:3) while moving stop to breakeven. This balances profit-taking with letting winners run. Strategy varies by trading style but partial profit-taking is widely used institutionally.",
    tags: ["trade-management", "scaling-out", "profit-taking"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },

  // Trading Psychology & Discipline (6 questions)
  {
    question_code: "tp1",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the most common psychological mistake traders make?",
    options: ["Cutting winners short, letting losers run", "Trading too small", "Over-analyzing"],
    correct_answer: 0,
    explanation: "The classic mistake is cutting winning trades too early (fear of losing profits) while holding losing trades too long (hope of recovery). This violates the fundamental rule: cut losses short, let winners run. Behavioral finance studies show this stems from loss aversion bias.",
    tags: ["psychology", "common-mistakes", "discipline"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "tp2",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "Why is keeping a trading journal important?",
    options: ["Tax records", "Identify patterns in behavior and improve", "Broker requirement"],
    correct_answer: 1,
    explanation: "A trading journal helps identify patterns in your behavior, mistakes, and successful setups. Professional traders review journals weekly/monthly to continuously improve. Studies show traders who journal perform 25-30% better than those who don't. This practice is emphasized in professional trader development programs.",
    tags: ["trading-journal", "improvement", "discipline"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "tp3",
    category: "professional_practices" as const,
    difficulty: "advanced" as const,
    question_text: "What is 'revenge trading'?",
    options: ["Trading to recover losses emotionally", "Competitive trading", "Scalping strategy"],
    correct_answer: 0,
    explanation: "Revenge trading occurs when traders try to quickly recover losses by taking impulsive, oversized trades driven by emotion rather than strategy. This often leads to even bigger losses. Professional risk managers identify this as a top cause of account blowouts and require cooling-off periods after losses.",
    tags: ["psychology", "emotional-trading", "discipline"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "tp4",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What should you do after a series of losing trades?",
    options: ["Trade larger to recover", "Take a break and review", "Switch strategies completely"],
    correct_answer: 1,
    explanation: "After losing streaks, professional traders take a break to review trades objectively and ensure they're following their plan. Losing streaks are normal - even with 60% win rate, you can have 5-6 losers in a row statistically. Emotional distance prevents revenge trading. This practice is standard in institutional trading desks.",
    tags: ["losing-streaks", "discipline", "psychology"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "tp5",
    category: "professional_practices" as const,
    difficulty: "intermediate" as const,
    question_text: "What is 'FOMO' in trading?",
    options: ["Fear Of Missing Out", "Fixed Order Management", "Forex Market Operations"],
    correct_answer: 0,
    explanation: "FOMO (Fear Of Missing Out) causes traders to jump into trades impulsively without proper analysis because they fear missing profit opportunities. This leads to poor entries and trading outside your plan. Professional traders combat FOMO by focusing on their own setups and accepting that you can't catch every move.",
    tags: ["fomo", "psychology", "discipline"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "tp6",
    category: "professional_practices" as const,
    difficulty: "advanced" as const,
    question_text: "What percentage of trading success is attributed to psychology vs strategy?",
    options: ["50% psychology, 50% strategy", "80% psychology, 20% strategy", "20% psychology, 80% strategy"],
    correct_answer: 1,
    explanation: "Most professional traders and trading psychologists agree that trading is 80% psychology and 20% strategy. Having a great strategy means nothing if you can't follow it consistently. Emotional control, discipline, and proper mindset separate successful traders from unsuccessful ones. This is emphasized across all professional trading education programs.",
    tags: ["psychology", "success-factors", "mindset"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },

  // Market Analysis & Correlations (5 questions)
  {
    question_code: "ma1",
    category: "statistics" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the typical correlation between EUR/USD and USD/CHF?",
    options: ["Positive correlation", "Negative correlation", "No correlation"],
    correct_answer: 1,
    explanation: "EUR/USD and USD/CHF typically have strong negative correlation (around -0.85 to -0.95). When EUR/USD rises, USD/CHF usually falls because USD is in the denominator of EUR/USD but numerator of USD/CHF. Understanding correlations prevents overexposure to the same directional risk.",
    tags: ["correlations", "forex", "risk-management"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ma2",
    category: "statistics" as const,
    difficulty: "intermediate" as const,
    question_text: "Gold typically has what relationship with the US Dollar?",
    options: ["Positive correlation", "Inverse correlation", "Random"],
    correct_answer: 1,
    explanation: "Gold and USD typically have inverse correlation - when USD strengthens, gold tends to weaken (priced in USD). Also, gold is seen as an alternative store of value to USD. This relationship is foundational in commodity trading and is monitored by all major hedge funds.",
    tags: ["gold", "usd", "correlations"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ma3",
    category: "statistics" as const,
    difficulty: "advanced" as const,
    question_text: "What is 'risk-on' vs 'risk-off' sentiment?",
    options: ["Risk tolerance levels", "Market environment affecting asset flows", "Position sizing method"],
    correct_answer: 1,
    explanation: "Risk-on means investors favor higher-yielding, riskier assets (stocks, commodities, carry trades). Risk-off means flight to safety (USD, JPY, gold, bonds). Recognizing the risk environment helps predict currency movements - for example, JPY strengthens during risk-off periods. This framework is used daily by institutional traders.",
    tags: ["risk-sentiment", "market-environment", "analysis"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ma4",
    category: "statistics" as const,
    difficulty: "intermediate" as const,
    question_text: "What does increasing VIX (Volatility Index) typically indicate?",
    options: ["Market fear/uncertainty", "Market confidence", "Ranging market"],
    correct_answer: 0,
    explanation: "VIX measures S&P 500 option-implied volatility and is known as the 'fear gauge'. Rising VIX indicates increasing market fear and uncertainty. VIX above 30 suggests high fear; below 12 suggests complacency. Forex traders monitor VIX as it affects overall risk sentiment.",
    tags: ["vix", "volatility", "risk-sentiment"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "ma5",
    category: "professional_practices" as const,
    difficulty: "advanced" as const,
    question_text: "What are the three pillars of market analysis?",
    options: ["Technical, Fundamental, Sentiment", "Price, Volume, Time", "Trend, Support, Resistance"],
    correct_answer: 0,
    explanation: "The three pillars are: Technical (charts/patterns), Fundamental (economic data), and Sentiment (market positioning/psychology). Professional traders use all three for comprehensive analysis - technical for timing, fundamental for direction, sentiment for confirmation. This framework is taught in CFA and CMT programs.",
    tags: ["market-analysis", "analysis-types", "professional-standards"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  // Stock Market Specific Questions
  {
    question_code: "sm1",
    category: "stock_market" as const,
    difficulty: "intermediate" as const,
    question_text: "What does P/E ratio measure in stock analysis?",
    options: ["Price to Earnings ratio", "Profit to Equity ratio", "Price to Enterprise value"],
    correct_answer: 0,
    explanation: "Price-to-Earnings (P/E) ratio measures stock price relative to earnings per share. P/E of 15 means investors pay $15 for every $1 of earnings. Used to determine if stock is overvalued or undervalued. Source: Benjamin Graham's 'Security Analysis' and CFA Level 1 curriculum.",
    tags: ["fundamental-analysis", "valuation", "stock-metrics"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm2",
    category: "stock_market" as const,
    difficulty: "beginner" as const,
    question_text: "What is a blue-chip stock?",
    options: ["Large, established, financially stable company", "Technology startup", "Penny stock"],
    correct_answer: 0,
    explanation: "Blue-chip stocks are shares of large, well-established companies with stable earnings and reliable dividends (e.g., Apple, Microsoft, Johnson & Johnson). The term comes from poker where blue chips have the highest value. Source: NYSE trading standards.",
    tags: ["stock-types", "classification", "terminology"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm3",
    category: "stock_market" as const,
    difficulty: "intermediate" as const,
    question_text: "What time does regular US stock market trading begin (EST)?",
    options: ["9:30 AM", "8:00 AM", "10:00 AM"],
    correct_answer: 0,
    explanation: "Regular NYSE and NASDAQ trading hours are 9:30 AM to 4:00 PM EST. Pre-market trading runs 4:00-9:30 AM, after-hours 4:00-8:00 PM. The market opening at 9:30 AM often sees high volatility and volume. Source: NYSE and NASDAQ official trading hours.",
    tags: ["market-hours", "trading-sessions", "timing"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm4",
    category: "stock_market" as const,
    difficulty: "advanced" as const,
    question_text: "What is the most reliable indicator of stock market health?",
    options: ["Market breadth (advance-decline line)", "Single index price", "Average P/E ratio"],
    correct_answer: 0,
    explanation: "Market breadth measures how many stocks are advancing vs declining. When few stocks drive index higher while most decline, it signals weakness. Strong markets show broad participation. Professional traders monitor NYSE advance-decline line daily. Source: Martin Zweig's 'Winning on Wall Street'.",
    tags: ["market-breadth", "technical-indicators", "market-health"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm5",
    category: "stock_market" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the key difference between a stock split and dividend?",
    options: ["Split increases shares/lowers price; dividend pays cash", "No difference", "Split pays cash; dividend increases shares"],
    correct_answer: 0,
    explanation: "Stock split divides existing shares (e.g., 2-for-1 doubles shares, halves price) without changing total value. Dividends pay cash/stock to shareholders from earnings. Splits make shares more affordable; dividends provide income. Both are positive signals. Source: SEC investor education materials.",
    tags: ["corporate-actions", "stock-mechanics", "terminology"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  // Forex Specific Questions
  {
    question_code: "fx1",
    category: "forex" as const,
    difficulty: "beginner" as const,
    question_text: "What does EUR/USD = 1.0850 mean?",
    options: ["1 Euro equals 1.0850 US Dollars", "1 Dollar equals 1.0850 Euros", "Exchange rate percentage"],
    correct_answer: 0,
    explanation: "In forex pairs, the first currency (base) is always 1 unit. EUR/USD = 1.0850 means 1 Euro equals 1.0850 US Dollars. If it rises to 1.0900, the Euro strengthened. Understanding quote conventions is fundamental. Source: Bank for International Settlements (BIS) forex standards.",
    tags: ["forex-basics", "currency-pairs", "quote-convention"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx2",
    category: "forex" as const,
    difficulty: "intermediate" as const,
    question_text: "Which forex session typically has the highest volatility?",
    options: ["London-New York overlap", "Asian session", "Sydney session"],
    correct_answer: 0,
    explanation: "London-New York overlap (8 AM - 12 PM EST) sees 70% of daily forex volume. London opens at 3 AM EST, New York at 8 AM. This 4-hour overlap creates maximum liquidity and volatility, offering best trading opportunities. Source: BIS Triennial Survey.",
    tags: ["forex-sessions", "trading-hours", "volatility"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx3",
    category: "forex" as const,
    difficulty: "advanced" as const,
    question_text: "What is the carry trade strategy?",
    options: ["Borrow low-yield currency, invest in high-yield", "Day trading currency pairs", "Hedging currency risk"],
    correct_answer: 0,
    explanation: "Carry trade borrows low-interest currency (e.g., JPY at 0.1%) to buy high-interest currency (e.g., AUD at 4.35%), profiting from interest differential. Works in stable markets but risky during volatility. Used by hedge funds managing billions. Source: IMF Working Papers on carry trade.",
    tags: ["carry-trade", "interest-rates", "strategies"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx4",
    category: "forex" as const,
    difficulty: "intermediate" as const,
    question_text: "What is a pip in forex trading?",
    options: ["0.0001 price movement (4th decimal)", "1% price movement", "Minimum trade size"],
    correct_answer: 0,
    explanation: "Pip (percentage in point) is smallest price move, typically 0.0001 for most pairs. EUR/USD moving from 1.0850 to 1.0851 = 1 pip. JPY pairs use 0.01. Critical for calculating profit/loss and position sizing. Source: International Organization for Standardization (ISO) forex standards.",
    tags: ["forex-terminology", "pip-calculation", "basics"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx5",
    category: "forex" as const,
    difficulty: "advanced" as const,
    question_text: "Which central bank decision has the greatest global forex impact?",
    options: ["US Federal Reserve interest rate decision", "Bank of Japan decision", "European Central Bank decision"],
    correct_answer: 0,
    explanation: "Federal Reserve rate decisions affect USD, which is involved in 88% of forex transactions globally. Fed moves impact all markets due to USD's reserve currency status. NFP data and FOMC minutes also create major volatility. Source: Federal Reserve Board and BIS statistics.",
    tags: ["central-banks", "interest-rates", "market-impact"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  // Cryptocurrency Specific Questions
  {
    question_code: "cr1",
    category: "cryptocurrency" as const,
    difficulty: "beginner" as const,
    question_text: "What is Bitcoin's maximum supply?",
    options: ["21 million coins", "Unlimited", "100 million coins"],
    correct_answer: 0,
    explanation: "Bitcoin's supply is capped at 21 million coins by its protocol. This scarcity is built into the code and cannot be changed without consensus. As of 2024, approximately 19.5 million are mined. The last Bitcoin will be mined around 2140. Source: Bitcoin whitepaper by Satoshi Nakamoto.",
    tags: ["bitcoin", "supply", "fundamentals"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr2",
    category: "cryptocurrency" as const,
    difficulty: "intermediate" as const,
    question_text: "What is a cryptocurrency halving event?",
    options: ["Mining rewards cut in half", "Price drops by 50%", "Trading volume halves"],
    correct_answer: 0,
    explanation: "Bitcoin halving occurs every 210,000 blocks (≈4 years), cutting mining rewards by 50%. Started at 50 BTC per block (2009), now 3.125 BTC (2024). Reduces new supply issuance, historically correlating with price increases. Next halving: 2028. Source: Bitcoin blockchain protocol.",
    tags: ["halving", "supply-dynamics", "bitcoin"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr3",
    category: "cryptocurrency" as const,
    difficulty: "advanced" as const,
    question_text: "What is the primary factor that drives crypto market cycles?",
    options: ["Bitcoin halving cycles", "Government regulation", "Mining difficulty"],
    correct_answer: 0,
    explanation: "Bitcoin's 4-year halving cycle historically drives crypto bull/bear markets. Halving reduces supply while demand grows, creating price pressure. 2012, 2016, 2020 halvings preceded bull runs. Institutional analysts now track this cycle for positioning. Source: On-chain analytics firms (Glassnode, CryptoQuant).",
    tags: ["market-cycles", "halving", "analysis"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr4",
    category: "cryptocurrency" as const,
    difficulty: "intermediate" as const,
    question_text: "What is DeFi (Decentralized Finance)?",
    options: ["Financial services without intermediaries on blockchain", "Digital currency exchange", "Cryptocurrency mining"],
    correct_answer: 0,
    explanation: "DeFi provides financial services (lending, borrowing, trading) through smart contracts without banks or brokers. Built primarily on Ethereum. Users maintain custody of funds. Examples: Uniswap (trading), Aave (lending), MakerDAO (stablecoins). Source: Ethereum Foundation and DeFi Pulse.",
    tags: ["defi", "blockchain", "applications"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr5",
    category: "cryptocurrency" as const,
    difficulty: "beginner" as const,
    question_text: "What time does cryptocurrency market close for the day?",
    options: ["It never closes - 24/7/365 trading", "Closes at 5 PM EST", "Closes on weekends"],
    correct_answer: 0,
    explanation: "Cryptocurrency markets operate 24 hours a day, 7 days a week, 365 days a year. Unlike stocks or forex, there are no trading hours or market closures. This continuous operation provides flexibility but requires discipline and automated risk management. Source: All major crypto exchanges.",
    tags: ["trading-hours", "market-structure", "basics"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  // Commodities Specific Questions
  {
    question_code: "cm1",
    category: "commodities" as const,
    difficulty: "beginner" as const,
    question_text: "Which commodity is often called 'digital gold'?",
    options: ["Bitcoin", "Silver", "Platinum"],
    correct_answer: 0,
    explanation: "Bitcoin is called 'digital gold' due to similar properties: limited supply, store of value, inflation hedge. While physical gold has 5,000-year history, Bitcoin offers digital scarcity and portability. Many institutional investors now allocate to both. Source: JP Morgan and Goldman Sachs research reports.",
    tags: ["commodities", "bitcoin", "terminology"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm2",
    category: "commodities" as const,
    difficulty: "intermediate" as const,
    question_text: "What is contango in commodity futures?",
    options: ["Future price > spot price", "Spot price > future price", "Equal prices"],
    correct_answer: 0,
    explanation: "Contango occurs when futures prices exceed spot prices, typically due to storage costs, insurance, and financing. Common in oil, gold. Investors pay 'cost of carry' to hold position. Opposite is backwardation. Understanding this is critical for commodity futures trading. Source: CME Group educational materials.",
    tags: ["futures", "contango", "market-structure"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm3",
    category: "commodities" as const,
    difficulty: "advanced" as const,
    question_text: "Why does gold often rise when stocks fall?",
    options: ["Gold is a safe-haven asset and inverse correlation", "Gold production decreases", "Central banks buy gold"],
    correct_answer: 0,
    explanation: "Gold has -0.6 correlation with S&P 500 during crises. During market stress, investors flee to safety, buying gold, bonds, USD. Gold preserves wealth during uncertainty. Professional portfolio managers use 5-10% gold allocation for diversification. Source: World Gold Council research spanning 50+ years.",
    tags: ["gold", "safe-haven", "correlations"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm4",
    category: "commodities" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the most traded commodity futures contract globally?",
    options: ["WTI Crude Oil", "Gold", "Natural Gas"],
    correct_answer: 0,
    explanation: "WTI (West Texas Intermediate) Crude Oil is the world's most actively traded commodity futures. Daily volume exceeds 1 million contracts ($50B+ notional). Oil drives global economy and forex markets. Professional traders monitor oil-CAD and oil-NOK correlations. Source: CME Group volume statistics.",
    tags: ["oil", "futures", "volume"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm5",
    category: "commodities" as const,
    difficulty: "advanced" as const,
    question_text: "What does the gold-to-silver ratio indicate?",
    options: ["Relative value between gold and silver", "Gold purity measurement", "Mining profitability"],
    correct_answer: 0,
    explanation: "Gold-silver ratio shows how many ounces of silver equal one ounce of gold. Historical average: 60-70. Above 80 suggests silver undervalued; below 50 suggests overvalued. Ratio mean-reverts over time. Professional commodity traders use this for pairs trading. Source: LBMA historical data.",
    tags: ["gold-silver-ratio", "relative-value", "pairs-trading"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm6",
    category: "commodities" as const,
    difficulty: "intermediate" as const,
    question_text: "Which report has the largest impact on crude oil prices?",
    options: ["EIA Weekly Petroleum Status Report", "OPEC Monthly Report", "Baker Hughes Rig Count"],
    correct_answer: 0,
    explanation: "EIA (Energy Information Administration) releases weekly US petroleum inventory data every Wednesday at 10:30 AM EST. Unexpected inventory changes cause immediate volatility. Crude stockpiles, gasoline demand, refinery utilization all impact prices. All professional oil traders monitor this religiously. Source: EIA official reports.",
    tags: ["oil", "inventory-data", "economic-reports"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm7",
    category: "commodities" as const,
    difficulty: "advanced" as const,
    question_text: "What is backwardation in commodity markets?",
    options: ["Spot price > future price", "Future price > spot price", "Price stagnation"],
    correct_answer: 0,
    explanation: "Backwardation occurs when spot prices exceed futures prices, indicating strong current demand or supply concerns. Common during supply shocks or geopolitical tensions. Signals bullish sentiment. Roll yield is positive in backwardation, negative in contango. Critical concept for commodity funds. Source: Academic studies on commodity term structure.",
    tags: ["backwardation", "futures", "term-structure"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm8",
    category: "commodities" as const,
    difficulty: "intermediate" as const,
    question_text: "Which factor has the greatest impact on agricultural commodity prices?",
    options: ["Weather patterns and crop reports", "Currency fluctuations", "Interest rates"],
    correct_answer: 0,
    explanation: "Weather drives agricultural prices - drought, floods, frost all impact supply. USDA crop reports (released monthly) provide planting intentions, yield estimates, inventory data. These reports cause extreme volatility. Professional ag traders monitor weather services and USDA religiously. Source: USDA National Agricultural Statistics Service.",
    tags: ["agriculture", "weather", "supply-factors"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm9",
    category: "commodities" as const,
    difficulty: "beginner" as const,
    question_text: "What is a commodity CFD?",
    options: ["Contract for Difference - derivative tracking commodity price", "Certified Futures Dealer", "Commodity Futures Document"],
    correct_answer: 0,
    explanation: "CFD (Contract for Difference) is a derivative allowing speculation on commodity price movements without owning physical commodity or futures. Offers leverage, no expiry dates, smaller contract sizes. Popular for retail traders. Regulated differently than futures. Source: FCA and ESMA regulatory guidelines.",
    tags: ["cfd", "derivatives", "trading-instruments"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm10",
    category: "commodities" as const,
    difficulty: "advanced" as const,
    question_text: "How do professional traders use the COT (Commitments of Traders) report?",
    options: ["Track commercial hedger vs speculator positioning", "Monitor commodity inventory levels", "Predict weather patterns"],
    correct_answer: 0,
    explanation: "COT report (released Friday, data through Tuesday) shows futures positioning by commercials (hedgers), large speculators (funds), and small speculators (retail). Extreme positioning often precedes reversals. Commercials are typically right at extremes. All serious commodity traders analyze COT weekly. Source: CFTC official COT reports.",
    tags: ["cot-report", "positioning", "sentiment-analysis"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm11",
    category: "commodities" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the London Gold Fix?",
    options: ["Twice-daily gold price benchmark", "Storage facility in London", "Gold purity standard"],
    correct_answer: 0,
    explanation: "London Gold Fix (now LBMA Gold Price) occurs twice daily (10:30 AM and 3:00 PM London time) via electronic auction. Sets benchmark used globally for contracts, derivatives, mining companies. Replaced telephone fixing in 2015 for transparency. Source: London Bullion Market Association (LBMA).",
    tags: ["gold", "benchmark", "price-fixing"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm12",
    category: "commodities" as const,
    difficulty: "advanced" as const,
    question_text: "Why do commodity currencies (AUD, CAD, NOK) correlate with commodity prices?",
    options: ["Their economies heavily export commodities", "Central bank policies", "Geographic location"],
    correct_answer: 0,
    explanation: "Australia exports iron ore/coal (AUD rises with commodity boom), Canada exports oil (CAD follows WTI), Norway exports oil/gas (NOK tracks Brent). When commodities rally, these currencies strengthen from export revenues and terms of trade. Professional forex traders monitor commodity prices for these currencies. Source: Reserve Bank of Australia and Bank of Canada research.",
    tags: ["commodity-currencies", "correlations", "forex"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm13",
    category: "commodities" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the VIX equivalent for oil markets?",
    options: ["OVX (Crude Oil Volatility Index)", "USO (Oil ETF)", "API Report"],
    correct_answer: 0,
    explanation: "OVX measures expected 30-day volatility of crude oil derived from options. Like VIX for stocks, high OVX indicates fear/uncertainty in oil markets. Spikes during geopolitical events, OPEC surprises, inventory shocks. Professional energy traders monitor OVX for risk management. Source: CBOE (Chicago Board Options Exchange).",
    tags: ["volatility", "ovx", "risk-indicators"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm14",
    category: "commodities" as const,
    difficulty: "beginner" as const,
    question_text: "What does OPEC stand for and why is it important?",
    options: ["Organization of Petroleum Exporting Countries - controls 40% of oil supply", "Oil Production and Export Commission", "Offshore Petroleum Energy Council"],
    correct_answer: 0,
    explanation: "OPEC is cartel of 13 oil-producing nations controlling ~40% of global oil production and 60% of international oil trade. OPEC+ (includes Russia) coordinates production cuts/increases affecting global prices. Their meetings cause major market volatility. Source: OPEC official statistics and IEA reports.",
    tags: ["opec", "oil", "supply-control"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm15",
    category: "commodities" as const,
    difficulty: "advanced" as const,
    question_text: "What is the crack spread in oil markets?",
    options: ["Refining margin between crude oil and refined products", "Oil price volatility measure", "Geographic price differential"],
    correct_answer: 0,
    explanation: "Crack spread measures refinery profit margin - difference between crude oil input cost and refined product (gasoline, diesel, heating oil) output value. Typically expressed as 3-2-1 (3 barrels crude to 2 barrels gasoline, 1 barrel diesel). Wide spreads = high refinery profitability. Professional energy traders arbitrage this. Source: CME Group crack spread contracts.",
    tags: ["crack-spread", "refining", "arbitrage"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },

  // Additional Stock Market Questions
  {
    question_code: "sm6",
    category: "stock_market" as const,
    difficulty: "advanced" as const,
    question_text: "What is the Shiller P/E (CAPE) ratio and why is it important?",
    options: ["P/E based on 10-year average earnings, predicts long-term returns", "Current quarter P/E ratio", "Price to book value ratio"],
    correct_answer: 0,
    explanation: "CAPE (Cyclically Adjusted Price-to-Earnings) ratio, developed by Nobel laureate Robert Shiller, divides current S&P 500 price by average inflation-adjusted earnings over past 10 years. Smooths earnings volatility. Historically, CAPE above 30 preceded poor 10-year returns; below 15 preceded strong returns. Currently ~30-35. Professional value investors monitor CAPE for market valuation. Source: 'Irrational Exuberance' by Robert Shiller.",
    tags: ["valuation", "cape-ratio", "market-timing"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm7",
    category: "stock_market" as const,
    difficulty: "intermediate" as const,
    question_text: "What does the VIX above 30 historically indicate?",
    options: ["High market fear, often marks capitulation/bottoms", "Bull market strength", "Normal market conditions"],
    correct_answer: 0,
    explanation: "VIX above 30 indicates extreme fear and uncertainty. Historical spikes: 2008 financial crisis (80+), 2020 COVID (85), 2022 selloff (37). Paradoxically, extreme VIX spikes often mark market bottoms as fear reaches climax. Professional traders buy volatility premium when VIX is low (<12), sell when high (>30). Source: CBOE VIX historical data and academic studies.",
    tags: ["vix", "volatility", "contrarian-indicators"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm8",
    category: "stock_market" as const,
    difficulty: "advanced" as const,
    question_text: "What is the '2% rule' in stock market trading?",
    options: ["Never risk more than 2% of capital on single trade", "Market gains 2% annually", "Rebalance at 2% threshold"],
    correct_answer: 0,
    explanation: "The 2% rule states never risk more than 2% of total trading capital on any single trade. With $100,000 account, maximum risk per trade is $2,000. This allows surviving 50 consecutive losses (extremely unlikely with proper strategy). Combined with 1:2 risk-reward, you only need 33% win rate to profit. All professional trading firms enforce strict risk rules. Source: Mark Douglas 'Trading in the Zone' and institutional risk management protocols.",
    tags: ["risk-management", "position-sizing", "professional-rules"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm9",
    category: "stock_market" as const,
    difficulty: "intermediate" as const,
    question_text: "What is a market order vs limit order?",
    options: ["Market executes immediately at current price; limit executes only at specified price", "No difference", "Market is for large orders; limit for small"],
    correct_answer: 0,
    explanation: "Market order executes immediately at best available price (guaranteed fill, price uncertain). Limit order only executes at specified price or better (price guaranteed, fill uncertain). In fast markets or illiquid stocks, market orders can have significant slippage. Professionals use limit orders to control execution price, especially for large positions. Source: SEC Investor Bulletin on order types.",
    tags: ["order-types", "execution", "trading-mechanics"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm10",
    category: "stock_market" as const,
    difficulty: "advanced" as const,
    question_text: "What is the most important metric for evaluating stock market indices health?",
    options: ["Cumulative advance-decline line", "Index price level", "Average P/E ratio"],
    correct_answer: 0,
    explanation: "Cumulative advance-decline line (advancing stocks minus declining stocks, cumulative sum) is the single best breadth indicator. When S&P 500 makes new highs but A-D line doesn't, it shows only few stocks driving index - bearish divergence. Strong bull markets have both making new highs together. Martin Zweig called A-D line 'most valuable single indicator'. All professional traders monitor breadth daily. Source: 'Winning on Wall Street' by Martin Zweig.",
    tags: ["market-breadth", "technical-indicators", "divergence"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm11",
    category: "stock_market" as const,
    difficulty: "beginner" as const,
    question_text: "What is a stock's dividend yield?",
    options: ["Annual dividend divided by stock price, expressed as percentage", "Total dividends paid in a year", "Dividend growth rate"],
    correct_answer: 0,
    explanation: "Dividend yield = (Annual dividend / Stock price) × 100. If stock trades at $100 and pays $3 annual dividend, yield is 3%. Yields above 4% are considered high; above 7% may signal risk. Dividend aristocrats maintain/grow dividends for 25+ years. Income-focused investors prioritize yield. Source: S&P Dow Jones Indices dividend methodology.",
    tags: ["dividends", "yield", "income-investing"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm12",
    category: "stock_market" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the significance of the 200-day moving average?",
    options: ["Major support/resistance level watched by institutions", "Average daily return", "Volatility measure"],
    correct_answer: 0,
    explanation: "The 200-day MA is the most widely watched long-term trend indicator. Price above 200-MA = bull market; below = bear market. S&P 500 crossing above/below 200-MA triggers billions in systematic fund flows. Acts as magnet - prices often revert to test it. Professional portfolio managers use 200-MA for asset allocation decisions. Source: Academic research on moving average strategies and institutional surveys.",
    tags: ["moving-averages", "technical-analysis", "trend"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm13",
    category: "stock_market" as const,
    difficulty: "advanced" as const,
    question_text: "What is the most reliable predictor of 10-year stock returns?",
    options: ["Starting valuation (Shiller P/E or P/E ratio)", "GDP growth rate", "Previous 10-year returns"],
    correct_answer: 0,
    explanation: "Starting valuation has ~80% correlation with subsequent 10-year returns. Buy when CAPE <15 = average 10-year return 12%+ annually. Buy when CAPE >30 = average return 0-3% annually. This relationship holds globally across 100+ years. Short-term, valuations don't matter; long-term, they're everything. Source: Multiple academic studies including Shiller's data spanning 140+ years.",
    tags: ["valuation", "long-term-returns", "statistical-relationships"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm14",
    category: "stock_market" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the difference between NYSE and NASDAQ?",
    options: ["NYSE is auction market; NASDAQ is dealer market", "NYSE for stocks; NASDAQ for bonds", "No operational difference"],
    correct_answer: 0,
    explanation: "NYSE operates as auction market with specialists maintaining orderly markets for each stock (hybrid electronic/floor). NASDAQ is fully electronic dealer market with market makers competing. NYSE traditionally lists older, larger companies (blue chips). NASDAQ lists more tech companies. Both are equally reputable and liquid. Source: NYSE and NASDAQ official documentation.",
    tags: ["market-structure", "exchanges", "trading-venues"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "sm15",
    category: "stock_market" as const,
    difficulty: "beginner" as const,
    question_text: "What is market capitalization?",
    options: ["Stock price × total shares outstanding", "Total annual revenue", "Company's total assets"],
    correct_answer: 0,
    explanation: "Market cap = Stock Price × Shares Outstanding. Represents total market value of company. Categories: Mega-cap >$200B (Apple, Microsoft), Large-cap $10-200B, Mid-cap $2-10B, Small-cap $300M-$2B, Micro-cap <$300M. Large-caps are less volatile but lower growth; small-caps more volatile but higher growth potential. Source: S&P index methodology.",
    tags: ["market-cap", "company-size", "classification"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },

  // Additional Forex Questions
  {
    question_code: "fx6",
    category: "forex" as const,
    difficulty: "advanced" as const,
    question_text: "What is the most important economic indicator for forex traders?",
    options: ["Non-Farm Payrolls (NFP) and interest rate decisions", "GDP growth", "Trade balance"],
    correct_answer: 0,
    explanation: "Non-Farm Payrolls (released first Friday of month, 8:30 AM EST) shows US employment change. Strong NFP = USD strength. Creates extreme volatility - 100+ pip moves common. Interest rate decisions from Fed, ECB, BoE, BoJ are equally critical. Professional forex traders prepare for NFP with reduced position sizes or flatten positions entirely. Source: Federal Reserve research and forex market analysis.",
    tags: ["nfp", "economic-indicators", "market-movers"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx7",
    category: "forex" as const,
    difficulty: "intermediate" as const,
    question_text: "What is standard lot size in forex?",
    options: ["100,000 units of base currency", "10,000 units", "1,000 units"],
    correct_answer: 0,
    explanation: "Standard lot = 100,000 units base currency. Mini lot = 10,000 units (0.1 standard). Micro lot = 1,000 units (0.01 standard). For EUR/USD, 1 standard lot = €100,000. With 1 pip = $10 on standard lot, a 50-pip move = $500 profit/loss. Position sizing must account for lot size and pip value. Source: Universal forex market convention.",
    tags: ["lot-size", "position-sizing", "forex-mechanics"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx8",
    category: "forex" as const,
    difficulty: "advanced" as const,
    question_text: "What is the difference between bid/ask spread in forex?",
    options: ["Bid is sell price; ask is buy price; spread is difference", "Bid is buy price; ask is sell price", "No functional difference"],
    correct_answer: 0,
    explanation: "Bid = price dealer will buy from you (you sell). Ask = price dealer will sell to you (you buy). Spread = Ask - Bid, represents transaction cost. EUR/USD bid 1.0850 / ask 1.0851 = 1 pip spread. Major pairs have 0.1-1 pip spreads; exotic pairs 5-20+ pips. Tighter spreads reduce trading costs significantly. Source: BIS forex market structure survey.",
    tags: ["bid-ask", "spread", "transaction-costs"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx9",
    category: "forex" as const,
    difficulty: "intermediate" as const,
    question_text: "Why do currency pairs move in opposite directions to each other?",
    options: ["If EUR/USD rises, USD/CHF typically falls (USD correlation)", "Random market movement", "Central bank intervention"],
    correct_answer: 0,
    explanation: "EUR/USD and USD/CHF have -0.95 correlation because USD is denominator in first, numerator in second. If USD weakens, EUR/USD rises while USD/CHF falls. Similarly, EUR/USD and GBP/USD are positively correlated (+0.85) as both measure USD strength. Understanding correlations prevents taking duplicate risk and identifies hedging opportunities. Source: Statistical analysis of major currency pairs.",
    tags: ["correlations", "currency-pairs", "risk-management"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx10",
    category: "forex" as const,
    difficulty: "beginner" as const,
    question_text: "What are the 'major' currency pairs?",
    options: ["EUR/USD, GBP/USD, USD/JPY, USD/CHF, AUD/USD, USD/CAD, NZD/USD", "Any pair with USD", "Most volatile pairs"],
    correct_answer: 0,
    explanation: "Major pairs include USD and one of the seven major currencies: EUR, GBP, JPY, CHF, AUD, CAD, NZD. These 7 pairs represent ~75% of forex volume, offer tightest spreads, highest liquidity, lowest slippage. Professional traders focus on majors for reliability and cost-efficiency. Cross pairs (no USD) are less liquid. Source: BIS Triennial Survey data.",
    tags: ["major-pairs", "currency-classification", "liquidity"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx11",
    category: "forex" as const,
    difficulty: "advanced" as const,
    question_text: "What is the Taylor Rule and how does it affect forex?",
    options: ["Formula predicting central bank interest rate decisions", "Technical analysis pattern", "Risk management method"],
    correct_answer: 0,
    explanation: "Taylor Rule, developed by economist John Taylor, estimates appropriate interest rate based on inflation gap and output gap. If actual rate below Taylor Rule rate, tightening likely (currency bullish). If above, easing likely (currency bearish). Professional traders compare Taylor Rule estimates to actual rates for positioning. Used by Fed governors in policy discussions. Source: Federal Reserve research papers.",
    tags: ["taylor-rule", "interest-rates", "monetary-policy"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx12",
    category: "forex" as const,
    difficulty: "intermediate" as const,
    question_text: "What is a forex swap or rollover?",
    options: ["Interest paid/earned for holding position overnight", "Currency exchange transaction", "Position size adjustment"],
    correct_answer: 0,
    explanation: "Forex positions held past 5 PM EST incur rollover (tom-next swap) - interest differential between two currencies. If you're long high-interest currency vs low-interest, you earn positive rollover. Reverse, you pay. On Wednesday, triple rollover for weekend. Carry traders profit from positive rollover over weeks/months. Source: Central bank interest rate policies and forex broker mechanisms.",
    tags: ["swap", "rollover", "interest-differential"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx13",
    category: "forex" as const,
    difficulty: "advanced" as const,
    question_text: "What is purchasing power parity (PPP) in forex?",
    options: ["Theory that exchange rates equalize purchasing power between countries", "Currency strength index", "Interest rate comparison"],
    correct_answer: 0,
    explanation: "PPP theory states exchange rates should adjust so identical goods cost the same in different countries. If Big Mac costs $5 in US and £4 in UK, PPP suggests GBP/USD = 1.25. In reality, short-term deviations are large, but currencies tend toward PPP over decades. The Economist's Big Mac Index illustrates PPP. Academic tool for long-term fair value. Source: 'The Economist' Big Mac Index and international economics textbooks.",
    tags: ["ppp", "fair-value", "economic-theory"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx14",
    category: "forex" as const,
    difficulty: "beginner" as const,
    question_text: "What does 'hawkish' vs 'dovish' central bank mean?",
    options: ["Hawkish = favor rate hikes (currency bullish); Dovish = favor rate cuts (bearish)", "Hawkish = aggressive policy; Dovish = passive policy", "No difference"],
    correct_answer: 0,
    explanation: "Hawkish central bank prioritizes fighting inflation via higher interest rates (currency strengthens as capital flows to higher yields). Dovish prioritizes growth/employment via lower rates (currency weakens). FOMC members are labeled hawkish/dovish. Their speeches move markets. Example: Jerome Powell hawkish comments in 2022 strengthened USD significantly. Source: Federal Reserve communications and forex market analysis.",
    tags: ["monetary-policy", "central-banks", "hawkish-dovish"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "fx15",
    category: "forex" as const,
    difficulty: "intermediate" as const,
    question_text: "What is intervention in forex markets?",
    options: ["Central bank buying/selling currency to influence exchange rate", "Trading halt", "Interest rate change"],
    correct_answer: 0,
    explanation: "Central banks intervene by buying/selling their currency to influence exchange rates. Bank of Japan frequently intervenes to weaken JPY (support exports). Swiss National Bank intervened heavily 2011-2015 to cap CHF strength. Interventions can cause sudden 100+ pip moves. Most central banks prefer verbal intervention ('jawboning') over actual intervention. Source: BIS reports on central bank intervention.",
    tags: ["intervention", "central-banks", "market-manipulation"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },

  // Additional Cryptocurrency Questions
  {
    question_code: "cr6",
    category: "cryptocurrency" as const,
    difficulty: "advanced" as const,
    question_text: "What is Bitcoin dominance and why does it matter?",
    options: ["Bitcoin market cap as percentage of total crypto market cap", "Bitcoin mining power", "Bitcoin trading volume"],
    correct_answer: 0,
    explanation: "Bitcoin dominance = Bitcoin market cap / Total crypto market cap × 100. Historically ranges 40-70%. High dominance (>60%) suggests 'risk-off' in crypto - money flowing to 'safest' crypto. Low dominance (<40%) suggests 'alt season' - capital rotating to altcoins. Professional crypto traders use dominance for altcoin market timing. Source: CoinMarketCap and crypto analytics platforms.",
    tags: ["bitcoin-dominance", "market-analysis", "altcoins"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr7",
    category: "cryptocurrency" as const,
    difficulty: "intermediate" as const,
    question_text: "What is a blockchain?",
    options: ["Distributed ledger recording all transactions across network", "Cryptocurrency wallet", "Mining software"],
    correct_answer: 0,
    explanation: "Blockchain is decentralized, immutable ledger where transactions are grouped in blocks, cryptographically linked in chronological chain. Each block contains hash of previous block, timestamp, transaction data. Once recorded, data cannot be altered retroactively. Maintained by distributed network, not central authority. Fundamental innovation enabling trustless value transfer. Source: Bitcoin whitepaper by Satoshi Nakamoto (2008).",
    tags: ["blockchain", "distributed-ledger", "technology"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr8",
    category: "cryptocurrency" as const,
    difficulty: "advanced" as const,
    question_text: "What is the difference between Proof of Work (PoW) and Proof of Stake (PoS)?",
    options: ["PoW uses mining/energy; PoS uses staking/validators", "No functional difference", "PoW for Bitcoin only; PoS for altcoins"],
    correct_answer: 0,
    explanation: "PoW (Bitcoin) requires miners to solve complex mathematical problems using computational power - energy intensive but highly secure. PoS (Ethereum post-Merge) requires validators to stake coins as collateral - 99.95% less energy but different security model. PoW: security from energy cost. PoS: security from economic penalty. Both secure but different tradeoffs. Source: Ethereum Foundation and Bitcoin Core documentation.",
    tags: ["consensus", "pow", "pos"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr9",
    category: "cryptocurrency" as const,
    difficulty: "beginner" as const,
    question_text: "What is a crypto wallet?",
    options: ["Software storing private keys to access cryptocurrency", "Physical wallet for crypto coins", "Exchange account"],
    correct_answer: 0,
    explanation: "Crypto wallet stores private keys (secret codes) proving ownership of cryptocurrency on blockchain. Hot wallets (online) offer convenience; cold wallets (offline hardware) offer security. Custodial wallets (exchange) - they control keys. Non-custodial - you control keys ('not your keys, not your coins'). Professional traders use cold storage for bulk holdings. Source: Blockchain.com and hardware wallet manufacturers.",
    tags: ["wallets", "private-keys", "security"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr10",
    category: "cryptocurrency" as const,
    difficulty: "intermediate" as const,
    question_text: "What is Ethereum gas and why does it fluctuate?",
    options: ["Transaction fee on Ethereum network; varies with network congestion", "Ethereum supply mechanism", "Mining reward"],
    correct_answer: 0,
    explanation: "Gas is computation fee for Ethereum transactions measured in gwei (0.000000001 ETH). Users bid gas fees for transaction priority. High network activity = high gas. Simple transfer: ~21,000 gas units. Complex smart contract: 200,000+ gas. Gas prices historically ranged from 5 gwei to 500+ gwei. Layer-2 solutions reduce gas costs. Source: Ethereum yellow paper and EIP-1559 documentation.",
    tags: ["gas-fees", "ethereum", "transaction-costs"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr11",
    category: "cryptocurrency" as const,
    difficulty: "advanced" as const,
    question_text: "What are the key on-chain metrics professional crypto traders monitor?",
    options: ["MVRV ratio, exchange reserves, active addresses, hash rate", "Price and volume only", "Social media sentiment"],
    correct_answer: 0,
    explanation: "MVRV (Market Value to Realized Value) - >3.5 suggests overvalued; <1 undervalued. Exchange reserves - decreasing suggests accumulation (bullish). Active addresses - increasing suggests adoption. Hash rate - increasing suggests network security. Professional traders use Glassnode, CryptoQuant for on-chain data. These metrics predicted major tops/bottoms historically. Source: On-chain analytics research and hedge fund methodologies.",
    tags: ["on-chain-metrics", "mvrv", "data-analysis"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr12",
    category: "cryptocurrency" as const,
    difficulty: "intermediate" as const,
    question_text: "What is a stablecoin and why is it important?",
    options: ["Cryptocurrency pegged to stable asset like USD (e.g., USDT, USDC)", "Low volatility altcoin", "Government-backed digital currency"],
    correct_answer: 0,
    explanation: "Stablecoins maintain 1:1 peg with fiat (usually USD). USDT (Tether), USDC (Circle), DAI (algorithmic) are largest. Used for: trading pairs, preserving value during volatility, earning yield, cross-border transfers. Enable crypto trading without returning to banking system. Some backed by reserves, others algorithmic. Critical infrastructure for crypto markets. Source: Stablecoin issuer transparency reports.",
    tags: ["stablecoins", "usdt", "usdc"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr13",
    category: "cryptocurrency" as const,
    difficulty: "beginner" as const,
    question_text: "What is an altcoin?",
    options: ["Any cryptocurrency other than Bitcoin", "Alternative investment coin", "New cryptocurrency"],
    correct_answer: 0,
    explanation: "Altcoin = 'alternative coin' to Bitcoin. Includes Ethereum, Ripple, Cardano, Solana, and 20,000+ others. Each has different use cases: Ethereum (smart contracts), Ripple (payments), Chainlink (oracles). Most altcoins are highly correlated with Bitcoin but with higher volatility (3-5x Bitcoin's moves). 'Alt season' = periods when altcoins outperform Bitcoin significantly. Source: CoinMarketCap cryptocurrency listings.",
    tags: ["altcoins", "terminology", "classification"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr14",
    category: "cryptocurrency" as const,
    difficulty: "advanced" as const,
    question_text: "What is the fear and greed index for crypto?",
    options: ["Sentiment indicator 0-100; extreme fear/greed signals reversals", "Volatility measure", "Market cap index"],
    correct_answer: 0,
    explanation: "Crypto Fear & Greed Index (0-100) combines volatility, momentum, social media, surveys, dominance, trends. <25 = extreme fear (often buying opportunity). >75 = extreme greed (often selling opportunity). Contrarian indicator - 'be greedy when others are fearful'. Updated daily. Professional traders use alongside technical analysis. Source: Alternative.me Fear & Greed Index methodology.",
    tags: ["sentiment", "fear-greed", "contrarian"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cr15",
    category: "cryptocurrency" as const,
    difficulty: "intermediate" as const,
    question_text: "What is the difference between a CEX and DEX?",
    options: ["CEX is centralized exchange; DEX is decentralized exchange", "No difference", "CEX for stocks; DEX for crypto"],
    correct_answer: 0,
    explanation: "CEX (Centralized Exchange) like Coinbase, Binance - company controls funds, KYC required, fast, high liquidity, custodial risk. DEX (Decentralized Exchange) like Uniswap, PancakeSwap - non-custodial, no KYC, you control funds, smart contracts execute trades, lower liquidity, smart contract risk. Professional traders use both: CEX for speed/liquidity, DEX for privacy/new tokens. Source: DeFi Pulse and exchange documentation.",
    tags: ["exchanges", "cex", "dex"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
];
    explanation: "Gold typically has negative correlation with stocks, rising during uncertainty as investors seek safety. During 2008 crisis and 2020 pandemic, gold surged while stocks crashed. Also benefits from low interest rates. Professional portfolios hold 5-10% gold for diversification. Source: World Gold Council research.",
    tags: ["safe-haven", "correlation", "portfolio-management"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm4",
    category: "commodities" as const,
    difficulty: "intermediate" as const,
    question_text: "What drives crude oil prices most significantly?",
    options: ["Supply/demand balance and geopolitics", "Weather patterns", "Gold prices"],
    correct_answer: 0,
    explanation: "Oil prices are driven by supply (OPEC production, US shale), demand (global economic growth, China/India consumption), and geopolitics (Middle East tensions). Traders watch EIA inventory reports (Wednesdays 10:30 AM EST) and OPEC meetings. Source: Energy Information Administration (EIA).",
    tags: ["crude-oil", "fundamentals", "market-drivers"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
  {
    question_code: "cm5",
    category: "commodities" as const,
    difficulty: "beginner" as const,
    question_text: "What are the two main categories of commodities?",
    options: ["Hard (metals/energy) and Soft (agricultural)", "Physical and Digital", "Domestic and International"],
    correct_answer: 0,
    explanation: "Hard commodities include metals (gold, silver, copper) and energy (oil, natural gas) that are mined or extracted. Soft commodities are agricultural products (wheat, corn, coffee, cotton) that are grown. Each category has different fundamental drivers. Source: Chicago Mercantile Exchange (CME) classification.",
    tags: ["commodity-types", "classification", "basics"],
    pattern_name: null,
    pattern_key: null,
    image_url: null,
    image_metadata: null,
  },
];
