export type PlanKey = 'free' | 'lite' | 'pro' | 'elite' | 'data_api';

export const PRICING_PLANS = [
  {
    key: 'free' as PlanKey,
    name: 'Free',
    tagline: 'Explore',
    price: { monthly: 0, annual: 0, monthlyLabel: '$0 / month', annualLabel: '$0 / year', savings: null },
    description: 'Discover live pattern signals across 20 instruments.',
    features: [
      'Live pattern scanner — 20 instruments (stocks)',
      '1h timeframe only',
      'Grade B & C patterns',
      '7-day outcome history',
      '3 pattern alerts per day',
      '1 trading plan',
      'Community access',
    ],
    cta: 'Start Free',
    ctaLink: '/auth?mode=signup',
    popular: false,
    highlighted: false,
    badge: null,
    isExternal: false,
  },
  {
    key: 'lite' as PlanKey,
    name: 'Lite',
    tagline: 'Getting Started',
    price: { monthly: 12, annual: 99, monthlyLabel: '$12 / month', annualLabel: '$99 / year', savings: 'Save 31%' },
    description: 'Full outcome history and richer alert capacity.',
    features: [
      'Everything in Free, plus:',
      'All asset classes (stocks, FX, ETFs)',
      '4h and daily timeframes',
      'Full 90-day outcome history',
      'Win rates by pattern & timeframe',
      '10 pattern alerts per day',
      '2 trading plans',
    ],
    cta: 'Start Lite',
    ctaLink: '/auth?mode=signup&plan=lite',
    popular: true,
    highlighted: false,
    badge: 'Most Popular',
    isExternal: false,
  },
  {
    key: 'pro' as PlanKey,
    name: 'Pro',
    tagline: 'Serious Trading',
    price: { monthly: 79, annual: 599, monthlyLabel: '$79 / month', annualLabel: '$599 / year', savings: 'Save 37%' },
    description: 'Complete outcome database, all timeframes, and AI Copilot.',
    features: [
      'Everything in Lite, plus:',
      'All timeframes — 1h, 4h, 1d, 1wk',
      'Grade A, B & C patterns',
      'Full outcome database (live count)',
      'Edge Atlas — win rates by pattern, timeframe & instrument',
      'Pattern Lab backtester',
      'Unlimited pattern alerts',
      'ChartingPath Copilot (AI trading assistant)',
      '10 trading plans',
      'Paper trading simulator',
    ],
    cta: 'Start 7-Day Free Trial',
    ctaLink: '/auth?mode=signup&plan=pro',
    popular: false,
    highlighted: true,
    badge: null,
    isExternal: false,
  },
  {
    key: 'elite' as PlanKey,
    name: 'Elite',
    tagline: 'Full Autonomy',
    price: { monthly: 149, annual: 999, monthlyLabel: '$149 / month', annualLabel: '$999 / year', savings: 'Save 44%' },
    description: 'Copilot ACS, API access, and priority everything.',
    features: [
      'Everything in Pro, plus:',
      'Copilot Autonomous Control System (ACS)',
      'Real-time priority pattern alerts',
      'Unlimited custom watchlists',
      'API access to outcome database',
      'Priority support',
      'Early access to new features',
    ],
    cta: 'Start 7-Day Free Trial',
    ctaLink: '/auth?mode=signup&plan=elite',
    popular: false,
    highlighted: false,
    badge: 'For Serious Traders',
    isExternal: false,
  },
  {
    key: 'data_api' as PlanKey,
    name: 'Data API',
    tagline: 'Institutional',
    price: { monthly: null, annual: null, monthlyLabel: 'Contact us', annualLabel: null, savings: null },
    description: "Institutional access to ChartingPath's outcome dataset.",
    features: [
      'REST API access to full outcome database',
      'Pattern outcomes by instrument × timeframe × regime',
      'Custom data exports',
      'Priority support & SLA',
    ],
    cta: 'Get in touch',
    ctaLink: 'mailto:yohei@chartingpath.com',
    popular: false,
    highlighted: false,
    badge: null,
    isExternal: true,
  },
];

export const PRICING_TEASER_PLANS = PRICING_PLANS.filter(p => p.key !== 'data_api');
