import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  ArrowLeft, 
  Download, 
  Copy, 
  Save, 
  Zap, 
  Crown, 
  Lock,
  Settings,
  Code2,
  History,
  TrendingUp
} from "lucide-react";
import { Link } from "react-router-dom";
import Navigation from "@/components/Navigation";
import { toast } from "sonner";

const AIBuilder = () => {
  const [strategy, setStrategy] = useState("");
  const [baseTemplate, setBaseTemplate] = useState("");
  const [timeframe, setTimeframe] = useState("15m");
  const [confirmTimeframe, setConfirmTimeframe] = useState("");
  const [mtfEnabled, setMtfEnabled] = useState(false);
  const [riskType, setRiskType] = useState("atr");
  const [atrLength, setAtrLength] = useState("14");
  const [atrSL, setAtrSL] = useState("1.5");
  const [atrTP, setAtrTP] = useState("3.0");
  const [volumeFilter, setVolumeFilter] = useState(false);
  const [trendEmaLength, setTrendEmaLength] = useState("50");
  const [alertsOnClose, setAlertsOnClose] = useState(true);
  const [multiCondition, setMultiCondition] = useState(false);
  const [generatedCode, setGeneratedCode] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Mock user tier - in real app this would come from auth context
  const userTier: "Starter" | "Pro" | "Pro+" | "Elite" = "Starter"; // Change to test different tiers
  const quotaUsed = 5;
  const quotaLimit = getTierLimit(userTier);

  function getTierLimit(tier: "Starter" | "Pro" | "Pro+" | "Elite"): number {
    switch (tier) {
      case "Pro": return 5;
      case "Pro+": return 20;
      case "Elite": return 100;
      default: return 0;
    }
  }

  function getTierPlatforms(tier: "Starter" | "Pro" | "Pro+" | "Elite"): string[] {
    switch (tier) {
      case "Pro": return ["pine"];
      case "Pro+": return ["pine", "mql4", "mql5"];
      case "Elite": return ["pine", "mql4", "mql5", "ctrader", "ninjatrader"];
      default: return [];
    }
  }

  const timeframes = ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w"];
  const templates = [
    "MACD",
    "RSI", 
    "Bollinger Bands",
    "Moving Average",
    "Breakout",
    "Candlestick",
    "VPT",
    "Custom"
  ];

  const handleGenerate = async () => {
    if (userTier === "Starter") {
      toast.error("AI Strategy Builder is available for Pro+ and above. Please upgrade your plan.");
      return;
    }

    if (quotaUsed >= quotaLimit) {
      toast.error(`Daily quota exceeded (${quotaLimit} generations). Quota resets at 00:00 JST.`);
      return;
    }

    if (!strategy.trim()) {
      toast.error("Please describe your strategy first.");
      return;
    }

    setIsGenerating(true);
    
    // Simulate API call delay
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    // Mock generated Pine Script code
    const mockCode = `// AI Generated Strategy: ${strategy.substring(0, 50)}...
// Generated by Market Leap Partners AI Builder
// Disclaimer: Educational purposes only. Not financial advice.

//@version=5
strategy("AI Strategy", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=10)

// Parameters
ema_fast = input.int(50, "Fast EMA")
ema_slow = input.int(200, "Slow EMA")
rsi_length = input.int(14, "RSI Length")
atr_length = input.int(${atrLength}, "ATR Length")
atr_sl_mult = input.float(${atrSL}, "ATR SL Multiplier")
atr_tp_mult = input.float(${atrTP}, "ATR TP Multiplier")

// Indicators
ema_fast_line = ta.ema(close, ema_fast)
ema_slow_line = ta.ema(close, ema_slow)
rsi = ta.rsi(close, rsi_length)
atr = ta.atr(atr_length)

// Entry Conditions
long_condition = ta.crossover(ema_fast_line, ema_slow_line) and rsi > 50
short_condition = ta.crossunder(ema_fast_line, ema_slow_line) and rsi < 50

// Strategy Logic
if long_condition
    if strategy.position_size < 0
        strategy.close("Short")
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", "Long", stop=close - atr * atr_sl_mult, limit=close + atr * atr_tp_mult)

if short_condition
    if strategy.position_size > 0
        strategy.close("Long")  
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", "Short", stop=close + atr * atr_sl_mult, limit=close - atr * atr_tp_mult)

// Alerts
${alertsOnClose ? 'alertcondition(long_condition, "Long Signal", "Long entry signal detected")' : ''}
${alertsOnClose ? 'alertcondition(short_condition, "Short Signal", "Short entry signal detected")' : ''}

// Plots
plot(ema_fast_line, "Fast EMA", color.blue)
plot(ema_slow_line, "Slow EMA", color.red)`;

    setGeneratedCode(mockCode);
    setIsGenerating(false);
    toast.success("Strategy generated successfully!");
  };

  const handleCopy = (code: string) => {
    navigator.clipboard.writeText(code);
    toast.success("Code copied to clipboard!");
  };

  const handleDownload = () => {
    // Mock download functionality
    toast.success("Strategy bundle downloaded!");
  };

  const handleSave = () => {
    if (!["Pro+", "Elite"].includes(userTier)) {
      toast.error("Save to Library is available for Pro+ and Elite tiers only.");
      return;
    }
    toast.success("Strategy saved to your library!");
  };

  if (userTier === "Starter") {
    return (
      <div className="min-h-screen bg-background">
        <Navigation />
        <div className="container mx-auto px-6 py-8 max-w-6xl">
          <div className="mb-6">
            <Link to="/" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
              <ArrowLeft className="h-4 w-4" />
              Back to Home
            </Link>
          </div>

          <Card className="text-center py-12">
            <CardHeader>
              <div className="flex justify-center mb-4">
                <Lock className="h-16 w-16 text-muted-foreground" />
              </div>
              <CardTitle className="text-3xl mb-4">AI Strategy Builder</CardTitle>
              <CardDescription className="text-lg">
                Transform your trading ideas into code with AI-powered generation
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground mb-6 max-w-2xl mx-auto">
                The AI Strategy Builder is available for Pro+ and Elite subscribers. 
                Upgrade to start generating Pine Script, MQL4, and MQL5 strategies from plain English descriptions.
              </p>
              <Link to="/pricing">
                <Button size="lg">
                  Upgrade to Pro+ 
                  <Zap className="ml-2 h-4 w-4" />
                </Button>
              </Link>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      <div className="container mx-auto px-6 py-8 max-w-7xl">
        {/* Header */}
        <div className="mb-6 flex items-center justify-between">
          <Link to="/" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Link>
          
          <Badge variant="outline" className="flex items-center gap-2">
            <Crown className="h-3 w-3" />
            {userTier} - {quotaUsed}/{quotaLimit} used today
          </Badge>
        </div>

        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent mb-4">
            AI Strategy Builder
          </h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Transform your trading ideas into professional-grade code. Describe your strategy in plain English 
            and get Pine Script, MQL4, and MQL5 implementations instantly.
          </p>
        </div>

        {/* Main Content Grid */}
        <div className="grid lg:grid-cols-3 gap-8">
          
          {/* Panel A: Strategy Description */}
          <div className="lg:col-span-1">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Settings className="h-5 w-5" />
                  Strategy Configuration
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                
                {/* Strategy Description */}
                <div>
                  <Label htmlFor="strategy">Describe Your Strategy</Label>
                  <Textarea
                    id="strategy"
                    value={strategy}
                    onChange={(e) => setStrategy(e.target.value)}
                    placeholder="Describe your strategy in plain English... e.g., '15m BTC strategy: EMA 50/200 trend filter, MACD cross for entries, RSI > 50, ATR SL 1.5×, TP 3×, alerts on close.'"
                    className="mt-2 min-h-[100px]"
                  />
                </div>

                {/* Base Template */}
                <div>
                  <Label>Base Template (Optional)</Label>
                  <Select value={baseTemplate} onValueChange={setBaseTemplate}>
                    <SelectTrigger className="mt-2">
                      <SelectValue placeholder="Choose a template" />
                    </SelectTrigger>
                    <SelectContent>
                      {templates.map(template => (
                        <SelectItem key={template} value={template.toLowerCase()}>
                          {template}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Timeframes */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label>Signal Timeframe</Label>
                    <Select value={timeframe} onValueChange={setTimeframe}>
                      <SelectTrigger className="mt-2">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {timeframes.map(tf => (
                          <SelectItem key={tf} value={tf}>{tf}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  
                  <div>
                    <Label>Confirm TF</Label>
                    <Select 
                      value={confirmTimeframe} 
                      onValueChange={setConfirmTimeframe}
                      disabled={!mtfEnabled}
                    >
                      <SelectTrigger className="mt-2">
                        <SelectValue placeholder="Select..." />
                      </SelectTrigger>
                      <SelectContent>
                        {timeframes.map(tf => (
                          <SelectItem key={tf} value={tf}>{tf}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                {/* MTF Toggle */}
                <div className="flex items-center space-x-2">
                  <Switch 
                    id="mtf" 
                    checked={mtfEnabled}
                    onCheckedChange={setMtfEnabled}
                  />
                  <Label htmlFor="mtf">Multi-Timeframe Confirmation</Label>
                </div>

                {/* Risk Controls */}
                <div>
                  <Label>Risk Controls</Label>
                  <Select value={riskType} onValueChange={setRiskType}>
                    <SelectTrigger className="mt-2">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="atr">ATR-based</SelectItem>
                      <SelectItem value="percentage">Percentage-based</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                {/* ATR Settings */}
                {riskType === "atr" && (
                  <div className="grid grid-cols-3 gap-2">
                    <div>
                      <Label className="text-xs">ATR Length</Label>
                      <Select value={atrLength} onValueChange={setAtrLength}>
                        <SelectTrigger className="mt-1">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="10">10</SelectItem>
                          <SelectItem value="14">14</SelectItem>
                          <SelectItem value="20">20</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div>
                      <Label className="text-xs">SL Mult</Label>
                      <Select value={atrSL} onValueChange={setAtrSL}>
                        <SelectTrigger className="mt-1">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="1.0">1.0×</SelectItem>
                          <SelectItem value="1.5">1.5×</SelectItem>
                          <SelectItem value="2.0">2.0×</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div>
                      <Label className="text-xs">TP Mult</Label>
                      <Select value={atrTP} onValueChange={setAtrTP}>
                        <SelectTrigger className="mt-1">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="2.0">2.0×</SelectItem>
                          <SelectItem value="3.0">3.0×</SelectItem>
                          <SelectItem value="4.0">4.0×</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                )}

                {/* Filters */}
                <div className="space-y-3">
                  <div className="flex items-center space-x-2">
                    <Switch 
                      id="volume" 
                      checked={volumeFilter}
                      onCheckedChange={setVolumeFilter}
                    />
                    <Label htmlFor="volume">Volume Filter</Label>
                  </div>
                  
                  <div>
                    <Label className="text-sm">Trend EMA Length</Label>
                    <Select value={trendEmaLength} onValueChange={setTrendEmaLength}>
                      <SelectTrigger className="mt-1">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="20">20</SelectItem>
                        <SelectItem value="50">50</SelectItem>
                        <SelectItem value="200">200</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                {/* Alerts */}
                <div className="space-y-3">
                  <div className="flex items-center space-x-2">
                    <Switch 
                      id="alerts" 
                      checked={alertsOnClose}
                      onCheckedChange={setAlertsOnClose}
                    />
                    <Label htmlFor="alerts">Alerts on Close</Label>
                  </div>
                  
                  {(userTier === "Pro+" || userTier === "Elite") && (
                    <div className="flex items-center space-x-2">
                      <Switch 
                        id="multicondition" 
                        checked={multiCondition}
                        onCheckedChange={setMultiCondition}
                      />
                      <Label htmlFor="multicondition">Multi-condition Alerts</Label>
                    </div>
                  )}
                </div>

                {/* Generate Button */}
                <Button 
                  onClick={handleGenerate} 
                  disabled={isGenerating || quotaUsed >= quotaLimit}
                  className="w-full"
                  size="lg"
                >
                  {isGenerating ? (
                    "Generating..."
                  ) : (
                    <>
                      Generate Strategy
                      <Code2 className="ml-2 h-4 w-4" />
                    </>
                  )}
                </Button>
                
                {quotaUsed >= quotaLimit && (
                  <p className="text-sm text-destructive text-center">
                    Daily quota exceeded. Resets at 00:00 JST.
                  </p>
                )}

              </CardContent>
            </Card>
          </div>

          {/* Panel B: Code Output */}
          <div className="lg:col-span-2">
            <Card className="h-fit">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2">
                    <Code2 className="h-5 w-5" />
                    Generated Code
                  </CardTitle>
                  
                  {generatedCode && (
                    <div className="flex gap-2">
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => handleCopy(generatedCode)}
                      >
                        <Copy className="h-4 w-4 mr-1" />
                        Copy
                      </Button>
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={handleDownload}
                      >
                        <Download className="h-4 w-4 mr-1" />
                        Download
                      </Button>
                      {(userTier === "Pro+" || userTier === "Elite") && (
                        <Button 
                          variant="outline" 
                          size="sm"
                          onClick={handleSave}
                        >
                          <Save className="h-4 w-4 mr-1" />
                          Save
                        </Button>
                      )}
                    </div>
                  )}
                </div>
              </CardHeader>
              
              <CardContent>
                {generatedCode ? (
                  <Tabs defaultValue="pine" className="w-full">
                    <TabsList className="grid w-full grid-cols-auto">
                      {getTierPlatforms(userTier).map(platform => (
                        <TabsTrigger key={platform} value={platform} className="capitalize">
                          {platform === "pine" ? "Pine v5" : platform.toUpperCase()}
                        </TabsTrigger>
                      ))}
                    </TabsList>
                    
                    {getTierPlatforms(userTier).map(platform => (
                      <TabsContent key={platform} value={platform}>
                        <div className="bg-muted rounded-lg p-4 font-mono text-sm overflow-x-auto max-h-96 overflow-y-auto">
                          <pre className="whitespace-pre-wrap">{generatedCode}</pre>
                        </div>
                        
                        <div className="mt-4 space-y-4">
                          <Card>
                            <CardHeader className="pb-3">
                              <CardTitle className="text-base">Installation Guide</CardTitle>
                            </CardHeader>
                            <CardContent className="pt-0">
                              <ol className="list-decimal list-inside space-y-2 text-sm text-muted-foreground">
                                <li>Copy the code above</li>
                                <li>Open TradingView Pine Editor</li>
                                <li>Paste and save as new strategy</li>
                                <li>Add to chart and configure parameters</li>
                                <li>Set up alerts if needed</li>
                              </ol>
                            </CardContent>
                          </Card>
                          
                          {(userTier === "Pro+" || userTier === "Elite") && (
                            <Card>
                              <CardHeader className="pb-3">
                                <CardTitle className="text-base flex items-center gap-2">
                                  <TrendingUp className="h-4 w-4" />
                                  Backtest Preview
                                </CardTitle>
                              </CardHeader>
                              <CardContent className="pt-0">
                                <div className="grid grid-cols-4 gap-4 text-center">
                                  <div>
                                    <p className="text-2xl font-bold text-primary">67%</p>
                                    <p className="text-xs text-muted-foreground">Win Rate</p>
                                  </div>
                                  <div>
                                    <p className="text-2xl font-bold text-primary">2.3</p>
                                    <p className="text-xs text-muted-foreground">P/L Ratio</p>
                                  </div>
                                  <div>
                                    <p className="text-2xl font-bold text-destructive">-8%</p>
                                    <p className="text-xs text-muted-foreground">Max DD</p>
                                  </div>
                                  <div>
                                    <p className="text-2xl font-bold text-primary">+24%</p>
                                    <p className="text-xs text-muted-foreground">Total Return</p>
                                  </div>
                                </div>
                                <p className="text-xs text-muted-foreground mt-3 text-center">
                                  *Simulated results based on historical data
                                </p>
                              </CardContent>
                            </Card>
                          )}
                        </div>
                      </TabsContent>
                    ))}
                  </Tabs>
                ) : (
                  <div className="text-center py-12 text-muted-foreground">
                    <Code2 className="h-12 w-12 mx-auto mb-4 opacity-50" />
                    <p>Your generated strategy will appear here</p>
                    <p className="text-sm mt-2">Describe your strategy and click Generate to get started</p>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>

        {/* History Panel (Pro+ & Elite only) */}
        {(userTier === "Pro+" || userTier === "Elite") && (
          <Card className="mt-8">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <History className="h-5 w-5" />
                Strategy History
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-center py-8 text-muted-foreground">
                <History className="h-12 w-12 mx-auto mb-4 opacity-50" />
                <p>Your generated strategies will appear here</p>
                <p className="text-sm mt-2">Generate your first strategy to start building your library</p>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Disclaimer */}
        <div className="mt-8 p-4 bg-destructive/10 border border-destructive/20 rounded-lg">
          <p className="text-sm text-destructive text-center font-medium">
            <strong>Educational Purposes Only:</strong> All generated strategies are for educational use only and do not constitute financial advice. 
            Trading involves substantial risk of loss. Past performance does not guarantee future results. 
            Always test strategies thoroughly before live trading.
          </p>
        </div>
      </div>
    </div>
  );
};

export default AIBuilder;