import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { 
  ArrowLeft, 
  Download, 
  Copy, 
  Save, 
  Zap, 
  Crown, 
  Lock,
  Settings,
  Code2,
  History,
  TrendingUp,
  Plus,
  X,
  Move,
  Target,
  BarChart3,
  Clock,
  Star,
  ChevronDown,
  ChevronRight,
  Info,
  HelpCircle
} from "lucide-react";
import { Link } from "react-router-dom";
import Navigation from "@/components/Navigation";
import { toast } from "sonner";

const AIBuilder = () => {
  const [strategy, setStrategy] = useState("");
  const [baseTemplate, setBaseTemplate] = useState("");
  const [timeframe, setTimeframe] = useState("15m");
  const [confirmTimeframe, setConfirmTimeframe] = useState("");
  const [mtfEnabled, setMtfEnabled] = useState(false);
  const [riskType, setRiskType] = useState("atr");
  const [atrLength, setAtrLength] = useState("14");
  const [atrSL, setAtrSL] = useState("1.5");
  const [atrTP, setAtrTP] = useState("3.0");
  const [volumeFilter, setVolumeFilter] = useState(false);
  const [trendEmaLength, setTrendEmaLength] = useState("50");
  const [alertsOnClose, setAlertsOnClose] = useState(true);
  const [multiCondition, setMultiCondition] = useState(false);
  const [generatedCode, setGeneratedCode] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Visual Condition Builder State
  const [builderMode, setBuilderMode] = useState<"natural" | "visual">("natural");
  const [starsAligned, setStarsAligned] = useState(true); // AND mode by default
  const [indicatorConditions, setIndicatorConditions] = useState<IndicatorCondition[]>([]);
  const [priceActionConditions, setPriceActionConditions] = useState<PriceActionCondition[]>([]);
  const [timeConditions, setTimeConditions] = useState<TimeCondition[]>([]);
  const [executionAction, setExecutionAction] = useState<"long" | "short">("long");
  const [useDirectionalMapping, setUseDirectionalMapping] = useState(false);
  const [trailingStop, setTrailingStop] = useState(false);
  const [trailingStopValue, setTrailingStopValue] = useState("1.5");
  const [earlyExit, setEarlyExit] = useState(false);

  // Types for condition builder
  interface IndicatorCondition {
    id: string;
    indicator: string;
    leftParams: Record<string, any>;
    operator: string;
    rightOperand: string;
    rightValue?: string;
    timeframe?: string;
  }

  interface PriceActionCondition {
    id: string;
    type: "close_vs_open" | "intraday_range" | "candle_pattern" | "sr_touch";
    params: Record<string, any>;
  }

  interface TimeCondition {
    id: string;
    type: "session_window" | "day_filter" | "bar_close";
    params: Record<string, any>;
  }
  
  // Mock user tier - in real app this would come from auth context
  const userTier: "Starter" | "Pro" | "Pro+" | "Elite" = "Elite"; // Set to Elite for full access
  const quotaUsed = 5;
  const quotaLimit = getTierLimit(userTier);

  function getTierLimit(tier: "Starter" | "Pro" | "Pro+" | "Elite"): number {
    switch (tier) {
      case "Pro": return 5;
      case "Pro+": return 20;
      case "Elite": return 100;
      default: return 0;
    }
  }

  function getTierPlatforms(tier: "Starter" | "Pro" | "Pro+" | "Elite"): string[] {
    switch (tier) {
      case "Pro": return ["pine"];
      case "Pro+": return ["pine", "mql4", "mql5"];
      case "Elite": return ["pine", "mql4", "mql5", "ctrader", "ninjatrader"];
      default: return [];
    }
  }

  const timeframes = ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w"];
  const templates = [
    "MACD",
    "RSI", 
    "Bollinger Bands",
    "Moving Average",
    "Breakout",
    "Candlestick",
    "VPT",
    "Custom"
  ];

  const handleGenerate = async () => {
    if (quotaUsed >= quotaLimit) {
      toast.error(`Daily quota exceeded (${quotaLimit} generations). Quota resets at 00:00 JST.`);
      return;
    }

    if (!strategy.trim()) {
      toast.error("Please describe your strategy first.");
      return;
    }

    setIsGenerating(true);
    
    // Simulate API call delay
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    // Mock generated Pine Script code
    const mockCode = `// AI Generated Strategy: ${strategy.substring(0, 50)}...
// Generated by Market Leap Partners AI Builder
// Disclaimer: Educational purposes only. Not financial advice.

//@version=5
strategy("AI Strategy", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=10)

// Parameters
ema_fast = input.int(50, "Fast EMA")
ema_slow = input.int(200, "Slow EMA")
rsi_length = input.int(14, "RSI Length")
atr_length = input.int(${atrLength}, "ATR Length")
atr_sl_mult = input.float(${atrSL}, "ATR SL Multiplier")
atr_tp_mult = input.float(${atrTP}, "ATR TP Multiplier")

// Indicators
ema_fast_line = ta.ema(close, ema_fast)
ema_slow_line = ta.ema(close, ema_slow)
rsi = ta.rsi(close, rsi_length)
atr = ta.atr(atr_length)

// Entry Conditions
long_condition = ta.crossover(ema_fast_line, ema_slow_line) and rsi > 50
short_condition = ta.crossunder(ema_fast_line, ema_slow_line) and rsi < 50

// Strategy Logic
if long_condition
    if strategy.position_size < 0
        strategy.close("Short")
    strategy.entry("Long", strategy.long)
    strategy.exit("Long Exit", "Long", stop=close - atr * atr_sl_mult, limit=close + atr * atr_tp_mult)

if short_condition
    if strategy.position_size > 0
        strategy.close("Long")  
    strategy.entry("Short", strategy.short)
    strategy.exit("Short Exit", "Short", stop=close + atr * atr_sl_mult, limit=close - atr * atr_tp_mult)

// Alerts
${alertsOnClose ? 'alertcondition(long_condition, "Long Signal", "Long entry signal detected")' : ''}
${alertsOnClose ? 'alertcondition(short_condition, "Short Signal", "Short entry signal detected")' : ''}

// Plots
plot(ema_fast_line, "Fast EMA", color.blue)
plot(ema_slow_line, "Slow EMA", color.red)`;

    setGeneratedCode(mockCode);
    setIsGenerating(false);
    toast.success("Strategy generated successfully!");
  };

  const handleCopy = (code: string) => {
    navigator.clipboard.writeText(code);
    toast.success("Code copied to clipboard!");
  };

  const handleDownload = () => {
    // Mock download functionality
    toast.success("Strategy bundle downloaded!");
  };

  const handleSave = () => {
    if (!["Pro+", "Elite"].includes(userTier)) {
      toast.error("Save to Library is available for Pro+ and Elite tiers only.");
      return;
    }
    toast.success("Strategy saved to your library!");
  };

  // Condition Builder Helper Functions
  const addIndicatorCondition = () => {
    const newCondition: IndicatorCondition = {
      id: Date.now().toString(),
      indicator: "EMA",
      leftParams: { period: 15, source: "close" },
      operator: "crosses_up",
      rightOperand: "indicator",
      rightValue: "50",
      timeframe: timeframe
    };
    setIndicatorConditions([...indicatorConditions, newCondition]);
  };

  const addPriceActionCondition = () => {
    const newCondition: PriceActionCondition = {
      id: Date.now().toString(),
      type: "close_vs_open",
      params: { direction: "up", threshold: 1.0, unit: "percent" }
    };
    setPriceActionConditions([...priceActionConditions, newCondition]);
  };

  const addTimeCondition = () => {
    const newCondition: TimeCondition = {
      id: Date.now().toString(),
      type: "session_window",
      params: { session: "custom", startTime: "09:30", endTime: "11:30", duration: 120 }
    };
    setTimeConditions([...timeConditions, newCondition]);
  };

  const removeIndicatorCondition = (id: string) => {
    setIndicatorConditions(indicatorConditions.filter(c => c.id !== id));
  };

  const removePriceActionCondition = (id: string) => {
    setPriceActionConditions(priceActionConditions.filter(c => c.id !== id));
  };

  const removeTimeCondition = (id: string) => {
    setTimeConditions(timeConditions.filter(c => c.id !== id));
  };

  const updateIndicatorCondition = (id: string, updates: Partial<IndicatorCondition>) => {
    setIndicatorConditions(indicatorConditions.map(c => 
      c.id === id ? { ...c, ...updates } : c
    ));
  };

  const indicators = [
    { value: "EMA", label: "EMA", params: ["period", "source"] },
    { value: "SMA", label: "SMA", params: ["period", "source"] },
    { value: "MACD", label: "MACD", params: ["fast", "slow", "signal", "line"] },
    { value: "RSI", label: "RSI", params: ["period", "source"] },
    { value: "Stochastic", label: "Stochastic", params: ["k_period", "d_period", "line"] },
    { value: "Bollinger", label: "Bollinger Bands", params: ["period", "deviation", "line"] },
    { value: "VWAP", label: "VWAP", params: [] },
    { value: "ATR", label: "ATR", params: ["period"] },
    { value: "VPT", label: "VPT", params: ["smoothing"] },
    { value: "ADX", label: "ADX", params: ["period", "line"] },
    { value: "Ichimoku", label: "Ichimoku", params: ["tenkan", "kijun", "senkou", "line"] },
    { value: "CCI", label: "CCI", params: ["period", "source"] }
  ];

  const operators = [
    { value: "crosses_up", label: "Crosses Up" },
    { value: "crosses_down", label: "Crosses Down" },
    { value: "above", label: "Above (>)" },
    { value: "below", label: "Below (<)" },
    { value: "equals", label: "Equals (=)" },
    { value: "inside_band", label: "Inside Band" },
    { value: "outside_band", label: "Outside Band" },
    { value: "slope_up", label: "Slope Up" },
    { value: "slope_down", label: "Slope Down" }
  ];

  // Since Elite has full access, skip the Starter gate check
  return (
    <TooltipProvider>
      <div className="min-h-screen bg-background">
        <Navigation />
        <div className="container mx-auto px-6 py-8 max-w-7xl">
          {/* Header */}
          <div className="mb-6 flex items-center justify-between">
            <Link to="/" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
              <ArrowLeft className="h-4 w-4" />
              Back to Home
            </Link>
            
            <Badge variant="outline" className="flex items-center gap-2">
              <Crown className="h-3 w-3" />
              {userTier} - {quotaUsed}/{quotaLimit} used today
            </Badge>
          </div>

          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent mb-4">
              AI Strategy Builder
            </h1>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Transform your trading ideas into professional-grade code. Describe your strategy in plain English 
              and get Pine Script, MQL4, and MQL5 implementations instantly.
            </p>
          </div>

          {/* Main Content Grid */}
          <div className="grid lg:grid-cols-3 gap-8">
            
            {/* Panel A: Strategy Configuration */}
            <div className="lg:col-span-1">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Settings className="h-5 w-5" />
                    Strategy Configuration
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-6">
                  
                  {/* Mode Selection */}
                  <Tabs value={builderMode} onValueChange={(value: "natural" | "visual") => setBuilderMode(value)} className="w-full">
                    <TabsList className="grid w-full grid-cols-2">
                      <TabsTrigger value="natural">Natural Language</TabsTrigger>
                      <TabsTrigger value="visual">Visual Builder</TabsTrigger>
                    </TabsList>
                    
                    {/* Natural Language Tab */}
                    <TabsContent value="natural" className="space-y-6 mt-6">
                      {/* Strategy Description */}
                      <div>
                        <div className="flex items-center gap-2 mb-2">
                          <Label htmlFor="strategy">Describe Your Strategy</Label>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                            </TooltipTrigger>
                            <TooltipContent className="max-w-xs">
                              <p>Describe your trading strategy in plain English. Include entry conditions, indicators, timeframes, and risk management. Example: "15m BTC strategy using EMA crossover with RSI confirmation and ATR-based stops."</p>
                            </TooltipContent>
                          </Tooltip>
                        </div>
                        <Textarea
                          id="strategy"
                          value={strategy}
                          onChange={(e) => setStrategy(e.target.value)}
                          placeholder="Describe your strategy in plain English... e.g., '15m BTC strategy: EMA 50/200 trend filter, MACD cross for entries, RSI > 50, ATR SL 1.5×, TP 3×, alerts on close.'"
                          className="mt-2 min-h-[100px]"
                        />
                      </div>

                      {/* Base Template */}
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <Label>Base Template (Optional)</Label>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                            </TooltipTrigger>
                            <TooltipContent className="max-w-xs">
                              <p>Choose a pre-built template to start with. Templates provide common indicator setups like MACD crossovers, RSI signals, or Bollinger Band strategies as a foundation for your custom strategy.</p>
                            </TooltipContent>
                          </Tooltip>
                        </div>
                        <Select value={baseTemplate} onValueChange={setBaseTemplate}>
                          <SelectTrigger className="mt-2">
                            <SelectValue placeholder="Choose a template" />
                          </SelectTrigger>
                          <SelectContent className="bg-background border z-50">
                            {templates.map(template => (
                              <SelectItem key={template} value={template.toLowerCase()}>
                                {template}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                    </TabsContent>

                    {/* Visual Builder Tab */}
                    <TabsContent value="visual" className="space-y-6 mt-6">
                      {/* Stars Aligned Mode */}
                      <div className="flex items-center justify-between p-4 bg-muted/50 rounded-lg">
                        <div className="flex items-center gap-2">
                          <Star className="h-4 w-4" />
                          <span className="font-medium">Stars Aligned Mode</span>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                            </TooltipTrigger>
                            <TooltipContent className="max-w-xs">
                              <p><strong>Stars Aligned (AND):</strong> ALL conditions must be true for a signal. <strong>OR Mode:</strong> ANY condition can trigger a signal. Use AND for more selective entries, OR for more frequent signals.</p>
                            </TooltipContent>
                          </Tooltip>
                        </div>
                        <Switch 
                          checked={starsAligned}
                          onCheckedChange={setStarsAligned}
                        />
                      </div>
                      <p className="text-xs text-muted-foreground -mt-4">
                        {starsAligned ? "ALL conditions must be true (AND)" : "ANY condition can trigger (OR)"}
                      </p>

                      {/* Indicator Conditions */}
                      <Collapsible defaultOpen>
                        <CollapsibleTrigger asChild>
                          <Button variant="ghost" className="w-full justify-between p-3 h-auto">
                            <div className="flex items-center gap-2">
                              <BarChart3 className="h-4 w-4" />
                              <span>Indicator Conditions</span>
                              <Badge variant="secondary">{indicatorConditions.length}</Badge>
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                                </TooltipTrigger>
                                <TooltipContent className="max-w-xs">
                                  <p>Add technical indicator conditions like EMA crossovers, RSI levels, MACD signals, Bollinger Band touches, etc. Each condition can have its own timeframe and parameters.</p>
                                </TooltipContent>
                              </Tooltip>
                            </div>
                            <ChevronDown className="h-4 w-4" />
                          </Button>
                        </CollapsibleTrigger>
                        <CollapsibleContent className="space-y-3 mt-3">
                          {indicatorConditions.map((condition) => (
                            <Card key={condition.id} className="p-3">
                              <div className="space-y-3">
                                <div className="flex items-center justify-between">
                                  <Select 
                                    value={condition.indicator} 
                                    onValueChange={(value) => updateIndicatorCondition(condition.id, { indicator: value })}
                                  >
                                    <SelectTrigger className="w-24">
                                      <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent className="bg-background border z-50">
                                      {indicators.map(ind => (
                                        <SelectItem key={ind.value} value={ind.value}>{ind.label}</SelectItem>
                                      ))}
                                    </SelectContent>
                                  </Select>
                                  <Button 
                                    variant="ghost" 
                                    size="sm"
                                    onClick={() => removeIndicatorCondition(condition.id)}
                                  >
                                    <X className="h-3 w-3" />
                                  </Button>
                                </div>
                                
                                <div className="grid grid-cols-3 gap-2 text-xs">
                                  {condition.indicator === "EMA" && (
                                    <Input 
                                      placeholder="Period" 
                                      value={condition.leftParams.period || ""} 
                                      onChange={(e) => updateIndicatorCondition(condition.id, { 
                                        leftParams: { ...condition.leftParams, period: e.target.value }
                                      })}
                                    />
                                  )}
                                  <Select 
                                    value={condition.operator} 
                                    onValueChange={(value) => updateIndicatorCondition(condition.id, { operator: value })}
                                  >
                                    <SelectTrigger>
                                      <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent className="bg-background border z-50">
                                      {operators.map(op => (
                                        <SelectItem key={op.value} value={op.value}>{op.label}</SelectItem>
                                      ))}
                                    </SelectContent>
                                  </Select>
                                  <Input 
                                    placeholder="Value" 
                                    value={condition.rightValue || ""} 
                                    onChange={(e) => updateIndicatorCondition(condition.id, { rightValue: e.target.value })}
                                  />
                                </div>
                                
                                <Select 
                                  value={condition.timeframe || timeframe} 
                                  onValueChange={(value) => updateIndicatorCondition(condition.id, { timeframe: value })}
                                >
                                  <SelectTrigger className="w-20">
                                    <SelectValue />
                                  </SelectTrigger>
                                  <SelectContent className="bg-background border z-50">
                                    {timeframes.map(tf => (
                                      <SelectItem key={tf} value={tf}>{tf}</SelectItem>
                                    ))}
                                  </SelectContent>
                                </Select>
                              </div>
                            </Card>
                          ))}
                          
                          <Button 
                            variant="outline" 
                            size="sm" 
                            onClick={addIndicatorCondition}
                            className="w-full"
                          >
                            <Plus className="h-3 w-3 mr-2" />
                            Add Indicator Condition
                          </Button>
                        </CollapsibleContent>
                      </Collapsible>

                      {/* Price Action Conditions */}
                      <Collapsible>
                        <CollapsibleTrigger asChild>
                          <Button variant="ghost" className="w-full justify-between p-3 h-auto">
                            <div className="flex items-center gap-2">
                              <Target className="h-4 w-4" />
                              <span>Price Action & Candles</span>
                              <Badge variant="secondary">{priceActionConditions.length}</Badge>
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                                </TooltipTrigger>
                                <TooltipContent className="max-w-xs">
                                  <p>Add price action conditions like close vs open direction, intraday range moves, candlestick patterns (hammer, doji, engulfing), and support/resistance level touches.</p>
                                </TooltipContent>
                              </Tooltip>
                            </div>
                            <ChevronDown className="h-4 w-4" />
                          </Button>
                        </CollapsibleTrigger>
                        <CollapsibleContent className="space-y-3 mt-3">
                          {priceActionConditions.map((condition) => (
                            <Card key={condition.id} className="p-3">
                              <div className="space-y-3">
                                <div className="flex items-center justify-between">
                                  <Select 
                                    value={condition.type}
                                    onValueChange={(value: "close_vs_open" | "intraday_range" | "candle_pattern" | "sr_touch") => 
                                      setPriceActionConditions(priceActionConditions.map(c => 
                                        c.id === condition.id ? { ...c, type: value } : c
                                      ))
                                    }
                                  >
                                    <SelectTrigger>
                                      <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent className="bg-background border z-50">
                                      <SelectItem value="close_vs_open">Close vs Open</SelectItem>
                                      <SelectItem value="intraday_range">Intraday Range</SelectItem>
                                      <SelectItem value="candle_pattern">Candle Pattern</SelectItem>
                                      <SelectItem value="sr_touch">S/R Touch</SelectItem>
                                    </SelectContent>
                                  </Select>
                                  <Button 
                                    variant="ghost" 
                                    size="sm"
                                    onClick={() => removePriceActionCondition(condition.id)}
                                  >
                                    <X className="h-3 w-3" />
                                  </Button>
                                </div>
                                
                                {condition.type === "close_vs_open" && (
                                  <div className="grid grid-cols-3 gap-2 text-xs">
                                    <Select defaultValue="up">
                                      <SelectTrigger>
                                        <SelectValue />
                                      </SelectTrigger>
                                      <SelectContent className="bg-background border z-50">
                                        <SelectItem value="up">Up</SelectItem>
                                        <SelectItem value="down">Down</SelectItem>
                                      </SelectContent>
                                    </Select>
                                    <Input placeholder="1.0" />
                                    <Select defaultValue="percent">
                                      <SelectTrigger>
                                        <SelectValue />
                                      </SelectTrigger>
                                      <SelectContent className="bg-background border z-50">
                                        <SelectItem value="percent">%</SelectItem>
                                        <SelectItem value="ticks">Ticks</SelectItem>
                                      </SelectContent>
                                    </Select>
                                  </div>
                                )}
                              </div>
                            </Card>
                          ))}
                          
                          <Button 
                            variant="outline" 
                            size="sm" 
                            onClick={addPriceActionCondition}
                            className="w-full"
                          >
                            <Plus className="h-3 w-3 mr-2" />
                            Add Price Action Condition
                          </Button>
                        </CollapsibleContent>
                      </Collapsible>

                      {/* Time/Session Conditions */}
                      <Collapsible>
                        <CollapsibleTrigger asChild>
                          <Button variant="ghost" className="w-full justify-between p-3 h-auto">
                            <div className="flex items-center gap-2">
                              <Clock className="h-4 w-4" />
                              <span>Time & Session</span>
                              <Badge variant="secondary">{timeConditions.length}</Badge>
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                                </TooltipTrigger>
                                <TooltipContent className="max-w-xs">
                                  <p>Add time-based filters like session windows (first 2 hours of London/NY), specific time ranges (09:30-11:30), day filters (weekdays only), or bar close requirements.</p>
                                </TooltipContent>
                              </Tooltip>
                            </div>
                            <ChevronDown className="h-4 w-4" />
                          </Button>
                        </CollapsibleTrigger>
                        <CollapsibleContent className="space-y-3 mt-3">
                          {timeConditions.map((condition) => (
                            <Card key={condition.id} className="p-3">
                              <div className="space-y-3">
                                <div className="flex items-center justify-between">
                                  <Select 
                                    value={condition.type}
                                    onValueChange={(value: "session_window" | "day_filter" | "bar_close") => 
                                      setTimeConditions(timeConditions.map(c => 
                                        c.id === condition.id ? { ...c, type: value } : c
                                      ))
                                    }
                                  >
                                    <SelectTrigger>
                                      <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent className="bg-background border z-50">
                                      <SelectItem value="session_window">Session Window</SelectItem>
                                      <SelectItem value="day_filter">Day Filter</SelectItem>
                                      <SelectItem value="bar_close">Bar Close Only</SelectItem>
                                    </SelectContent>
                                  </Select>
                                  <Button 
                                    variant="ghost" 
                                    size="sm"
                                    onClick={() => removeTimeCondition(condition.id)}
                                  >
                                    <X className="h-3 w-3" />
                                  </Button>
                                </div>
                                
                                {condition.type === "session_window" && (
                                  <div className="grid grid-cols-2 gap-2 text-xs">
                                    <Input placeholder="09:30" />
                                    <Input placeholder="11:30" />
                                  </div>
                                )}
                              </div>
                            </Card>
                          ))}
                          
                          <Button 
                            variant="outline" 
                            size="sm" 
                            onClick={addTimeCondition}
                            className="w-full"
                          >
                            <Plus className="h-3 w-3 mr-2" />
                            Add Time Condition
                          </Button>
                        </CollapsibleContent>
                      </Collapsible>

                      {/* Execution Panel */}
                      <Card className="p-4 bg-muted/30">
                        <h4 className="font-medium mb-3 flex items-center gap-2">
                          <Target className="h-4 w-4" />
                          Execution & Risk
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                            </TooltipTrigger>
                            <TooltipContent className="max-w-xs">
                              <p>Configure how trades are executed when conditions are met. Set direction (long/short), enable directional mapping, add trailing stops, and configure early exit rules.</p>
                            </TooltipContent>
                          </Tooltip>
                        </h4>
                        <div className="space-y-4">
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <Label className="text-sm">Action on Trigger</Label>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                              </TooltipTrigger>
                              <TooltipContent className="max-w-xs">
                                <p>Choose whether signals trigger long or short entries. Can be overridden by directional mapping if enabled.</p>
                              </TooltipContent>
                            </Tooltip>
                          </div>
                          <Select value={executionAction} onValueChange={(value: "long" | "short") => setExecutionAction(value)}>
                            <SelectTrigger className="mt-1">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent className="bg-background border z-50">
                              <SelectItem value="long">Enter Long</SelectItem>
                              <SelectItem value="short">Enter Short</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                          
                          <div className="flex items-center space-x-2">
                            <Switch 
                              checked={useDirectionalMapping}
                              onCheckedChange={setUseDirectionalMapping}
                            />
                            <Label className="text-sm">Use Directional Mapping</Label>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                              </TooltipTrigger>
                              <TooltipContent className="max-w-xs">
                                <p>Automatically determine trade direction based on signal type (e.g., EMA cross up = Long, RSI below 30 = Short). Overrides the fixed action setting above.</p>
                              </TooltipContent>
                            </Tooltip>
                          </div>
                          
                          <div className="flex items-center space-x-2">
                            <Switch 
                              checked={trailingStop}
                              onCheckedChange={setTrailingStop}
                            />
                            <Label className="text-sm">Trailing Stop</Label>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                              </TooltipTrigger>
                              <TooltipContent className="max-w-xs">
                                <p>Enable trailing stop-loss that moves in your favor as price moves favorably. Specify the trail distance in ATR multiples or percentage.</p>
                              </TooltipContent>
                            </Tooltip>
                          </div>
                          
                          {trailingStop && (
                            <Input 
                              placeholder="1.5"
                              value={trailingStopValue}
                              onChange={(e) => setTrailingStopValue(e.target.value)}
                            />
                          )}
                          
                          <div className="flex items-center space-x-2">
                            <Switch 
                              checked={earlyExit}
                              onCheckedChange={setEarlyExit}
                            />
                            <Label className="text-sm">Early Exit on Opposite Signal</Label>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                              </TooltipTrigger>
                              <TooltipContent className="max-w-xs">
                                <p>Close the current position early if an opposite signal appears, even before hitting stop-loss or take-profit levels.</p>
                              </TooltipContent>
                            </Tooltip>
                          </div>
                        </div>
                      </Card>
                    </TabsContent>
                  </Tabs>

                  {/* Common Settings (shown for both modes) */}
                  <div className="space-y-6 border-t pt-6">
                    {/* Timeframes */}
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <Label>Signal Timeframe</Label>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                            </TooltipTrigger>
                            <TooltipContent className="max-w-xs">
                              <p>The main timeframe where signals are generated. This is the chart timeframe where your strategy will look for entry conditions.</p>
                            </TooltipContent>
                          </Tooltip>
                        </div>
                        <Select value={timeframe} onValueChange={setTimeframe}>
                          <SelectTrigger className="mt-2">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent className="bg-background border z-50">
                            {timeframes.map(tf => (
                              <SelectItem key={tf} value={tf}>{tf}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                      
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <Label>Confirm TF</Label>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                            </TooltipTrigger>
                            <TooltipContent className="max-w-xs">
                              <p>Optional higher timeframe for trend confirmation. Signals from the main timeframe will only trigger if the trend on this timeframe aligns.</p>
                            </TooltipContent>
                          </Tooltip>
                        </div>
                        <Select 
                          value={confirmTimeframe} 
                          onValueChange={setConfirmTimeframe}
                          disabled={!mtfEnabled}
                        >
                          <SelectTrigger className="mt-2">
                            <SelectValue placeholder="Select..." />
                          </SelectTrigger>
                          <SelectContent className="bg-background border z-50">
                            {timeframes.map(tf => (
                              <SelectItem key={tf} value={tf}>{tf}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                    </div>

                    {/* MTF Toggle */}
                    <div className="flex items-center space-x-2">
                      <Switch 
                        id="mtf" 
                        checked={mtfEnabled}
                        onCheckedChange={setMtfEnabled}
                      />
                      <Label htmlFor="mtf">Multi-Timeframe Confirmation</Label>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                        </TooltipTrigger>
                        <TooltipContent className="max-w-xs">
                          <p>Enable higher timeframe trend confirmation to improve signal quality. Only take signals when the higher timeframe trend aligns with your entry direction.</p>
                        </TooltipContent>
                      </Tooltip>
                    </div>

                    {/* Risk Controls */}
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <Label>Risk Controls</Label>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                          </TooltipTrigger>
                          <TooltipContent className="max-w-xs">
                            <p><strong>ATR-based:</strong> Uses Average True Range for dynamic stops based on market volatility. <strong>Percentage-based:</strong> Uses fixed percentage stops from entry price.</p>
                          </TooltipContent>
                        </Tooltip>
                      </div>
                      <Select value={riskType} onValueChange={setRiskType}>
                        <SelectTrigger className="mt-2">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent className="bg-background border z-50">
                          <SelectItem value="atr">ATR-based</SelectItem>
                          <SelectItem value="percentage">Percentage-based</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>

                    {/* ATR Settings */}
                    {riskType === "atr" && (
                      <div className="grid grid-cols-3 gap-2">
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <Label className="text-xs">ATR Length</Label>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <HelpCircle className="h-3 w-3 text-muted-foreground hover:text-foreground cursor-help" />
                              </TooltipTrigger>
                              <TooltipContent className="max-w-xs">
                                <p>Number of bars to calculate Average True Range. Higher values = smoother, less reactive. Lower values = more responsive to recent volatility changes.</p>
                              </TooltipContent>
                            </Tooltip>
                          </div>
                          <Select value={atrLength} onValueChange={setAtrLength}>
                            <SelectTrigger className="mt-1">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent className="bg-background border z-50">
                              <SelectItem value="10">10</SelectItem>
                              <SelectItem value="14">14</SelectItem>
                              <SelectItem value="20">20</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <Label className="text-xs">SL Mult</Label>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <HelpCircle className="h-3 w-3 text-muted-foreground hover:text-foreground cursor-help" />
                              </TooltipTrigger>
                              <TooltipContent className="max-w-xs">
                                <p>Stop-loss multiplier. Stop = Entry ± (ATR × Multiplier). Higher values = wider stops, lower risk of being stopped out but larger losses when wrong.</p>
                              </TooltipContent>
                            </Tooltip>
                          </div>
                          <Select value={atrSL} onValueChange={setAtrSL}>
                            <SelectTrigger className="mt-1">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent className="bg-background border z-50">
                              <SelectItem value="1.0">1.0×</SelectItem>
                              <SelectItem value="1.5">1.5×</SelectItem>
                              <SelectItem value="2.0">2.0×</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <Label className="text-xs">TP Mult</Label>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <HelpCircle className="h-3 w-3 text-muted-foreground hover:text-foreground cursor-help" />
                              </TooltipTrigger>
                              <TooltipContent className="max-w-xs">
                                <p>Take-profit multiplier. Target = Entry ± (ATR × Multiplier). Higher values = larger profit targets but lower hit rate. Aim for TP/SL ratio ≥ 2:1.</p>
                              </TooltipContent>
                            </Tooltip>
                          </div>
                          <Select value={atrTP} onValueChange={setAtrTP}>
                            <SelectTrigger className="mt-1">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent className="bg-background border z-50">
                              <SelectItem value="2.0">2.0×</SelectItem>
                              <SelectItem value="3.0">3.0×</SelectItem>
                              <SelectItem value="4.0">4.0×</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                      </div>
                    )}

                    {/* Filters */}
                    <div className="space-y-3">
                      <div className="flex items-center space-x-2">
                        <Switch 
                          id="volume" 
                          checked={volumeFilter}
                          onCheckedChange={setVolumeFilter}
                        />
                        <Label htmlFor="volume">Volume Filter</Label>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                          </TooltipTrigger>
                          <TooltipContent className="max-w-xs">
                            <p>Only take signals when current volume is above the 20-period moving average. Helps filter out low-conviction moves in thin volume.</p>
                          </TooltipContent>
                        </Tooltip>
                      </div>
                      
                      <div>
                        <div className="flex items-center justify-between mb-1">
                          <Label className="text-sm">Trend EMA Length</Label>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                            </TooltipTrigger>
                            <TooltipContent className="max-w-xs">
                              <p>EMA period for trend filter. Only take long signals when price is above this EMA, short signals when below. Common values: 20 (short-term), 50 (medium), 200 (long-term).</p>
                            </TooltipContent>
                          </Tooltip>
                        </div>
                        <Select value={trendEmaLength} onValueChange={setTrendEmaLength}>
                          <SelectTrigger className="mt-1">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent className="bg-background border z-50">
                            <SelectItem value="20">20</SelectItem>
                            <SelectItem value="50">50</SelectItem>
                            <SelectItem value="200">200</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                    </div>

                    {/* Alerts */}
                    <div className="space-y-3">
                      <div className="flex items-center space-x-2">
                        <Switch 
                          id="alerts" 
                          checked={alertsOnClose}
                          onCheckedChange={setAlertsOnClose}
                        />
                        <Label htmlFor="alerts">Alerts on Close</Label>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                          </TooltipTrigger>
                          <TooltipContent className="max-w-xs">
                            <p>Generate alerts only when the bar closes with signal conditions met. Reduces false signals from intra-bar noise but may delay notifications.</p>
                          </TooltipContent>
                        </Tooltip>
                      </div>
                      
                      {userTier === "Elite" && (
                        <div className="flex items-center space-x-2">
                          <Switch 
                            id="multicondition" 
                            checked={multiCondition}
                            onCheckedChange={setMultiCondition}
                          />
                          <Label htmlFor="multicondition">Multi-condition Alerts</Label>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <HelpCircle className="h-4 w-4 text-muted-foreground hover:text-foreground cursor-help" />
                            </TooltipTrigger>
                            <TooltipContent className="max-w-xs">
                              <p>Elite feature: Create complex alert conditions that include multiple indicators, price action, and time filters. Supports email, Telegram, and Discord notifications.</p>
                            </TooltipContent>
                          </Tooltip>
                        </div>
                      )}
                    </div>

                    {/* Generate Button */}
                    <Button 
                      onClick={handleGenerate} 
                      disabled={isGenerating || quotaUsed >= quotaLimit || (builderMode === "natural" && !strategy.trim()) || (builderMode === "visual" && indicatorConditions.length === 0 && priceActionConditions.length === 0)}
                      className="w-full"
                      size="lg"
                    >
                      {isGenerating ? (
                        "Generating..."
                      ) : (
                        <>
                          Generate Strategy
                          <Code2 className="ml-2 h-4 w-4" />
                        </>
                      )}
                    </Button>
                    
                    {quotaUsed >= quotaLimit && (
                      <p className="text-sm text-destructive text-center">
                        Daily quota exceeded. Resets at 00:00 JST.
                      </p>
                    )}
                  </div>

                </CardContent>
              </Card>
            </div>

          {/* Panel B: Code Output */}
          <div className="lg:col-span-2">
            <Card className="h-fit">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2">
                    <Code2 className="h-5 w-5" />
                    Generated Code
                  </CardTitle>
                  
                  {generatedCode && (
                    <div className="flex gap-2">
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => handleCopy(generatedCode)}
                      >
                        <Copy className="h-4 w-4 mr-1" />
                        Copy
                      </Button>
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={handleDownload}
                      >
                        <Download className="h-4 w-4 mr-1" />
                        Download
                      </Button>
                      {userTier === "Elite" && (
                        <Button 
                          variant="outline" 
                          size="sm"
                          onClick={handleSave}
                        >
                          <Save className="h-4 w-4 mr-1" />
                          Save
                        </Button>
                      )}
                    </div>
                  )}
                </div>
              </CardHeader>
              
              <CardContent>
                {generatedCode ? (
                  <Tabs defaultValue="pine" className="w-full">
                    <TabsList className="grid w-full grid-cols-auto">
                      {getTierPlatforms(userTier).map(platform => (
                        <TabsTrigger key={platform} value={platform} className="capitalize">
                          {platform === "pine" ? "Pine v5" : platform.toUpperCase()}
                        </TabsTrigger>
                      ))}
                    </TabsList>
                    
                    {getTierPlatforms(userTier).map(platform => (
                      <TabsContent key={platform} value={platform}>
                        <div className="bg-muted rounded-lg p-4 font-mono text-sm overflow-x-auto max-h-96 overflow-y-auto">
                          <pre className="whitespace-pre-wrap">{generatedCode}</pre>
                        </div>
                        
                        <div className="mt-4 space-y-4">
                          <Card>
                            <CardHeader className="pb-3">
                              <CardTitle className="text-base">Installation Guide</CardTitle>
                            </CardHeader>
                            <CardContent className="pt-0">
                              <ol className="list-decimal list-inside space-y-2 text-sm text-muted-foreground">
                                <li>Copy the code above</li>
                                <li>Open TradingView Pine Editor</li>
                                <li>Paste and save as new strategy</li>
                                <li>Add to chart and configure parameters</li>
                                <li>Set up alerts if needed</li>
                              </ol>
                            </CardContent>
                          </Card>
                          
                          {userTier === "Elite" && (
                            <Card>
                              <CardHeader className="pb-3">
                                <CardTitle className="text-base flex items-center gap-2">
                                  <TrendingUp className="h-4 w-4" />
                                  Backtest Preview
                                </CardTitle>
                              </CardHeader>
                              <CardContent className="pt-0">
                                <div className="grid grid-cols-4 gap-4 text-center">
                                  <div>
                                    <p className="text-2xl font-bold text-primary">67%</p>
                                    <p className="text-xs text-muted-foreground">Win Rate</p>
                                  </div>
                                  <div>
                                    <p className="text-2xl font-bold text-primary">2.3</p>
                                    <p className="text-xs text-muted-foreground">P/L Ratio</p>
                                  </div>
                                  <div>
                                    <p className="text-2xl font-bold text-destructive">-8%</p>
                                    <p className="text-xs text-muted-foreground">Max DD</p>
                                  </div>
                                  <div>
                                    <p className="text-2xl font-bold text-primary">+24%</p>
                                    <p className="text-xs text-muted-foreground">Total Return</p>
                                  </div>
                                </div>
                                <p className="text-xs text-muted-foreground mt-3 text-center">
                                  *Simulated results based on historical data
                                </p>
                              </CardContent>
                            </Card>
                          )}
                        </div>
                      </TabsContent>
                    ))}
                  </Tabs>
                ) : (
                  <div className="text-center py-12 text-muted-foreground">
                    <Code2 className="h-12 w-12 mx-auto mb-4 opacity-50" />
                    <p>Your generated strategy will appear here</p>
                    <p className="text-sm mt-2">Describe your strategy and click Generate to get started</p>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>

        {/* History Panel (Elite only in this demo) */}
        {userTier === "Elite" && (
          <Card className="mt-8">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <History className="h-5 w-5" />
                Strategy History
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-center py-8 text-muted-foreground">
                <History className="h-12 w-12 mx-auto mb-4 opacity-50" />
                <p>Your generated strategies will appear here</p>
                <p className="text-sm mt-2">Generate your first strategy to start building your library</p>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Disclaimer */}
        <div className="mt-8 p-4 bg-destructive/10 border border-destructive/20 rounded-lg">
          <p className="text-sm text-destructive text-center font-medium">
            <strong>Educational Purposes Only:</strong> All generated strategies are for educational use only and do not constitute financial advice. 
            Trading involves substantial risk of loss. Past performance does not guarantee future results. 
            Always test strategies thoroughly before live trading.
          </p>
        </div>
      </div>
    </div>
    </TooltipProvider>
  );
};

export default AIBuilder;