export interface Strategy {
  id: number;
  name: string;
  category: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced" | "Expert";
  indicators: string[];
  timeframes: string[];
  description: string;
  entry: string;
  exit: string;
  riskReward: string;
  pack: string;
  hidden?: boolean;
  internalJsonSchema?: {
    name: string;
    inputs: Record<string, any>;
    indicators: string[];
    signals: string[];
    filters: Record<string, any>;
    exits: Record<string, any>;
    timeframe: { signal: string; confirm?: string };
    alerts: Record<string, any>;
  };
}

export const STRATEGY_PACKS = {
  "MACD Strategy Pack": "A",
  "Bollinger Bands Strategy Pack": "B", 
  "RSI Strategy Pack": "C",
  "Moving Averages & Trend Pack": "D",
  "Stochastic & Oscillators Pack": "E",
  "Volume & Volume-Price Pack": "F",
  "Levels & Patterns Pack": "G",
  "Market Structure & Profile Pack": "H",
  "Advanced Confirmation Pack": "I",
  "Trading Styles Pack": "J"
} as const;

export const tradingStrategies: Strategy[] = [
  // MACD Strategy Pack (A)
  {
    id: 1,
    name: "MACD Golden Cross Momentum",
    category: "MACD",
    difficulty: "Beginner",
    indicators: ["MACD", "Signal Line", "Volume"],
    timeframes: ["1H", "4H", "1D"],
    description: "Enter long when MACD crosses above signal line with increasing volume",
    entry: "MACD line crosses above signal line + volume spike",
    exit: "MACD crosses below signal line or 2% stop loss",
    riskReward: "1:2",
    pack: "MACD Strategy Pack",
    internalJsonSchema: {
      name: "MACD Golden Cross Momentum",
      inputs: { "macdFast": 12, "macdSlow": 26, "signal": 9, "riskPercent": 1.0 },
      indicators: ["MACD", "Signal Line", "Volume"],
      signals: ["crossUp"],
      filters: { "volumeSpike": true },
      exits: { "oppositeSignal": true, "stopLoss": 2.0 },
      timeframe: { "signal": "1H" },
      alerts: { "onCloseOnly": true, "message": "MACD Golden Cross signal triggered" }
    }
  },
  {
    id: 2,
    name: "MACD Divergence Reversal",
    category: "MACD",
    difficulty: "Advanced",
    indicators: ["MACD", "Price Action", "RSI"],
    timeframes: ["4H", "1D"],
    description: "Identify divergence between price and MACD for reversal signals",
    entry: "Bearish divergence + MACD histogram declining",
    exit: "Target previous support/resistance levels",
    riskReward: "1:3",
    pack: "MACD Strategy Pack"
  },
  {
    id: 3,
    name: "MACD Zero Line Bounce",
    category: "MACD",
    difficulty: "Intermediate",
    indicators: ["MACD", "EMA 20", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Trade bounces off MACD zero line in trending markets",
    entry: "MACD touches zero line and bounces + price above EMA 20",
    exit: "MACD histogram peaks or price breaks EMA 20",
    riskReward: "1:2.5",
    pack: "MACD Strategy Pack"
  },
  {
    id: 4,
    name: "MACD Histogram Strategy",
    category: "MACD",
    difficulty: "Expert",
    indicators: ["MACD Histogram", "Volume Profile", "ATR"],
    timeframes: ["15M", "1H"],
    description: "Use MACD histogram for precise entry timing",
    entry: "Histogram turning positive + volume above average",
    exit: "Histogram peaks or ATR-based stop loss",
    riskReward: "1:2",
    pack: "MACD Strategy Pack"
  },
  {
    id: 5,
    name: "MACD Triple Screen",
    category: "MACD",
    difficulty: "Expert",
    indicators: ["MACD", "Weekly Trend", "Daily MACD", "Hourly Entry"],
    timeframes: ["1W", "1D", "1H"],
    description: "Elder's triple screen method using MACD across timeframes",
    entry: "Weekly uptrend + daily MACD buy + hourly pullback",
    exit: "Daily MACD turns negative",
    riskReward: "1:4",
    pack: "MACD Strategy Pack"
  },

  // Bollinger Bands Strategy Pack (B)
  {
    id: 6,
    name: "Bollinger Band Squeeze",
    category: "Bollinger Bands",
    difficulty: "Intermediate",
    indicators: ["Bollinger Bands", "Volume", "ATR"],
    timeframes: ["1H", "4H"],
    description: "Trade breakouts after periods of low volatility",
    entry: "Bands squeeze + volume expansion on breakout",
    exit: "Price reaches opposite band or volume dies",
    riskReward: "1:3",
    pack: "Bollinger Bands Strategy Pack"
  },
  {
    id: 7,
    name: "Bollinger Band Mean Reversion",
    category: "Bollinger Bands",
    difficulty: "Beginner",
    indicators: ["Bollinger Bands", "RSI", "Stochastic"],
    timeframes: ["15M", "1H"],
    description: "Buy oversold at lower band, sell overbought at upper band",
    entry: "Price touches lower band + RSI < 30",
    exit: "Price reaches middle band or upper band",
    riskReward: "1:2",
    pack: "Bollinger Bands Strategy Pack"
  },
  {
    id: 8,
    name: "Bollinger Band Walk Strategy",
    category: "Bollinger Bands",
    difficulty: "Advanced",
    indicators: ["Bollinger Bands", "Volume", "Momentum"],
    timeframes: ["4H", "1D"],
    description: "Ride strong trends walking along the bands",
    entry: "Price walks along upper band with volume",
    exit: "Price falls below middle band",
    riskReward: "1:5",
    pack: "Bollinger Bands Strategy Pack"
  },
  {
    id: 9,
    name: "Double Bollinger Band System",
    category: "Bollinger Bands",
    difficulty: "Expert",
    indicators: ["BB (20,2)", "BB (20,1)", "Volume", "MACD"],
    timeframes: ["1H", "4H"],
    description: "Use two sets of Bollinger Bands for refined entries",
    entry: "Price between outer and inner bands + MACD confirmation",
    exit: "Price reaches target zone or stops triggered",
    riskReward: "1:2.5",
    pack: "Bollinger Bands Strategy Pack"
  },
  {
    id: 10,
    name: "Bollinger Band Reversal Pattern",
    category: "Bollinger Bands",
    difficulty: "Intermediate",
    indicators: ["Bollinger Bands", "Candlestick Patterns", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Combine BB touches with reversal candlestick patterns",
    entry: "Hammer at lower band or shooting star at upper band",
    exit: "Price reaches middle band or pattern fails",
    riskReward: "1:2.5",
    pack: "Bollinger Bands Strategy Pack"
  },

  // RSI Strategy Pack (C)
  {
    id: 11,
    name: "RSI Divergence Strategy",
    category: "RSI",
    difficulty: "Advanced",
    indicators: ["RSI", "Price Action", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Trade divergences between RSI and price action",
    entry: "Bullish divergence: lower lows in price, higher lows in RSI",
    exit: "RSI reaches overbought or price breaks key resistance",
    riskReward: "1:3",
    pack: "RSI Strategy Pack"
  },
  {
    id: 12,
    name: "RSI 50 Line Strategy",
    category: "RSI",
    difficulty: "Beginner",
    indicators: ["RSI", "EMA 21", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Use RSI 50 line as trend filter for entries",
    entry: "RSI above 50 + price above EMA 21 + pullback",
    exit: "RSI below 50 or EMA 21 break",
    riskReward: "1:2",
    pack: "RSI Strategy Pack"
  },
  {
    id: 13,
    name: "RSI Overbought/Oversold Scalp",
    category: "RSI",
    difficulty: "Intermediate",
    indicators: ["RSI", "Stochastic", "Volume"],
    timeframes: ["5M", "15M"],
    description: "Quick scalps using extreme RSI levels",
    entry: "RSI > 80 or < 20 + stochastic confirmation",
    exit: "RSI returns to 50 line or time-based exit",
    riskReward: "1:1.5",
    pack: "RSI Strategy Pack"
  },
  {
    id: 14,
    name: "RSI Failure Swing",
    category: "RSI",
    difficulty: "Expert",
    indicators: ["RSI", "Support/Resistance", "Volume"],
    timeframes: ["4H", "1D"],
    description: "Trade RSI failure swings at key levels",
    entry: "RSI fails to exceed previous high/low at key S/R",
    exit: "Price breaks significant support/resistance",
    riskReward: "1:4",
    pack: "RSI Strategy Pack"
  },
  {
    id: 15,
    name: "RSI Cutler's Method",
    category: "RSI",
    difficulty: "Expert",
    indicators: ["RSI Cutler", "Volume Profile", "VWAP"],
    timeframes: ["1H", "4H"],
    description: "Use Cutler's RSI modification for cleaner signals",
    entry: "Cutler RSI crosses threshold + volume confirmation",
    exit: "RSI momentum weakens or VWAP rejection",
    riskReward: "1:2.5",
    pack: "RSI Strategy Pack"
  },

  // Moving Averages & Trend Pack (D)
  {
    id: 16,
    name: "Golden Cross Strategy",
    category: "Moving Averages",
    difficulty: "Beginner",
    indicators: ["EMA 50", "EMA 200", "Volume"],
    timeframes: ["1D", "1W"],
    description: "Trade when 50 EMA crosses above 200 EMA",
    entry: "50 EMA crosses above 200 EMA + volume spike",
    exit: "50 EMA crosses below 200 EMA",
    riskReward: "1:5",
    pack: "Moving Averages & Trend Pack"
  },
  {
    id: 17,
    name: "Triple EMA Crossover",
    category: "Moving Averages",
    difficulty: "Intermediate",
    indicators: ["EMA 8", "EMA 13", "EMA 21", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Use three EMAs for trend confirmation and entries",
    entry: "Fast EMA > Medium EMA > Slow EMA alignment",
    exit: "EMA alignment breaks or stop loss hit",
    riskReward: "1:2.5",
    pack: "Moving Averages & Trend Pack"
  },
  {
    id: 18,
    name: "VWAP Bounce Strategy",
    category: "Moving Averages",
    difficulty: "Intermediate",
    indicators: ["VWAP", "Volume", "ATR"],
    timeframes: ["5M", "15M", "1H"],
    description: "Trade bounces off VWAP in trending markets",
    entry: "Price bounces off VWAP + volume confirmation",
    exit: "Price moves 2x ATR or breaks VWAP decisively",
    riskReward: "1:2",
    pack: "Moving Averages & Trend Pack"
  },
  {
    id: 19,
    name: "Hull Moving Average Trend",
    category: "Moving Averages",
    difficulty: "Advanced",
    indicators: ["Hull MA", "RSI", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Use Hull MA for reduced lag trend following",
    entry: "Hull MA changes color + RSI confirms trend",
    exit: "Hull MA color changes or RSI divergence",
    riskReward: "1:3",
    pack: "Moving Averages & Trend Pack"
  },
  {
    id: 20,
    name: "Adaptive Moving Average System",
    category: "Moving Averages",
    difficulty: "Expert",
    indicators: ["KAMA", "Volatility Index", "Volume"],
    timeframes: ["4H", "1D"],
    description: "Use Kaufman's Adaptive MA for volatile markets",
    entry: "KAMA trend change + volatility expansion",
    exit: "KAMA flattens or volatility contracts",
    riskReward: "1:3.5",
    pack: "Moving Averages & Trend Pack"
  },

  // Stochastic & Oscillators Pack (E)
  {
    id: 21,
    name: "Stochastic %K %D Cross",
    category: "Stochastic",
    difficulty: "Beginner",
    indicators: ["Stochastic %K", "Stochastic %D", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Trade crossovers of %K and %D lines",
    entry: "%K crosses above %D below 20 oversold zone",
    exit: "%K crosses below %D above 80 overbought zone",
    riskReward: "1:2",
    pack: "Stochastic & Oscillators Pack"
  },
  {
    id: 22,
    name: "Slow Stochastic Divergence",
    category: "Stochastic",
    difficulty: "Advanced",
    indicators: ["Slow Stochastic", "Price Action", "Trend Lines"],
    timeframes: ["4H", "1D"],
    description: "Identify divergences using slow stochastic",
    entry: "Bearish divergence in uptrend + stoch turns down",
    exit: "Price breaks trend line or stoch reaches extreme",
    riskReward: "1:3.5",
    pack: "Stochastic & Oscillators Pack"
  },
  {
    id: 23,
    name: "Williams %R Overbought/Oversold",
    category: "Williams %R",
    difficulty: "Beginner",
    indicators: ["Williams %R", "Price Action", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Trade extreme readings in Williams %R",
    entry: "%R below -80 (oversold) + bullish price action",
    exit: "%R above -20 (overbought) or stop loss",
    riskReward: "1:2",
    pack: "Stochastic & Oscillators Pack"
  },
  {
    id: 24,
    name: "On Balance Volume Trend (OBV)",
    category: "Volume",
    difficulty: "Intermediate",
    indicators: ["OBV", "Price Trend", "MA"],
    timeframes: ["1H", "4H"],
    description: "Confirm trends using On Balance Volume",
    entry: "OBV breaks resistance + price follows",
    exit: "OBV diverges from price or MA breaks",
    riskReward: "1:2.5",
    pack: "Volume & Volume-Price Pack"
  },
  {
    id: 25,
    name: "Volume Price Trend Indicator (VPT)",
    category: "Volume",
    difficulty: "Advanced",
    indicators: ["VPT", "Price Action", "Trend Lines"],
    timeframes: ["4H", "1D"],
    description: "Use VPT for volume-adjusted price analysis",
    entry: "VPT trend line break + price confirmation",
    exit: "VPT momentum fails or reverses",
    riskReward: "1:3.5",
    pack: "Volume & Volume-Price Pack"
  },
  {
    id: 26,
    name: "Rate of Change Momentum (ROC)",
    category: "Momentum",
    difficulty: "Intermediate",
    indicators: ["ROC", "MA", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Trade momentum using Rate of Change indicator",
    entry: "ROC crosses above zero + MA support",
    exit: "ROC crosses below zero or MA breaks",
    riskReward: "1:2.5",
    pack: "Stochastic & Oscillators Pack"
  },
  {
    id: 27,
    name: "Price Momentum Oscillator (PMO)",
    category: "Momentum",
    difficulty: "Advanced",
    indicators: ["PMO", "Signal Line", "Trend"],
    timeframes: ["4H", "1D"],
    description: "Use DecisionPoint's PMO for momentum analysis",
    entry: "PMO crosses above signal line + uptrend",
    exit: "PMO crosses below signal or trend breaks",
    riskReward: "1:3",
    pack: "Stochastic & Oscillators Pack"
  },
  {
    id: 28,
    name: "ADX Trend Strength Filter",
    category: "ADX/DMI",
    difficulty: "Intermediate",
    indicators: ["ADX", "DI+", "DI-", "EMA"],
    timeframes: ["1H", "4H"],
    description: "Use ADX to filter strong trending moves",
    entry: "ADX > 25 + DI+ > DI- + price above EMA",
    exit: "ADX < 20 or DI crossover reverses",
    riskReward: "1:3",
    pack: "Volume & Volume-Price Pack"
  },
  {
    id: 29,
    name: "Parabolic SAR Trend Following",
    category: "Parabolic SAR",
    difficulty: "Beginner",
    indicators: ["Parabolic SAR", "EMA", "Volume"],
    timeframes: ["4H", "1D"],
    description: "Follow trends using SAR stop and reverse points",
    entry: "SAR flips below price + EMA alignment",
    exit: "SAR flips above price or volume dies",
    riskReward: "1:3",
    pack: "Volume & Volume-Price Pack"
  },
  {
    id: 30,
    name: "Fibonacci Retracement Bounce",
    category: "Fibonacci",
    difficulty: "Beginner",
    indicators: ["Fibonacci Retracement", "Support/Resistance", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Trade bounces from key Fibonacci levels",
    entry: "Price bounces from 61.8% or 50% retracement",
    exit: "Price reaches 100% extension or fails retest",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 31,
    name: "Ichimoku Cloud Breakout",
    category: "Ichimoku",
    difficulty: "Intermediate",
    indicators: ["Ichimoku Cloud", "Tenkan", "Kijun", "Volume"],
    timeframes: ["4H", "1D"],
    description: "Trade breakouts above/below Ichimoku cloud",
    entry: "Price breaks above cloud + Tenkan > Kijun",
    exit: "Price re-enters cloud or Tenkan < Kijun",
    riskReward: "1:3",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 32,
    name: "Standard Pivot Point Trading",
    category: "Pivot Points",
    difficulty: "Beginner",
    indicators: ["Pivot Points", "S1/S2/S3", "R1/R2/R3", "Volume"],
    timeframes: ["15M", "1H"],
    description: "Trade bounces and breaks of pivot levels",
    entry: "Price bounces from pivot level + volume",
    exit: "Price reaches next pivot level or fails",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 33,
    name: "Market Profile Value Area",
    category: "Advanced",
    difficulty: "Expert",
    indicators: ["Market Profile", "Value Area", "POC", "Volume"],
    timeframes: ["30M", "1H"],
    description: "Trade using Market Profile value area concepts",
    entry: "Price at value area extreme + volume confirmation",
    exit: "Price reaches POC or breaks value area",
    riskReward: "1:3",
    pack: "Market Structure & Profile Pack"
  },
  {
    id: 34,
    name: "Triple Confirmation System",
    category: "Multi-Indicator",
    difficulty: "Advanced",
    indicators: ["MACD", "RSI", "Bollinger Bands", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Require confirmation from three different indicator types",
    entry: "MACD bullish + RSI oversold recovery + BB breakout + volume",
    exit: "Any indicator turns bearish or stops hit",
    riskReward: "1:3",
    pack: "Advanced Confirmation Pack"
  },
  {
    id: 35,
    name: "CCI Zero Line Cross",
    category: "CCI",
    difficulty: "Beginner",
    indicators: ["CCI", "Volume", "Trend"],
    timeframes: ["1H", "4H"],
    description: "Trade CCI crosses above/below zero line",
    entry: "CCI crosses above 0 + volume confirmation",
    exit: "CCI crosses below 0 or hits +100 level",
    riskReward: "1:2",
    pack: "Stochastic & Oscillators Pack"
  },
  {
    id: 37,
    name: "Multi-Timeframe Trend Alignment",
    category: "Trend Following",
    difficulty: "Advanced",
    indicators: ["Daily EMA", "4H EMA", "1H Entry", "Volume"],
    timeframes: ["1D", "4H", "1H"],
    description: "Align trends across multiple timeframes for high-probability entries",
    entry: "Daily uptrend + 4H pullback + 1H reversal signal",
    exit: "4H trend changes or daily EMA breaks",
    riskReward: "1:4",
    pack: "Advanced Confirmation Pack"
  },
  {
    id: 38,
    name: "5-Minute Scalping System",
    category: "Scalping",
    difficulty: "Expert",
    indicators: ["EMA 5", "EMA 10", "RSI", "Volume"],
    timeframes: ["5M", "1M"],
    description: "Quick scalps using fast EMAs and momentum",
    entry: "EMA 5 > EMA 10 + RSI > 50 + volume spike",
    exit: "EMA cross or 10-pip target/5-pip stop",
    riskReward: "1:2",
    pack: "Trading Styles Pack"
  },
  {
    id: 39,
    name: "Weekly Swing Strategy",
    category: "Swing Trading",
    difficulty: "Intermediate",
    indicators: ["Weekly EMA", "Daily RSI", "Support/Resistance"],
    timeframes: ["1W", "1D"],
    description: "Hold positions for days to weeks based on weekly trends",
    entry: "Weekly EMA support + daily RSI oversold + S/R level",
    exit: "Weekly trend change or major resistance",
    riskReward: "1:5",
    pack: "Trading Styles Pack"
  },
  {
    id: 40,
    name: "Oversold Bounce Strategy",
    category: "Mean Reversion",
    difficulty: "Beginner",
    indicators: ["RSI", "Bollinger Bands", "Support Levels"],
    timeframes: ["4H", "1D"],
    description: "Buy oversold conditions at support levels",
    entry: "RSI < 25 + price at BB lower band + support level",
    exit: "RSI > 70 or resistance level reached",
    riskReward: "1:2.5",
    pack: "Trading Styles Pack"
  },

  // Hidden duplicate entry for BB Squeeze Breakout
  {
    id: 36,
    name: "Bollinger Band Squeeze Breakout",
    category: "Breakout",
    difficulty: "Intermediate",
    indicators: ["Bollinger Bands", "Volume", "ATR"],
    timeframes: ["1H", "4H"],
    description: "Trade explosive moves after volatility compression",
    entry: "BB squeeze + volume expansion on breakout direction",
    exit: "Volatility exhaustion or opposite BB touch",
    riskReward: "1:3.5",
    pack: "Bollinger Bands Strategy Pack",
    hidden: true  // Hide this duplicate in favor of "Bollinger Band Squeeze"
  },

  // Additional Classic Strategies
  {
    id: 41,
    name: "Holy Grail Trading Strategy",
    category: "EMA + ADX",
    difficulty: "Advanced",
    indicators: ["EMA", "ADX", "DI+", "DI-"],
    timeframes: ["1H", "4H"],
    description: "Linda Raschke's classic: EMA + ADX pullback continuation. Very similar logic to Slingshot but with ADX filter.",
    entry: "EMA pullback + ADX > 25 + DI+ > DI- confirmation",
    exit: "ADX weakens or EMA breaks decisively",
    riskReward: "1:3",
    pack: "Advanced Confirmation Pack"
  },
  {
    id: 42,
    name: "Vegas Tunnel Strategy",
    category: "EMA Envelope",
    difficulty: "Intermediate",
    indicators: ["EMA 144", "EMA 169", "Price Envelope"],
    timeframes: ["1H", "4H"],
    description: "Uses 144 EMA and 169 EMA envelopes to define trend 'tunnels' for entries/exits.",
    entry: "Price enters tunnel between 144/169 EMAs in trend direction",
    exit: "Price exits tunnel or trend reversal confirmed",
    riskReward: "1:2.5",
    pack: "Moving Averages & Trend Pack"
  },
  {
    id: 43,
    name: "London Breakout Strategy",
    category: "Session Breakout",
    difficulty: "Intermediate",
    indicators: ["Asian Range", "Volume", "London Open"],
    timeframes: ["5M", "15M", "1H"],
    description: "Forex-specific: trade breakouts during London session after Asian session range.",
    entry: "Price breaks Asian session high/low during London open + volume",
    exit: "End of London session or range retest failure",
    riskReward: "1:2",
    pack: "Trading Styles Pack"
  },
  {
    id: 44,
    name: "Asian Session Range Breakout",
    category: "Session Breakout", 
    difficulty: "Beginner",
    indicators: ["Asian Range", "Volume", "Momentum"],
    timeframes: ["15M", "1H"],
    description: "Focuses on Asian consolidation followed by London momentum breakout.",
    entry: "Asian range defined + breakout with momentum confirmation",
    exit: "Range retest or momentum exhaustion",
    riskReward: "1:2",
    pack: "Trading Styles Pack"
  },
  {
    id: 45,
    name: "Opening Range Breakout (ORB) Strategy",
    category: "Opening Range",
    difficulty: "Beginner",
    indicators: ["Opening Range", "Volume", "ATR"],
    timeframes: ["5M", "15M", "1H"],
    description: "Trade breakouts of the first hour's range with volume confirmation.",
    entry: "Price breaks opening range high/low + volume above average",
    exit: "End of day or ATR-based target reached",
    riskReward: "1:2.5",
    pack: "Trading Styles Pack"
  },
  {
    id: 46,
    name: "The 9/30 Trading Strategy",
    category: "EMA Crossover",
    difficulty: "Beginner",
    indicators: ["EMA 9", "EMA 30", "Volume"],
    timeframes: ["15M", "1H", "4H"],
    description: "Uses EMA 9 and EMA 30 for momentum pullback entries.",
    entry: "EMA 9 above EMA 30 + pullback to EMA 9 + bounce",
    exit: "EMA 9 crosses below EMA 30 or stop loss",
    riskReward: "1:2",
    pack: "Moving Averages & Trend Pack"
  },
  {
    id: 47,
    name: "Turtle Soup Strategy",
    category: "Counter-Trend",
    difficulty: "Advanced",
    indicators: ["Breakout Levels", "Volume", "Price Action"],
    timeframes: ["1H", "4H"],
    description: "Larry Connors' counter-trend method targeting fake breakout reversals.",
    entry: "Failed breakout + reversal candle + volume confirmation",
    exit: "Price reaches previous support/resistance or trend resumes",
    riskReward: "1:3",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 48,
    name: "Pop and Drop Strategy",
    category: "Parabolic Reversal",
    difficulty: "Expert",
    indicators: ["Volume Spike", "RSI", "Price Velocity"],
    timeframes: ["1M", "5M", "15M"],
    description: "Day-trading strategy on parabolic price spikes followed by sharp reversal.",
    entry: "Parabolic move + volume exhaustion + RSI extreme",
    exit: "Quick scalp target or momentum resumption",
    riskReward: "1:1.5",
    pack: "Trading Styles Pack"
  },
  {
    id: 49,
    name: "Darvas Box Strategy",
    category: "Box Breakout",
    difficulty: "Intermediate",
    indicators: ["Price Boxes", "Volume", "New Highs"],
    timeframes: ["1D", "1W"],
    description: "Nicolas Darvas' trend-following system based on breakout of price 'boxes'.",
    entry: "New box high + volume expansion + uptrend intact",
    exit: "Box low break or trend deterioration",
    riskReward: "1:4",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 50,
    name: "Supertrend Strategy",
    category: "Trend Following",
    difficulty: "Beginner",
    indicators: ["Supertrend", "ATR", "Volume"],
    timeframes: ["1H", "4H", "1D"],
    description: "Uses the Supertrend indicator (ATR-based trailing filter) for trend following.",
    entry: "Supertrend flips bullish + price above indicator",
    exit: "Supertrend flips bearish or ATR stop triggered",
    riskReward: "1:3",
    pack: "Volume & Volume-Price Pack"
  },
  {
    id: 51,
    name: "Heikin Ashi Trend Rider",
    category: "Candlestick",
    difficulty: "Intermediate",
    indicators: ["Heikin Ashi", "EMA", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Relies on Heikin Ashi candle smoothing with MA filters.",
    entry: "HA candles turn bullish + price above EMA + volume",
    exit: "HA candles turn bearish or EMA break",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 52,
    name: "Guppy Multiple Moving Average (GMMA)",
    category: "Multiple EMA",
    difficulty: "Advanced",
    indicators: ["Multiple EMAs", "Short-term Group", "Long-term Group"],
    timeframes: ["1H", "4H"],
    description: "Uses multiple EMAs (short-term + long-term groups) to identify transitions.",
    entry: "Short-term EMAs cross above long-term group + expansion",
    exit: "EMA groups compress or crossover reverses",
    riskReward: "1:3",
    pack: "Moving Averages & Trend Pack"
  },
  {
    id: 53,
    name: "Alligator Strategy",
    category: "Bill Williams",
    difficulty: "Intermediate",
    indicators: ["Alligator Jaw", "Alligator Teeth", "Alligator Lips"],
    timeframes: ["1H", "4H"],
    description: "Bill Williams' system with Alligator indicator (Jaw/Teeth/Lips MAs).",
    entry: "Price above all three Alligator lines + lines expanding",
    exit: "Price returns to Alligator mouth or lines converge",
    riskReward: "1:2.5",
    pack: "Advanced Confirmation Pack"
  },
  {
    id: 54,
    name: "Fractal Breakout Strategy",
    category: "Bill Williams",
    difficulty: "Advanced",
    indicators: ["Fractals", "Alligator", "Volume"],
    timeframes: ["1H", "4H"],
    description: "Bill Williams system: breakout confirmation from fractal levels.",
    entry: "Fractal high break + Alligator alignment + volume",
    exit: "Opposite fractal signal or Alligator reversal",
    riskReward: "1:3",
    pack: "Advanced Confirmation Pack"
  },
  {
    id: 55,
    name: "Big Shadow Strategy",
    category: "Candlestick Pattern",
    difficulty: "Beginner",
    indicators: ["Candlestick Patterns", "Volume", "Support/Resistance"],
    timeframes: ["1H", "4H"],
    description: "Candle pattern method using large engulfing bars for reversals.",
    entry: "Large engulfing candle + high volume + key level",
    exit: "Pattern confirmation fails or target reached",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 56,
    name: "Dead Cat Bounce Strategy",
    category: "Counter-Trend",
    difficulty: "Advanced",
    indicators: ["Downtrend", "Bounce Pattern", "Volume"],
    timeframes: ["4H", "1D"],
    description: "Short-selling setup after strong downtrend and small corrective rally.",
    entry: "Strong downtrend + weak bounce + volume drying up",
    exit: "New lows achieved or bounce gains momentum",
    riskReward: "1:3",
    pack: "Trading Styles Pack"
  },
  {
    id: 57,
    name: "Gap and Go Strategy",
    category: "Gap Trading",
    difficulty: "Intermediate",
    indicators: ["Price Gap", "Volume", "Pre-market"],
    timeframes: ["5M", "15M", "1H"],
    description: "Day-trading stocks: trade continuation after a gap-up/down open.",
    entry: "Gap open + volume confirmation + momentum continuation",
    exit: "Gap fill or end of day session",
    riskReward: "1:2",
    pack: "Trading Styles Pack"
  },
  {
    id: 58,
    name: "Rubber Band Strategy",
    category: "Mean Reversion",
    difficulty: "Beginner",
    indicators: ["Bollinger Bands", "EMA", "RSI"],
    timeframes: ["15M", "1H", "4H"],
    description: "Price stretches far from Bollinger/EMA, then reverts like a rubber band.",
    entry: "Price 2+ standard deviations from mean + oversold RSI",
    exit: "Price returns to mean or momentum exhausts",
    riskReward: "1:2",
    pack: "Bollinger Bands Strategy Pack"
  },
  {
    id: 59,
    name: "3-Bar Play Strategy",
    category: "Price Action",
    difficulty: "Intermediate",
    indicators: ["Candlestick Pattern", "Volume", "Momentum"],
    timeframes: ["5M", "15M", "1H"],
    description: "Day trading setup: momentum bar → consolidation bar → breakout bar.",
    entry: "3-bar pattern completion + volume on breakout bar",
    exit: "Pattern fails or quick scalp target hit",
    riskReward: "1:1.5",
    pack: "Trading Styles Pack"
  },
  {
    id: 60,
    name: "Inside Bar Breakout Strategy",
    category: "Price Action",
    difficulty: "Beginner",
    indicators: ["Inside Bar Pattern", "Volume", "Key Levels"],
    timeframes: ["1H", "4H"],
    description: "Classic price-action pattern: enter on breakout of inside bar range.",
    entry: "Inside bar identified + breakout with volume confirmation",
    exit: "Opposite side of inside bar or target reached",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 61,
    name: "Outside Bar Strategy",
    category: "Candlestick Pattern",
    difficulty: "Beginner",
    indicators: ["Engulfing Pattern", "Volume", "Trend Context"],
    timeframes: ["1H", "4H"],
    description: "Enter on bullish/bearish engulfing candle pattern confirmation.",
    entry: "Engulfing pattern + volume increase + trend context",
    exit: "Pattern invalidation or target achievement",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 62,
    name: "Head and Shoulders Breakout Strategy",
    category: "Chart Pattern",
    difficulty: "Intermediate",
    indicators: ["H&S Pattern", "Neckline", "Volume"],
    timeframes: ["4H", "1D"],
    description: "Uses neckline break as entry trigger for H&S pattern completion.",
    entry: "H&S pattern complete + neckline break + volume confirmation",
    exit: "Pattern target reached or neckline reclaim",
    riskReward: "1:3",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 63,
    name: "Cup and Handle Strategy",
    category: "Chart Pattern",
    difficulty: "Intermediate",
    indicators: ["Cup Pattern", "Handle", "Volume"],
    timeframes: ["1D", "1W"],
    description: "Chart pattern continuation strategy for bullish formations.",
    entry: "Handle breakout + volume expansion + cup depth target",
    exit: "Pattern failure or measured move completion",
    riskReward: "1:3.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 64,
    name: "Flag and Pennant Strategy",
    category: "Chart Pattern",
    difficulty: "Beginner",
    indicators: ["Flag Pattern", "Pennant", "Volume"],
    timeframes: ["15M", "1H", "4H"],
    description: "Trade breakout after trend continuation flag/pennant formation.",
    entry: "Flag/pennant breakout + volume confirmation + trend intact",
    exit: "Pattern target or trend reversal",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 65,
    name: "Rising/Falling Wedge Breakout",
    category: "Chart Pattern",
    difficulty: "Intermediate",
    indicators: ["Wedge Pattern", "Trendlines", "Volume"],
    timeframes: ["1H", "4H", "1D"],
    description: "Price action breakout play using wedge pattern reversals.",
    entry: "Wedge pattern break + volume confirmation + momentum shift",
    exit: "Pattern target reached or false breakout confirmed",
    riskReward: "1:3",
    pack: "Levels & Patterns Pack"
  },

  // TIER 1: High-Reliability Pattern Strategies (15 patterns)
  {
    id: 66,
    name: "Inverted Head and Shoulders Breakout",
    category: "Chart Pattern",
    difficulty: "Intermediate",
    indicators: ["H&S Pattern", "Neckline", "Volume", "Support Levels"],
    timeframes: ["4H", "1D"],
    description: "Bullish reversal with three troughs - mirror of Head & Shoulders. 85% accuracy when confirmed.",
    entry: "Neckline break above with volume expansion (1.5x average) + right shoulder higher than left",
    exit: "Measured move target = Neckline + Pattern Height or neckline reclaim",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 67,
    name: "Double Top Reversal Strategy",
    category: "Chart Pattern",
    difficulty: "Beginner",
    indicators: ["Double Peak Pattern", "Support Level", "Volume Divergence"],
    timeframes: ["4H", "1D"],
    description: "Two equal peaks at resistance with declining volume on second peak. 78% success rate.",
    entry: "Break below support valley between peaks + volume confirmation + peaks within 3%",
    exit: "Measured move = Support - Pattern Height or pattern invalidation",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 68,
    name: "Double Bottom Reversal Strategy",
    category: "Chart Pattern",
    difficulty: "Beginner",
    indicators: ["Double Trough Pattern", "Resistance Level", "Volume Expansion"],
    timeframes: ["4H", "1D"],
    description: "Two equal troughs at support with volume increase. 78% success rate with confirmation.",
    entry: "Break above resistance peak between troughs + strong volume + troughs within 3%",
    exit: "Measured move = Resistance + Pattern Height or support break",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 69,
    name: "Triple Top Reversal Strategy",
    category: "Chart Pattern",
    difficulty: "Advanced",
    indicators: ["Triple Peak Pattern", "Support Level", "Volume Distribution"],
    timeframes: ["1D", "1W"],
    description: "Three failed attempts at resistance with declining volume. 80% success - stronger than double top.",
    entry: "Break below support connecting valleys + heavy volume + all peaks within 2-3%",
    exit: "Enhanced target = Support - (Pattern Height × 1.25) or stop above third peak",
    riskReward: "1:3.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 70,
    name: "Triple Bottom Reversal Strategy",
    category: "Chart Pattern",
    difficulty: "Advanced",
    indicators: ["Triple Trough Pattern", "Resistance Level", "Volume Accumulation"],
    timeframes: ["1D", "1W"],
    description: "Three support tests with strong buying interest. 80% success - more reliable than double bottom.",
    entry: "Break above resistance connecting peaks + volume expansion + troughs within 2-3%",
    exit: "Enhanced target = Resistance + (Pattern Height × 1.25) or stop below third trough",
    riskReward: "1:3.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 71,
    name: "Ascending Triangle Breakout",
    category: "Chart Pattern",
    difficulty: "Beginner",
    indicators: ["Horizontal Resistance", "Ascending Support", "Volume"],
    timeframes: ["1H", "4H", "1D"],
    description: "Bullish continuation with flat top and rising lows. 73% success rate - excellent risk/reward.",
    entry: "Break above horizontal resistance + volume spike + minimum 2 touches on each line",
    exit: "Pattern height projection from breakout point or support trendline break",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 72,
    name: "Descending Triangle Breakdown",
    category: "Chart Pattern",
    difficulty: "Beginner",
    indicators: ["Horizontal Support", "Descending Resistance", "Volume"],
    timeframes: ["1H", "4H", "1D"],
    description: "Bearish continuation with flat bottom and declining highs. 64% success rate.",
    entry: "Break below horizontal support + volume confirmation + minimum 2 touches each line",
    exit: "Pattern height projection downward from breakdown or resistance trendline reclaim",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 73,
    name: "Symmetrical Triangle Strategy",
    category: "Chart Pattern",
    difficulty: "Intermediate",
    indicators: ["Converging Trendlines", "Volume", "Momentum"],
    timeframes: ["1H", "4H", "1D"],
    description: "Neutral pattern with equal highs/lows convergence. 75% success - direction determined by breakout.",
    entry: "Breakout direction (either side) + volume expansion + break occurs at 50-75% of pattern width",
    exit: "75% of pattern height projected in breakout direction or false break",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 74,
    name: "Bull Flag Continuation",
    category: "Chart Pattern",
    difficulty: "Beginner",
    indicators: ["Flag Pole", "Parallel Channels", "Volume"],
    timeframes: ["15M", "1H", "4H"],
    description: "Brief consolidation after strong rally. 86% success - one of the highest reliability patterns.",
    entry: "Break above upper channel + volume surge + flag slopes against trend",
    exit: "Pole height projected from breakout or flag support break",
    riskReward: "1:3",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 75,
    name: "Bear Flag Continuation",
    category: "Chart Pattern",
    difficulty: "Beginner",
    indicators: ["Flag Pole", "Parallel Channels", "Volume"],
    timeframes: ["15M", "1H", "4H"],
    description: "Brief consolidation after strong decline. 82% success - reliable bearish continuation.",
    entry: "Break below lower channel + volume increase + flag slopes against trend",
    exit: "Pole height projected downward from breakdown or flag resistance reclaim",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 76,
    name: "Pennant Breakout Strategy",
    category: "Chart Pattern",
    difficulty: "Intermediate",
    indicators: ["Small Triangle", "Flag Pole", "Volume"],
    timeframes: ["15M", "1H", "4H"],
    description: "Mini symmetrical triangle after strong move. 76% success - similar to flags but triangular.",
    entry: "Triangle breakout in trend direction + volume expansion + forms quickly (1-3 weeks)",
    exit: "Pole height projected from breakout or pattern invalidation",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 77,
    name: "Rectangle Range Breakout",
    category: "Chart Pattern",
    difficulty: "Beginner",
    indicators: ["Horizontal Support", "Horizontal Resistance", "Volume"],
    timeframes: ["1H", "4H", "1D"],
    description: "Trading range consolidation. 67% success - clear boundaries make excellent risk management.",
    entry: "Break above resistance or below support + volume confirmation + minimum 2 touches each side",
    exit: "Range height projected in breakout direction or opposite boundary reclaim",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 78,
    name: "Hammer Reversal Strategy",
    category: "Candlestick Pattern",
    difficulty: "Beginner",
    indicators: ["Hammer Candle", "Support Levels", "Volume", "Trend Context"],
    timeframes: ["1H", "4H", "1D"],
    description: "Bullish reversal with long lower wick (2-3x body). 60% success at support levels.",
    entry: "Hammer at support + next candle closes above hammer high + volume confirmation",
    exit: "ATR-based target (2-3x ATR) or next resistance level",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 79,
    name: "Shooting Star Reversal Strategy",
    category: "Candlestick Pattern",
    difficulty: "Beginner",
    indicators: ["Shooting Star Candle", "Resistance Levels", "Volume", "Trend Context"],
    timeframes: ["1H", "4H", "1D"],
    description: "Bearish reversal with long upper wick. 62% success at resistance levels.",
    entry: "Shooting star at resistance + next candle closes below shooting star low + volume",
    exit: "ATR-based target (2-3x ATR) or next support level",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 80,
    name: "Doji Indecision Strategy",
    category: "Candlestick Pattern",
    difficulty: "Beginner",
    indicators: ["Doji Candle", "Support/Resistance", "Volume", "Trend"],
    timeframes: ["1H", "4H", "1D"],
    description: "Indecision candle signals potential reversal. 52% success - requires strong confirmation.",
    entry: "Doji at key level + next candle direction confirms + increased volume",
    exit: "Context-based: resistance/support levels or ATR-based stops",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },

  // TIER 2: Enhanced Confirmation Pattern Strategies (6 patterns)
  {
    id: 81,
    name: "Bump-and-Run Reversal Pattern",
    category: "Chart Pattern",
    difficulty: "Advanced",
    indicators: ["Trendline Phases", "Volume", "Momentum Indicators"],
    timeframes: ["4H", "1D", "1W"],
    description: "Three-phase reversal: lead-in, bump (acceleration), run (reversal). 64% success - complex but powerful.",
    entry: "Break below trendline from bump phase + volume confirmation + momentum divergence",
    exit: "Return to lead-in trendline or pattern invalidation if trend resumes",
    riskReward: "1:2.5",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 82,
    name: "Island Reversal Strategy",
    category: "Chart Pattern",
    difficulty: "Advanced",
    indicators: ["Gap Detection", "Volume", "Trend Context"],
    timeframes: ["1D", "1W"],
    description: "Gap-isolated pattern showing strong reversal. 59% success - rare but significant when appears.",
    entry: "Breakaway gap in new direction + exhaustion gap isolation confirmed",
    exit: "Gap fill level or major support/resistance in reversal direction",
    riskReward: "1:3",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 83,
    name: "Hanging Man Reversal Strategy",
    category: "Candlestick Pattern",
    difficulty: "Beginner",
    indicators: ["Hanging Man Candle", "Uptrend Context", "Volume", "Resistance"],
    timeframes: ["1H", "4H", "1D"],
    description: "Bearish reversal at top of uptrend with long lower wick. 59% success with trend context.",
    entry: "Hanging man at resistance in uptrend + next candle closes below + volume confirmation",
    exit: "ATR-based target or next support level",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 84,
    name: "Bullish Harami Strategy",
    category: "Candlestick Pattern",
    difficulty: "Intermediate",
    indicators: ["Harami Pattern", "Support Levels", "Volume", "Trend"],
    timeframes: ["4H", "1D"],
    description: "Small bullish candle inside previous large bearish candle. 63% success - shows momentum shift.",
    entry: "Harami at support + next candle confirms direction + volume expansion",
    exit: "Previous swing high or ATR-based target",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 85,
    name: "Bearish Harami Strategy",
    category: "Candlestick Pattern",
    difficulty: "Intermediate",
    indicators: ["Harami Pattern", "Resistance Levels", "Volume", "Trend"],
    timeframes: ["4H", "1D"],
    description: "Small bearish candle inside previous large bullish candle. 61% success - reversal warning signal.",
    entry: "Harami at resistance + next candle confirms direction + volume expansion",
    exit: "Previous swing low or ATR-based target",
    riskReward: "1:2",
    pack: "Levels & Patterns Pack"
  },
  {
    id: 86,
    name: "Spinning Top Reversal Strategy",
    category: "Candlestick Pattern",
    difficulty: "Beginner",
    indicators: ["Spinning Top", "Support/Resistance", "Volume", "Confirmation"],
    timeframes: ["1H", "4H", "1D"],
    description: "Small body with long wicks shows indecision. 45% success alone - REQUIRES strong confirmation.",
    entry: "Spinning top at key level + multiple confirmation indicators + next candle direction",
    exit: "Conservative targets due to lower reliability - ATR or nearest S/R level",
    riskReward: "1:1.5",
    pack: "Levels & Patterns Pack"
  }
];