import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { email, report, timezone, markets, timeSpan, tone } = await req.json();

    console.log("Sending market report to:", email);

    if (!email || !report) {
      throw new Error("Email and report are required");
    }

    // Format the report for email
    const timeSpanText = timeSpan === "previous_day" ? "Previous Day" : "Past 5 Sessions";
    const marketList = markets.join(", ").toUpperCase();

    // Convert markdown to HTML for better email rendering
    const htmlReport = report
      .replace(/## (.*)/g, '<h2 style="color: #333; margin-top: 24px; margin-bottom: 12px;">$1</h2>')
      .replace(/### (.*)/g, '<h3 style="color: #555; margin-top: 16px; margin-bottom: 8px;">$1</h3>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/\n\n/g, '</p><p style="margin: 12px 0;">')
      .replace(/- (.*)/g, '<li style="margin-left: 20px;">$1</li>');

    const emailHtml = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Market Breadth Report</title>
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f5f5f5; margin: 0; padding: 0;">
          <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 40px 20px;">
            <div style="text-align: center; margin-bottom: 32px;">
              <h1 style="color: #1a1a1a; font-size: 28px; margin: 0 0 8px 0;">Market Breadth Report</h1>
              <p style="color: #666; font-size: 14px; margin: 0;">Generated on ${new Date().toLocaleString('en-US', { timeZone: timezone })}</p>
            </div>

            <div style="background-color: #f9f9f9; border-left: 4px solid #4f46e5; padding: 16px; margin-bottom: 24px;">
              <p style="margin: 0; font-size: 14px; color: #333;">
                <strong>Markets:</strong> ${marketList}<br>
                <strong>Time Span:</strong> ${timeSpanText}<br>
                <strong>Timezone:</strong> ${timezone}<br>
                <strong>Tone:</strong> ${tone.charAt(0).toUpperCase() + tone.slice(1)}
              </p>
            </div>

            <div style="color: #333; font-size: 14px; line-height: 1.6;">
              <p style="margin: 12px 0;">${htmlReport}</p>
            </div>

            <div style="margin-top: 40px; padding-top: 24px; border-top: 1px solid #e0e0e0; text-align: center;">
              <p style="color: #888; font-size: 12px; margin: 0;">
                This report is for informational purposes only and should not be considered financial advice.
              </p>
              <p style="color: #888; font-size: 12px; margin: 8px 0 0 0;">
                Generated by Market Analysis Tool
              </p>
            </div>
          </div>
        </body>
      </html>
    `;

    const emailResponse = await resend.emails.send({
      from: "Market Analysis <onboarding@resend.dev>",
      to: [email],
      subject: `Market Breadth Report - ${timeSpanText} (${new Date().toLocaleDateString()})`,
      html: emailHtml,
    });

    console.log("Email sent successfully:", emailResponse);

    return new Response(
      JSON.stringify({ success: true, messageId: emailResponse.id }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error: any) {
    console.error("Error in send-market-report:", error);
    return new Response(
      JSON.stringify({ error: error.message || "Failed to send email" }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});