-- Update trading strategy articles with precise examples and practice setups
-- This migration enhances the 100 strategies with actionable examples

-- Update RSI Strategy with precise example
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: EUR/USD RSI Example\n\n**Scenario:** EUR/USD daily chart showing RSI oversold bounce\n\n**Setup Details:**\n- **Pair:** EUR/USD\n- **Timeframe:** Daily\n- **Date:** RSI drops to 25 after 5 consecutive red candles\n- **Price at Signal:** 1.0850\n\n**Trade Execution:**\n1. **Entry:** 1.0865 (after RSI crosses back above 30 with bullish candle)\n2. **Stop Loss:** 1.0795 (below recent swing low, 70 pips)\n3. **Take Profit 1:** 1.0935 (1:1 R:R, 70 pips)\n4. **Take Profit 2:** 1.1005 (2:1 R:R, 140 pips)\n\n**Position Sizing Example:**\n- Account: $10,000\n- Risk: 1% = $100\n- Stop: 70 pips = 0.0070\n- Position: $100 / 70 pips = ~$1.43/pip = 0.14 lots\n\n**What to Watch:**\n- RSI divergence at the 30 level (higher lows in RSI while price makes lower lows)\n- Volume spike on the reversal candle\n- Break of short-term trendline confirming reversal'
WHERE slug = 'rsi-trading-strategy';

-- Update MACD Strategy with precise example
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Apple (AAPL) MACD Example\n\n**Scenario:** AAPL 4-hour chart MACD bullish crossover\n\n**Setup Details:**\n- **Stock:** Apple (AAPL)\n- **Timeframe:** 4-Hour\n- **Context:** Price above 50 EMA, trending higher\n- **Price at Signal:** $175.50\n\n**Trade Execution:**\n1. **Entry:** $176.00 (after MACD line crosses above signal line + histogram turns green)\n2. **Stop Loss:** $172.50 (below recent swing low, $3.50 risk)\n3. **Take Profit 1:** $179.50 (1:1 R:R)\n4. **Take Profit 2:** $183.00 (2:1 R:R)\n\n**Position Sizing Example:**\n- Account: $25,000\n- Risk: 2% = $500\n- Stop: $3.50 per share\n- Position: $500 / $3.50 = 142 shares\n\n**Confirmation Checklist:**\n- [ ] MACD line above signal line\n- [ ] Histogram bars growing (momentum increasing)\n- [ ] Price above 50-period moving average\n- [ ] No major resistance within 1R distance'
WHERE slug = 'macd-complete-strategy';

-- Update Bollinger Bands Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Gold (XAU/USD) Bollinger Band Example\n\n**Scenario:** Gold touches lower Bollinger Band with RSI confirmation\n\n**Setup Details:**\n- **Instrument:** XAU/USD (Spot Gold)\n- **Timeframe:** 1-Hour\n- **Bollinger Settings:** 20-period, 2 standard deviations\n- **Price at Signal:** $1,945.00 (touching lower band)\n\n**Trade Execution:**\n1. **Entry:** $1,948.00 (after bounce candle closes above lower band)\n2. **Stop Loss:** $1,938.00 ($10 below entry, below band)\n3. **Take Profit:** $1,968.00 (middle band, $20 target)\n4. **Risk:Reward:** 1:2\n\n**Position Sizing Example:**\n- Account: $20,000\n- Risk: 1.5% = $300\n- Stop: $10 per oz\n- Position: $300 / $10 = 0.30 lots (30 oz)\n\n**Key Observations:**\n- RSI was at 28 when price touched lower band (double confirmation)\n- Previous two touches of lower band resulted in bounces to middle band\n- Volume decreased during the drop (exhaustion selling)'
WHERE slug = 'bollinger-bands-complete';

-- Update Fibonacci Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: S&P 500 Fibonacci Retracement Example\n\n**Scenario:** ES futures pullback to 61.8% Fibonacci level\n\n**Setup Details:**\n- **Instrument:** E-mini S&P 500 (ES)\n- **Timeframe:** Daily\n- **Trend:** Uptrend from 4,100 swing low to 4,400 swing high\n- **Retracement:** Price pulled back to 4,215 (61.8% level)\n\n**Fibonacci Levels:**\n- 0%: 4,400 (swing high)\n- 23.6%: 4,329\n- 38.2%: 4,285\n- 50%: 4,250\n- 61.8%: 4,215 ← Entry Zone\n- 78.6%: 4,164\n- 100%: 4,100 (swing low)\n\n**Trade Execution:**\n1. **Entry:** 4,220 (bullish engulfing at 61.8% with volume)\n2. **Stop Loss:** 4,160 (below 78.6% level, 60 points)\n3. **Take Profit 1:** 4,340 (127.2% extension, 120 points)\n4. **Take Profit 2:** 4,400 (prior high, 180 points)\n\n**Why This Works:**\n- 61.8% is the "golden pocket" - institutional buying zone\n- Confluence with previous support at 4,200\n- Volume spike on reversal candle confirms buyers stepping in'
WHERE slug = 'fibonacci-trading-complete';

-- Update Breakout Trading Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Tesla (TSLA) Breakout Example\n\n**Scenario:** TSLA breaks above 3-week consolidation range\n\n**Setup Details:**\n- **Stock:** Tesla (TSLA)\n- **Timeframe:** Daily\n- **Pattern:** Rectangle consolidation between $240-$260\n- **Consolidation Period:** 15 trading days\n\n**Trade Execution:**\n1. **Entry:** $262.50 (breakout above $260 with 2x average volume)\n2. **Stop Loss:** $254.00 (below breakout level, $8.50 risk)\n3. **Take Profit:** $282.50 (measured move: $260-$240 = $20, target = $260 + $20)\n4. **Risk:Reward:** 1:2.35\n\n**Volume Confirmation:**\n- Average daily volume: 50M shares\n- Breakout day volume: 120M shares (2.4x average) ✓\n- First pullback: 35M shares (declining volume on pullback) ✓\n\n**Position Sizing Example:**\n- Account: $50,000\n- Risk: 2% = $1,000\n- Stop: $8.50 per share\n- Position: $1,000 / $8.50 = 117 shares\n\n**Breakout Checklist:**\n- [ ] Price closes above resistance (not just a wick)\n- [ ] Volume 1.5x+ average on breakout day\n- [ ] No major earnings or news event causing artificial spike\n- [ ] Prior consolidation was at least 5 bars'
WHERE slug = 'breakout-trading-complete';

-- Update Donchian Channel / High-Low Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Crude Oil Donchian Channel Example\n\n**Scenario:** CL (Crude Oil) 20-day high breakout\n\n**Setup Details:**\n- **Instrument:** WTI Crude Oil (CL)\n- **Timeframe:** Daily\n- **Channel Period:** 20 days\n- **20-Day High:** $78.50\n- **20-Day Low:** $72.00\n\n**Trade Execution (Turtle Rules):**\n1. **Long Entry:** $78.75 (break above 20-day high)\n2. **Stop Loss (10-day low):** $75.20 (exit on 10-day low break, $3.55 risk)\n3. **Trailing Stop:** 2x ATR(20) = 2 × $1.50 = $3.00\n4. **Add Position:** Every 0.5 ATR of profit ($0.75)\n\n**Position Sizing (Turtle Method):**\n- Account: $100,000\n- ATR(20): $1.50\n- 1 ATR Risk: $1,500 per contract (1,000 barrels)\n- Risk 1% = $1,000\n- Position: $1,000 / $1,500 = 0.67 contracts → 1 contract\n\n**Unit Adding:**\n- Unit 1: $78.75 entry\n- Unit 2: $79.50 (add at +0.5 ATR with profit)\n- Unit 3: $80.25 (add at +1.0 ATR with profit)\n- Maximum: 4 units per market\n\n**Exit Rules:**\n- Exit all on 10-day low break ($75.20 initially, trailing)\n- Or exit on 2N trailing stop'
WHERE slug = 'high-low-channel-strategy';

-- Update Swing Trading Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Microsoft (MSFT) Swing Trade Example\n\n**Scenario:** MSFT pullback to 20 EMA in uptrend\n\n**Setup Details:**\n- **Stock:** Microsoft (MSFT)\n- **Timeframe:** Daily (holding 3-10 days)\n- **Trend:** Strong uptrend, 20 EMA > 50 EMA > 200 EMA\n- **Setup:** 3-day pullback to rising 20 EMA\n\n**Trade Execution:**\n1. **Entry:** $380.00 (bullish hammer at 20 EMA)\n2. **Stop Loss:** $370.00 (below 50 EMA, $10 risk)\n3. **Target 1:** $395.00 (prior swing high, 1.5:1 R:R)\n4. **Target 2:** $410.00 (extension, 3:1 R:R)\n\n**Entry Triggers (Choose One):**\n- Break above hammer high ($381.50)\n- Opening above prior day close\n- RSI(14) crosses above 50 from below\n\n**Position Sizing:**\n- Account: $30,000\n- Risk: 1.5% = $450\n- Stop: $10\n- Position: $450 / $10 = 45 shares\n\n**Swing Trade Management:**\n- Day 1-2: Hold, no action unless stop hit\n- Day 3-5: Move stop to breakeven if +1R\n- Day 5+: Trail stop below each higher low\n- Exit: Target hit or trailing stop triggered'
WHERE slug = 'swing-trading-strategy';

-- Update Moving Average Crossover Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: EUR/JPY Golden Cross Example\n\n**Scenario:** 50 EMA crosses above 200 EMA (Golden Cross)\n\n**Setup Details:**\n- **Pair:** EUR/JPY\n- **Timeframe:** Daily\n- **Signal:** 50 EMA crosses above 200 EMA at 158.50\n- **Current Price:** 159.00\n\n**Trade Execution:**\n1. **Entry:** 159.50 (next candle after crossover confirms)\n2. **Stop Loss:** 156.50 (below 200 EMA, 300 pips)\n3. **Take Profit 1:** 165.50 (2:1 R:R, 600 pips)\n4. **Take Profit 2:** Trail using 50 EMA as dynamic support\n\n**Position Sizing:**\n- Account: $15,000\n- Risk: 2% = $300\n- Stop: 300 pips = 3.00 (JPY pair)\n- Position: 0.10 lots (10,000 units)\n\n**Confirmation Filters:**\n- ADX(14) > 25 (trending market) ✓\n- RSI(14) between 50-70 (not overbought) ✓\n- Price making higher highs and higher lows ✓\n\n**Trade Management:**\n- Initial: Hold with fixed stop\n- After +1R: Move stop to entry (breakeven)\n- Trending: Trail stop below 50 EMA\n- Exit: 50 EMA crosses below 200 EMA (Death Cross)'
WHERE slug = 'moving-average-crossover-strategy';

-- Update Momentum Trading Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: NVIDIA (NVDA) Momentum Example\n\n**Scenario:** NVDA showing strong relative strength with volume surge\n\n**Setup Details:**\n- **Stock:** NVIDIA (NVDA)\n- **Timeframe:** Daily\n- **Context:** +8% in 3 days, above all major MAs\n- **Relative Strength:** Outperforming S&P 500 by 12% over 20 days\n\n**Momentum Indicators:**\n- RSI(14): 72 (strong but not extreme)\n- ROC(10): +15% (high positive momentum)\n- Volume: 3x 20-day average on breakout\n\n**Trade Execution:**\n1. **Entry:** $485.00 (flag breakout after 2-day consolidation)\n2. **Stop Loss:** $465.00 (below flag low, $20 risk)\n3. **Target 1:** $505.00 (1:1 R:R)\n4. **Target 2:** $525.00 (2:1 R:R, measured move)\n\n**Position Sizing:**\n- Account: $40,000\n- Risk: 2% = $800\n- Stop: $20\n- Position: $800 / $20 = 40 shares\n\n**Momentum Exit Signals:**\n- RSI divergence (price higher, RSI lower)\n- Volume declining for 3+ days\n- Break below 10 EMA on daily close\n- Relative strength line rolling over'
WHERE slug = 'momentum-trading-strategy';

-- Update Mean Reversion Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: SPY Mean Reversion Example\n\n**Scenario:** SPY 3 standard deviations below 20-day mean\n\n**Setup Details:**\n- **ETF:** SPDR S&P 500 (SPY)\n- **Timeframe:** Daily\n- **20-Day SMA:** $450.00\n- **Current Price:** $438.00 (2.7% below mean)\n- **Bollinger Band (2σ):** $442.00\n\n**Mean Reversion Signals:**\n- Price below lower Bollinger Band ✓\n- RSI(2): 8 (extreme oversold) ✓\n- 5-day consecutive down closes ✓\n- VIX spike > 25 ✓\n\n**Trade Execution:**\n1. **Entry:** $439.00 (after RSI(2) > 10 from below)\n2. **Stop Loss:** $432.00 (below recent low, $7 risk)\n3. **Target:** $448.00 (at 20-day moving average, $9 profit)\n4. **Risk:Reward:** 1:1.3\n\n**Position Sizing:**\n- Account: $50,000\n- Risk: 1% = $500\n- Stop: $7\n- Position: $500 / $7 = 71 shares\n\n**Mean Reversion Rules:**\n- Only trade in direction of 200-day MA (if bullish)\n- Exit at moving average, not beyond\n- Maximum hold time: 5 trading days\n- If no reversion in 5 days, exit regardless'
WHERE slug = 'mean-reversion-strategy';

-- Update Pullback Trading Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Amazon (AMZN) Pullback Example\n\n**Scenario:** AMZN pulls back to 38.2% Fibonacci + 21 EMA confluence\n\n**Setup Details:**\n- **Stock:** Amazon (AMZN)\n- **Timeframe:** 4-Hour\n- **Trend:** Strong uptrend (higher highs, higher lows)\n- **Swing Low:** $170.00\n- **Swing High:** $190.00\n\n**Confluence Zone:**\n- 38.2% Fibonacci: $182.35\n- 21 EMA: $182.00\n- Prior resistance (now support): $181.50\n\n**Trade Execution:**\n1. **Entry:** $183.00 (bullish engulfing at confluence zone)\n2. **Stop Loss:** $178.50 (below 50% Fib, $4.50 risk)\n3. **Target 1:** $190.00 (prior high, 1.5:1 R:R)\n4. **Target 2:** $197.00 (127.2% Fib extension, 3:1 R:R)\n\n**Position Sizing:**\n- Account: $35,000\n- Risk: 1.5% = $525\n- Stop: $4.50\n- Position: $525 / $4.50 = 116 shares\n\n**Pullback Quality Checklist:**\n- [ ] Trend clearly defined (20 EMA > 50 EMA)\n- [ ] Pullback is 3-5 candles (not exhausted)\n- [ ] Volume decreasing on pullback ✓\n- [ ] Clear support confluence zone ✓\n- [ ] No earnings or major news pending'
WHERE slug = 'pullback-trading-strategy';

-- Update Gap Trading Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Gap and Go Morning Trade\n\n**Scenario:** AAPL gaps up 4% on earnings beat\n\n**Pre-Market Analysis:**\n- **Stock:** Apple (AAPL)\n- **Gap:** +4% ($175 prior close → $182 pre-market)\n- **Catalyst:** Earnings beat + iPhone sales surprise\n- **Pre-market Volume:** 5x average\n\n**Gap Type:** Breakaway gap (above resistance on fundamentals)\n\n**Trade Execution (Gap and Go):**\n1. **Entry:** $183.50 (break above pre-market high at 9:35 AM)\n2. **Stop Loss:** $180.00 (below gap fill level, $3.50 risk)\n3. **Target 1:** $187.00 (1:1 R:R at 9:45 AM)\n4. **Target 2:** Trail with 5-min candle lows\n\n**Position Sizing:**\n- Account: $25,000\n- Risk: 1% = $250\n- Stop: $3.50\n- Position: $250 / $3.50 = 71 shares\n\n**Gap Trading Rules:**\n- Trade only gaps > 3% with clear catalyst\n- Wait for opening range (first 5-15 min) to form\n- Entry on break of opening range high\n- Don''t trade gap fills against strong catalyst\n- Exit by noon if target not reached'
WHERE slug = 'gap-trading-complete';

-- Update Reversal Trading Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Double Bottom Reversal\n\n**Scenario:** GBP/USD double bottom at major support\n\n**Setup Details:**\n- **Pair:** GBP/USD\n- **Timeframe:** 4-Hour\n- **Pattern:** Double bottom at 1.2100\n- **Neckline:** 1.2350\n\n**Pattern Formation:**\n- First Low: 1.2105 (with volume spike)\n- Rally: Up to 1.2350 (neckline)\n- Second Low: 1.2095 (slightly lower, RSI divergence)\n- Confirmation: Break above 1.2350\n\n**Trade Execution:**\n1. **Entry:** 1.2375 (neckline break with confirmation candle)\n2. **Stop Loss:** 1.2150 (below pattern low, 225 pips)\n3. **Target:** 1.2625 (measured move: 1.2350 + 250 pips pattern height)\n4. **Risk:Reward:** 1:1.1\n\n**Position Sizing:**\n- Account: $20,000\n- Risk: 2% = $400\n- Stop: 225 pips\n- Position: 0.18 lots\n\n**Reversal Confirmation:**\n- RSI divergence at second bottom ✓\n- Volume higher on second bottom ✓\n- Bullish engulfing at second low ✓\n- Break above neckline with volume ✓'
WHERE slug = 'reversal-trading-strategy';

-- Update Day Trading Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Opening Range Breakout\n\n**Scenario:** QQQ 15-minute opening range breakout\n\n**Setup Details:**\n- **ETF:** Invesco QQQ Trust (QQQ)\n- **Timeframe:** 15-minute (for OR), 1-minute (for entry)\n- **Opening Range (9:30-9:45 AM):**\n  - High: $380.50\n  - Low: $378.00\n\n**Trade Execution:**\n1. **Long Entry:** $380.75 (break above OR high at 9:50 AM)\n2. **Stop Loss:** $379.00 (at OR midpoint, $1.75 risk)\n3. **Target 1:** $382.25 (1x OR height = $2.50, at 10:15 AM)\n4. **Target 2:** $384.00 (2x OR height, if momentum continues)\n\n**Position Sizing:**\n- Account: $30,000 (day trading minimum)\n- Risk: 0.5% = $150 per trade\n- Stop: $1.75\n- Position: $150 / $1.75 = 85 shares\n\n**Day Trading Rules:**\n- Only trade OR breakouts in direction of gap\n- Best setups: 9:45-10:30 AM and 2:00-3:30 PM\n- Avoid 11:00 AM - 2:00 PM (lunch chop)\n- Flatten all positions by 3:55 PM\n- Maximum 3 trades per day'
WHERE slug = 'day-trading-strategy';

-- Update Position Trading Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Weekly Chart Position Trade\n\n**Scenario:** SPY weekly breakout from 6-month base\n\n**Setup Details:**\n- **ETF:** SPDR S&P 500 (SPY)\n- **Timeframe:** Weekly\n- **Pattern:** 6-month cup with handle\n- **Base Range:** $420-$440\n- **Breakout Level:** $442\n\n**Trade Execution:**\n1. **Entry:** $445.00 (weekly close above breakout level)\n2. **Stop Loss:** $420.00 (below base low, $25 risk)\n3. **Target 1:** $470.00 (cup depth projection)\n4. **Target 2:** $495.00 (hold for trend continuation)\n5. **Expected Hold Time:** 3-12 months\n\n**Position Sizing (Conservative):**\n- Account: $100,000\n- Risk: 5% = $5,000 (position trades use wider stops)\n- Stop: $25\n- Position: $5,000 / $25 = 200 shares\n\n**Position Management:**\n- Week 1-4: Hold, only exit on weekly close below stop\n- Month 2: Add 50% position on first pullback to 10 WMA\n- Month 3+: Trail stop below 10 WMA\n- Final Exit: Break below 10 WMA on weekly close\n\n**Monthly Review Checklist:**\n- [ ] Is the trend still intact (higher highs/lows)?\n- [ ] Is relative strength positive vs benchmark?\n- [ ] Are there fundamental changes to the thesis?\n- [ ] Has maximum hold time been reached?'
WHERE slug = 'position-trading-strategy';

-- Update VWAP Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: VWAP Pullback Long\n\n**Scenario:** SPY pulls back to rising VWAP for long entry\n\n**Setup Details:**\n- **ETF:** SPDR S&P 500 (SPY)\n- **Timeframe:** 5-minute\n- **Time:** 10:30 AM EST\n- **Context:** Gap up day, VWAP trending higher\n\n**VWAP Analysis:**\n- VWAP at 10:00 AM: $451.50\n- VWAP at 10:30 AM: $452.00 (rising)\n- Current Price: $452.25 (first touch of rising VWAP)\n\n**Trade Execution:**\n1. **Entry:** $452.50 (bounce from VWAP with bullish candle)\n2. **Stop Loss:** $451.25 (below VWAP, $1.25 risk)\n3. **Target 1:** $454.00 (prior high of day, 1.2:1 R:R)\n4. **Target 2:** $455.25 (2.2:1 R:R)\n\n**Position Sizing:**\n- Account: $30,000\n- Risk: 0.5% = $150\n- Stop: $1.25\n- Position: $150 / $1.25 = 120 shares\n\n**VWAP Rules:**\n- Long only when price > VWAP and VWAP rising\n- Short only when price < VWAP and VWAP falling\n- Best trades: First 1-2 touches of VWAP\n- Avoid trades in last 30 min (closing volatility)\n- Exit all positions before close'
WHERE slug = 'vwap-strategy';

-- Update Pairs Trading Strategy  
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: XOM/CVX Energy Pair\n\n**Scenario:** XOM/CVX ratio diverges 2.5 standard deviations\n\n**Setup Details:**\n- **Long Leg:** Exxon Mobil (XOM) - undervalued\n- **Short Leg:** Chevron (CVX) - overvalued\n- **Correlation:** 0.87 (highly correlated)\n- **Z-Score:** -2.5 (XOM cheap relative to CVX)\n\n**Ratio Analysis:**\n- 60-day Mean Ratio: 1.10 (XOM/CVX)\n- Current Ratio: 0.95 (-2.5 std dev)\n- Target Ratio: 1.10 (mean reversion)\n\n**Trade Execution:**\n1. **Long XOM:** 100 shares at $105.00 = $10,500\n2. **Short CVX:** 65 shares at $160.00 = $10,400\n3. **Dollar Neutral:** ~$100 difference (acceptable)\n\n**Exit Targets:**\n- **Target:** Ratio returns to mean (1.10)\n- **Stop:** Ratio expands to -3.5 std dev\n- **Time Stop:** 30 trading days maximum\n\n**P&L Scenarios:**\n- If ratio returns to 1.10:\n  - XOM rises to $110, CVX flat: +$500 - $0 = +$500\n  - XOM flat, CVX falls to $155: $0 + $325 = +$325\n- Expected: Combination of both moving toward mean\n\n**Risk Management:**\n- Beta-adjusted position if betas differ significantly\n- Monitor correlation daily (exit if < 0.70)\n- Maximum drawdown: 5% of capital allocated'
WHERE slug = 'pairs-trading';

-- Update Scalping Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: ES Futures Scalp\n\n**Scenario:** E-mini S&P 500 order flow scalp\n\n**Setup Details:**\n- **Instrument:** ES (E-mini S&P 500)\n- **Timeframe:** 1-minute / Tick chart\n- **Time:** 10:00 AM EST (post-open)\n- **Context:** Price consolidating at 4520 round number\n\n**Trade Execution:**\n1. **Entry:** 4520.25 (break above consolidation)\n2. **Stop Loss:** 4518.75 (6 ticks, $75 risk per contract)\n3. **Target:** 4522.25 (8 ticks, $100 profit per contract)\n4. **Risk:Reward:** 1:1.33\n5. **Duration:** 30 seconds to 3 minutes\n\n**Position Sizing:**\n- Account: $25,000\n- Risk per trade: 0.3% = $75\n- ES tick value: $12.50\n- Stop: 6 ticks = $75\n- Position: 1 contract\n\n**Scalping Rules:**\n- Maximum 10 trades per session\n- Stop after 3 consecutive losses\n- Only trade high-volume periods (9:30-11:00, 14:00-16:00)\n- No trades around major news releases\n- Keep win rate > 60% for profitability\n\n**Order Flow Signals:**\n- Large bid stacking below price (support)\n- Volume delta positive (more buying)\n- Tape reading: Large buyers absorbing sells'
WHERE slug = 'scalping-strategy';

-- Update EMA Crossover Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: 9/21 EMA Crossover\n\n**Scenario:** Bitcoin (BTC) 9 EMA crosses above 21 EMA\n\n**Setup Details:**\n- **Instrument:** BTC/USD\n- **Timeframe:** 4-Hour\n- **9 EMA:** $42,500 (fast)\n- **21 EMA:** $41,800 (slow)\n- **Crossover Price:** $43,000\n\n**Trade Execution:**\n1. **Entry:** $43,200 (candle close after crossover confirmed)\n2. **Stop Loss:** $40,500 (below 21 EMA at crossover, $2,700 risk)\n3. **Target 1:** $48,600 (2:1 R:R)\n4. **Target 2:** Trail below 9 EMA\n\n**Position Sizing:**\n- Account: $20,000\n- Risk: 2% = $400\n- Stop: $2,700 per BTC\n- Position: $400 / $2,700 = 0.148 BTC (~$6,400 notional)\n\n**EMA Crossover Filters:**\n- ADX > 20 (confirm trending environment)\n- Price > 50 EMA (broader trend bullish)\n- RSI 40-60 (not overbought)\n- No major resistance within 1R\n\n**Exit Strategy:**\n- Exit 50% at Target 1 (2:1 R:R)\n- Trail remaining 50% below 9 EMA\n- Full exit on bearish crossover'
WHERE slug = 'ema-crossover-strategy';

-- Update Ichimoku Strategy
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Ichimoku Cloud Breakout\n\n**Scenario:** USD/JPY breaks above Kumo cloud\n\n**Setup Details:**\n- **Pair:** USD/JPY\n- **Timeframe:** Daily\n- **Cloud Status:** Price breaking above cloud after consolidation\n- **Senkou Span A:** 148.50 (cloud top)\n- **Current Price:** 149.20\n\n**Ichimoku Signals:**\n- Price above cloud: Bullish ✓\n- Tenkan-sen (9) > Kijun-sen (26): Bullish ✓\n- Chikou Span above price 26 periods ago: Bullish ✓\n- Future cloud green (Senkou A > B): Bullish ✓\n\n**Trade Execution:**\n1. **Entry:** 149.50 (confirmed close above cloud)\n2. **Stop Loss:** 147.00 (below Kijun-sen, 250 pips)\n3. **Target 1:** 154.50 (prior swing high, 2:1 R:R)\n4. **Target 2:** 157.00 (cloud projection target)\n\n**Position Sizing:**\n- Account: $30,000\n- Risk: 2% = $600\n- Stop: 250 pips\n- Position: 0.24 lots\n\n**Ichimoku Exit Rules:**\n- Trail stop below Kijun-sen (26-period baseline)\n- Exit on bearish TK cross (Tenkan below Kijun)\n- Full exit if price closes inside cloud\n- Take profit at 3:1 R:R or cloud resistance'
WHERE slug = 'ichimoku-strategy';

-- Update Head and Shoulders Trading
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Head and Shoulders Short\n\n**Scenario:** EUR/GBP forms head and shoulders at resistance\n\n**Setup Details:**\n- **Pair:** EUR/GBP\n- **Timeframe:** 4-Hour\n- **Pattern Duration:** 3 weeks\n\n**Pattern Points:**\n- Left Shoulder High: 0.8650\n- Head High: 0.8720\n- Right Shoulder High: 0.8640\n- Neckline: 0.8550 (connecting lows)\n\n**Trade Execution:**\n1. **Entry:** 0.8535 (neckline break with confirmation candle)\n2. **Stop Loss:** 0.8660 (above right shoulder, 125 pips)\n3. **Target:** 0.8365 (pattern height projection: 0.8720-0.8550=170 pips)\n4. **Risk:Reward:** 1:1.36\n\n**Position Sizing:**\n- Account: $15,000\n- Risk: 1.5% = $225\n- Stop: 125 pips\n- Position: 0.18 lots\n\n**Pattern Validation:**\n- Left and right shoulders roughly equal height ✓\n- Head clearly higher than both shoulders ✓\n- Neckline slope: Slightly rising (stronger signal)\n- Volume: Declining from left shoulder to head to right shoulder ✓\n- RSI divergence at head (lower high in RSI) ✓'
WHERE slug = 'head-shoulders-trading';

-- Update Volume Spread Analysis
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: VSA Climactic Action\n\n**Scenario:** Selling climax followed by test\n\n**Setup Details:**\n- **Stock:** Meta (META)\n- **Timeframe:** Daily\n- **Context:** Downtrend approaching major support\n\n**VSA Sequence:**\n1. **Climactic Bar:** Large down bar, ultra-high volume, closes off lows\n   - Range: $15 (high $290, low $275, close $282)\n   - Volume: 5x average (distribution complete)\n   \n2. **Automatic Rally:** 3 green bars on decreasing volume\n   - Price: $282 → $295\n   \n3. **Test Bar:** Down bar, LOW volume, tests $278\n   - Range: $8, Volume: 0.5x average\n   - Closes in middle of range\n\n**Trade Execution:**\n1. **Entry:** $285.00 (next candle after successful low-volume test)\n2. **Stop Loss:** $272.00 (below climax low, $13 risk)\n3. **Target 1:** $305.00 (1.5:1 R:R)\n4. **Target 2:** $320.00 (prior swing high, 2.7:1 R:R)\n\n**Position Sizing:**\n- Account: $40,000\n- Risk: 2% = $800\n- Stop: $13\n- Position: $800 / $13 = 61 shares\n\n**VSA Confirmation:**\n- Climax bar: Wide spread, high volume, close off lows ✓\n- Test bar: Narrow spread, low volume, holds above climax low ✓\n- No supply: Test proves sellers exhausted ✓'
WHERE slug = 'volume-spread-analysis';

-- Update Flags and Pennants Trading
UPDATE learning_articles SET content = content || E'\n\n## Practice Trade Setup: Bull Flag Breakout\n\n**Scenario:** AMD forms bull flag after strong impulse move\n\n**Setup Details:**\n- **Stock:** AMD (Advanced Micro Devices)\n- **Timeframe:** 1-Hour\n- **Pole:** $120 to $135 (+12.5% in 2 days)\n- **Flag:** 4-day consolidation between $132-$136\n\n**Pattern Measurements:**\n- Pole Height: $15 ($120 → $135)\n- Flag Duration: 4 days (8 candles on 4H)\n- Flag Retracement: 20% of pole (healthy < 38%)\n\n**Trade Execution:**\n1. **Entry:** $136.50 (break above flag resistance)\n2. **Stop Loss:** $131.50 (below flag low, $5 risk)\n3. **Target:** $151.50 (pole height added: $136.50 + $15)\n4. **Risk:Reward:** 1:3\n\n**Position Sizing:**\n- Account: $25,000\n- Risk: 2% = $500\n- Stop: $5\n- Position: $500 / $5 = 100 shares\n\n**Bull Flag Quality Check:**\n- [ ] Pole has angle > 45 degrees (strong impulse) ✓\n- [ ] Flag retraces < 50% of pole ✓\n- [ ] Flag duration: 3-15 bars ideal ✓\n- [ ] Volume decreasing during flag ✓\n- [ ] Breakout on above-average volume ✓\n\n**Flag vs Pennant:**\n- Flag: Parallel channel (rectangle)\n- Pennant: Converging trendlines (triangle)\n- Same measured move target applies to both'
WHERE slug = 'flags-pennants-trading';