
-- 8H scan jobs (run at 00:15, 08:15, 16:15 UTC)
SELECT cron.schedule('scan-live-8h-stocks',    '15 0,8,16 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"stocks","timeframe":"8h","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

SELECT cron.schedule('scan-live-8h-etfs',      '15 0,8,16 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"etfs","timeframe":"8h","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

SELECT cron.schedule('scan-live-8h-commodities','15 0,8,16 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"commodities","timeframe":"8h","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

SELECT cron.schedule('scan-live-8h-crypto',    '15 0,8,16 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"crypto","timeframe":"8h","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

SELECT cron.schedule('scan-live-8h-indices',   '15 0,8,16 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"indices","timeframe":"8h","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

SELECT cron.schedule('scan-live-8h-fx',        '15 0,8,16 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"fx","timeframe":"8h","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

-- 1D scan jobs (run once daily at 05:00 UTC)
SELECT cron.schedule('scan-live-1d-stocks',    '0 5 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"stocks","timeframe":"1d","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

SELECT cron.schedule('scan-live-1d-etfs',      '0 5 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"etfs","timeframe":"1d","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

SELECT cron.schedule('scan-live-1d-commodities','0 5 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"commodities","timeframe":"1d","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

SELECT cron.schedule('scan-live-1d-crypto',    '0 5 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"crypto","timeframe":"1d","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

SELECT cron.schedule('scan-live-1d-indices',   '0 5 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"indices","timeframe":"1d","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);

SELECT cron.schedule('scan-live-1d-fx',        '0 5 * * *', $$SELECT net.http_post(url := 'https://dgznlsckoamseqcpzfqm.supabase.co/functions/v1/scan-live-patterns', headers := '{"Content-Type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnem5sc2Nrb2Ftc2VxY3B6ZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzA2MzcsImV4cCI6MjA3MTMwNjYzN30.qvXqakZccAMJK7pFpcxHRFu-mrGEA4R1Zo21uzjcMt8"}'::jsonb, body := '{"assetType":"fx","timeframe":"1d","forceRefresh":true,"maxTickers":100}'::jsonb) AS request_id;$$);
