-- Insert new Trading Strategy articles
INSERT INTO public.learning_articles (
  slug, title, excerpt, content, category, difficulty_level, reading_time_minutes, tags, status, published_at
) VALUES
('rsi-divergence-strategy', 'RSI Divergence Strategy: Catching Reversals', 'Identify trend reversals using regular and hidden RSI divergence patterns with confirmation techniques.', 'Master the art of identifying trend reversals using RSI divergence patterns — one of the most reliable momentum-based signals in technical analysis.', 'Trading Strategies', 'intermediate', 12, ARRAY['rsi', 'divergence', 'momentum', 'reversal'], 'published', NOW()),
('vwap-strategy', 'VWAP Trading Strategy: Institutional Edge', 'Trade with the institutional benchmark using VWAP bounces, breakouts, and intraday mean reversion.', 'Learn to trade with VWAP (Volume Weighted Average Price) — the institutional benchmark used by professional traders to identify fair value and optimal entry points.', 'Trading Strategies', 'intermediate', 10, ARRAY['vwap', 'intraday', 'institutional', 'volume'], 'published', NOW()),
('fibonacci-strategy', 'Fibonacci Retracement Strategy: Natural Levels', 'Master the Golden Pocket (61.8%) and other Fib levels for high-probability entries and targets.', 'Master Fibonacci retracements and extensions to identify high-probability entry points and profit targets based on natural mathematical ratios.', 'Trading Strategies', 'intermediate', 14, ARRAY['fibonacci', 'retracement', 'extension', 'technical'], 'published', NOW()),
('support-resistance-strategy', 'Support & Resistance Strategy: Key Levels', 'Trade bounces, breakouts, and role reversals at horizontal support and resistance zones.', 'Master the foundational trading strategy that underpins all technical analysis — identifying and trading key support and resistance levels for consistent profits.', 'Trading Strategies', 'beginner', 12, ARRAY['support', 'resistance', 'price-action', 'levels'], 'published', NOW()),
('gap-trading-strategy', 'Gap Trading Strategy: Opening Range Plays', 'Profit from price gaps using gap fill, gap-and-go, and opening range breakout strategies.', 'Learn to profit from price gaps — the high-probability setups that occur when markets open significantly higher or lower than the previous close.', 'Trading Strategies', 'intermediate', 11, ARRAY['gap', 'opening-range', 'intraday', 'breakout'], 'published', NOW()),
('momentum-strategy', 'Momentum Trading Strategy', 'Ride strong trends by entering positions when momentum indicators confirm directional strength.', 'Momentum trading focuses on capturing gains in strongly trending assets by entering when momentum is strongest.', 'Trading Strategies', 'intermediate', 10, ARRAY['momentum', 'trend', 'rsi', 'macd'], 'published', NOW()),
('swing-trading-strategy', 'Swing Trading Strategy', 'Capture multi-day moves by trading swings within established trends using technical patterns.', 'Swing trading involves holding positions for several days to weeks to profit from expected price swings.', 'Trading Strategies', 'intermediate', 12, ARRAY['swing', 'multi-day', 'trend', 'patterns'], 'published', NOW()),
('position-trading-strategy', 'Position Trading Strategy', 'Build long-term positions based on fundamental and technical analysis for major trend moves.', 'Position trading is a long-term strategy where traders hold positions for weeks to months based on major trend analysis.', 'Trading Strategies', 'advanced', 15, ARRAY['position', 'long-term', 'fundamental', 'trend'], 'published', NOW()),
('macd-strategy', 'MACD Crossover Strategy', 'Trade MACD signal line crossovers and histogram divergences for trend confirmation entries.', 'The MACD (Moving Average Convergence Divergence) is one of the most popular momentum indicators for timing entries.', 'Trading Strategies', 'intermediate', 18, ARRAY['macd', 'crossover', 'momentum', 'signals'], 'published', NOW()),
('bollinger-bands-strategy', 'Bollinger Bands Strategy: Volatility Trading', 'Trade band squeezes, walks, and mean reversion using standard deviation envelopes.', 'Bollinger Bands help identify volatility conditions and potential reversal points using standard deviation bands.', 'Trading Strategies', 'intermediate', 18, ARRAY['bollinger', 'volatility', 'bands', 'mean-reversion'], 'published', NOW())
ON CONFLICT (slug) DO NOTHING;